import type { LearningPath } from "@/types/glossary";

export const learningPaths: LearningPath[] = [
  {
    slug: "como-funciona-chatgpt",
    title: "Cómo funciona ChatGPT",
    question: "¿Cómo funciona ChatGPT?",
    description: "De qué es la IA hasta cómo un modelo de lenguaje aprende a conversar. La ruta más completa para empezar desde cero.",
    difficulty: "beginner",
    steps: [
      { slug: "artificial-intelligence", note: "El campo completo" },
      { slug: "machine-learning", note: "Aprender a partir de datos" },
      { slug: "neural-network", note: "El bloque básico" },
      { slug: "deep-learning", note: "Muchas capas, mucha capacidad" },
      { slug: "token", note: "Cómo lee texto un modelo" },
      { slug: "embeddings", note: "Cómo representa significado" },
      { slug: "attention", note: "Cómo relaciona palabras" },
      { slug: "transformer", note: "La arquitectura completa" },
      { slug: "llm", note: "El modelo de lenguaje" },
      { slug: "fine-tuning", note: "Especializarlo" },
      { slug: "rlhf", note: "Hacerlo útil y seguro" },
      { slug: "inference", note: "Usarlo en cada conversación" },
    ],
  },
  {
    slug: "que-es-un-llm",
    title: "Qué es realmente un LLM",
    question: "¿Qué es realmente un LLM?",
    description: "Tokens, predicción del siguiente token, contexto y por qué a veces se equivocan.",
    difficulty: "intermediate",
    steps: [
      { slug: "token" },
      { slug: "tokenization" },
      { slug: "next-token-prediction" },
      { slug: "pretraining" },
      { slug: "llm" },
      { slug: "context-window" },
      { slug: "sampling" },
      { slug: "temperature" },
      { slug: "hallucination" },
      { slug: "reasoning-model" },
    ],
  },
  {
    slug: "aprende-rag",
    title: "Aprende RAG",
    question: "¿Cómo funciona RAG?",
    description: "Cómo conectar un modelo de lenguaje con tus propios documentos para que responda con información actual y verificable.",
    difficulty: "intermediate",
    steps: [
      { slug: "llm" },
      { slug: "embeddings" },
      { slug: "semantic-search" },
      { slug: "vector-database" },
      { slug: "chunking" },
      { slug: "retrieval" },
      { slug: "reranking" },
      { slug: "rag" },
      { slug: "grounding" },
      { slug: "agentic-rag" },
    ],
  },
  {
    slug: "aprende-agentes",
    title: "Aprende AI Agents",
    question: "¿Qué son los agentes de IA?",
    description: "De un modelo que conversa a un sistema que usa herramientas, planifica y actúa.",
    difficulty: "advanced",
    steps: [
      { slug: "llm" },
      { slug: "prompt" },
      { slug: "function-calling" },
      { slug: "tool-calling" },
      { slug: "memory" },
      { slug: "planning" },
      { slug: "ai-agent" },
      { slug: "multi-agent-system" },
      { slug: "computer-use" },
      { slug: "prompt-injection", note: "El riesgo que hay que conocer" },
    ],
  },
  {
    slug: "como-aprende-una-ia",
    title: "Cómo aprende una IA",
    question: "¿Cómo aprende una IA?",
    description: "Datos, pérdida, gradientes y backpropagation: el ciclo de entrenamiento explicado paso a paso.",
    difficulty: "beginner",
    steps: [
      { slug: "data" },
      { slug: "dataset" },
      { slug: "model" },
      { slug: "training" },
      { slug: "loss-function" },
      { slug: "gradient" },
      { slug: "gradient-descent" },
      { slug: "backpropagation" },
      { slug: "overfitting" },
      { slug: "generalization" },
    ],
  },
  {
    slug: "como-genera-imagenes",
    title: "Cómo genera imágenes una IA",
    question: "¿Cómo genera imágenes una IA?",
    description: "De píxeles y convoluciones a los modelos de difusión que convierten texto en imágenes.",
    difficulty: "intermediate",
    steps: [
      { slug: "computer-vision" },
      { slug: "cnn" },
      { slug: "vision-transformer" },
      { slug: "latent-space" },
      { slug: "gan" },
      { slug: "diffusion-model" },
      { slug: "latent-diffusion" },
      { slug: "image-generation" },
      { slug: "multimodal-model" },
    ],
  },
  {
    slug: "matematicas-de-la-ia",
    title: "Las matemáticas de la IA, sin miedo",
    question: "¿Qué matemáticas necesito?",
    description: "Las ideas matemáticas mínimas para entender cómo funcionan los modelos por dentro.",
    difficulty: "intermediate",
    steps: [
      { slug: "scalar" },
      { slug: "vector" },
      { slug: "matrix" },
      { slug: "dot-product" },
      { slug: "cosine-similarity" },
      { slug: "probability" },
      { slug: "softmax" },
      { slug: "cross-entropy" },
      { slug: "derivative" },
      { slug: "gradient" },
    ],
  },
  {
    slug: "ia-segura",
    title: "IA segura y alineada",
    question: "¿Cómo se hace segura una IA?",
    description: "Alineación, ataques, defensas e interpretabilidad: cómo se intenta que la IA haga lo que queremos.",
    difficulty: "advanced",
    steps: [
      { slug: "ai-safety" },
      { slug: "hallucination" },
      { slug: "algorithmic-bias" },
      { slug: "alignment" },
      { slug: "rlhf" },
      { slug: "constitutional-ai" },
      { slug: "jailbreak" },
      { slug: "prompt-injection" },
      { slug: "interpretability" },
      { slug: "mechanistic-interpretability" },
    ],
  },
];
