import type { TermInput } from "@/types/glossary";

export const agentTerms: TermInput[] = [
  {
    slug: "ai-agent",
    name: "AI Agent",
    spanishName: "Agente de IA",
    aliases: ["Agente de IA", "Agentes de IA", "Agente", "Agentes", "AI Agents", "LLM agent"],
    category: "agents",
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition: "Un sistema en el que un modelo de IA decide por sí mismo qué pasos dar y qué herramientas usar para cumplir un objetivo.",
    simpleExplanation:
      "Un chatbot responde preguntas. Un agente **hace cosas**. Le das un objetivo —«encuentra los tres vuelos más baratos a Madrid y compáralos»— y el agente decide qué buscar, usa herramientas, revisa los resultados, corrige el rumbo y te entrega el resultado.\n\nLa clave es el ciclo: pensar, actuar, observar el resultado y volver a pensar, hasta terminar.",
    analogy:
      "Un LLM solo es como un experto encerrado en una habitación que únicamente puede hablar. Un agente es ese mismo experto con una computadora, teléfono y acceso a archivos: puede investigar, calcular y actuar por su cuenta.",
    inThirtySeconds: [
      "Recibe un objetivo.",
      "El LLM decide el siguiente paso.",
      "Llama a una herramienta (buscar, ejecutar código, consultar una API).",
      "Observa el resultado y actualiza su plan.",
      "Repite hasta cumplir el objetivo o pedir ayuda.",
    ],
    diagram: {
      kind: "flow",
      title: "El ciclo de un agente",
      steps: [
        { label: "Objetivo", detail: "«Resume las ventas del trimestre y envía el reporte»" },
        { label: "Razonar", detail: "El LLM decide qué hacer a continuación" },
        { label: "Actuar", chips: ["consultar_sql()", "crear_grafica()", "enviar_email()"] },
        { label: "Observar", detail: "Lee el resultado de la herramienta" },
        { label: "¿Terminado?", detail: "Si no, vuelve a razonar con la nueva información" },
      ],
    },
    mentalModel: [
      { label: "Agente", meaning: "LLM + herramientas + ciclo de decisión." },
      { label: "Herramientas", meaning: "Las manos del agente." },
      { label: "Memoria", meaning: "Lo que recuerda entre pasos y sesiones." },
      { label: "Planificación", meaning: "Cómo divide un objetivo en pasos." },
    ],
    comparison: {
      title: "AI Agent vs. Workflow",
      columns: ["Agente", "Workflow"],
      rows: [
        { aspect: "Quién decide los pasos", a: "El modelo, dinámicamente", b: "El desarrollador, de antemano" },
        { aspect: "Previsibilidad", a: "Menor", b: "Alta" },
        { aspect: "Flexibilidad", a: "Alta: se adapta a lo inesperado", b: "Limitada al flujo definido" },
        { aspect: "Costo y latencia", a: "Variables y a menudo mayores", b: "Predecibles" },
        { aspect: "Ideal para", a: "Tareas abiertas y de muchos pasos", b: "Procesos bien definidos y repetibles" },
      ],
    },
    technicalExplanation:
      "Un agente basado en LLM combina: un modelo que razona; un conjunto de herramientas descritas con esquemas ([[tool-calling]]); un bucle de control que ejecuta las llamadas y devuelve las observaciones; y opcionalmente [[memory|memoria]], [[planning|planificación]] y mecanismos de [[human-in-the-loop|supervisión humana]]. El patrón [[react-pattern|ReAct]] (razonar y actuar intercalados) es la base de muchos diseños.\n\nLos retos principales son la fiabilidad en tareas largas (los errores se acumulan), la seguridad (acciones irreversibles, [[prompt-injection]]), el costo y la evaluación. Una recomendación común es empezar por el sistema más simple posible —a menudo un [[workflow]]— y añadir autonomía solo cuando aporte valor.",
    commonMistakes: [
      "No todo lo que usa un LLM es un agente. Si los pasos están fijados en código, es un [[workflow]]; es un agente cuando el modelo decide dinámicamente la secuencia de acciones.",
    ],
    whyItMatters: "Los agentes convierten a los modelos de lenguaje de herramientas para conversar en sistemas capaces de completar trabajo real de varios pasos.",
    useCases: ["Asistentes de programación", "Investigación automatizada", "Atención al cliente con acciones", "Automatización de operaciones", "Computer use"],
    prerequisites: ["llm", "prompt", "tool-calling"],
    relatedTerms: ["tool-calling", "planning", "memory", "agentic-workflow", "multi-agent-system", "react-pattern"],
    nextTerms: ["planning", "memory", "multi-agent-system"],
    tags: ["agente", "autonomía", "herramientas", "automatización"],
    sources: [
      { title: "Building effective agents", authors: "Anthropic", year: 2024, url: "https://www.anthropic.com/research/building-effective-agents", kind: "article" },
      { title: "ReAct: Synergizing Reasoning and Acting in Language Models", authors: "Yao et al.", year: 2022, url: "https://arxiv.org/abs/2210.03629", kind: "paper" },
    ],
  },
  {
    slug: "agentic-ai",
    name: "Agentic AI",
    spanishName: "IA agéntica",
    aliases: ["IA agéntica", "Agentic", "Sistemas agénticos"],
    category: "agents",
    secondaryCategories: ["frontier"],
    difficulty: "intermediate",
    type: "concept",
    frontier: true,
    shortDefinition: "El enfoque de construir sistemas de IA que actúan con cierto grado de autonomía para lograr objetivos, en lugar de solo responder.",
    simpleExplanation:
      "«Agéntico» describe un grado, no un interruptor. Un sistema es más agéntico cuanto más decide por sí mismo: qué pasos seguir, qué herramientas usar, cuándo pedir ayuda. Va desde un chatbot que puede buscar en la web hasta sistemas que trabajan horas en una tarea compleja.",
    technicalExplanation:
      "El término agrupa [[ai-agent|agentes]], [[agentic-workflow|flujos agénticos]] y [[multi-agent-system|sistemas multiagente]]. Se caracteriza por bucles de decisión, uso de herramientas, estado persistente y horizontes de tarea largos. Su adopción depende de avances en fiabilidad, razonamiento ([[reasoning-model|modelos de razonamiento]]), estándares de integración como [[model-context-protocol|MCP]] y controles de seguridad.",
    whyItMatters: "Es la dirección principal hacia la que evoluciona el software basado en IA.",
    useCases: ["Automatización empresarial", "Asistentes de programación", "Investigación"],
    prerequisites: ["ai-agent"],
    relatedTerms: ["ai-agent", "agentic-workflow", "autonomous-agent", "computer-use"],
    nextTerms: ["agentic-workflow", "autonomous-agent"],
    tags: ["agéntico", "autonomía"],
  },
  {
    slug: "agentic-workflow",
    name: "Agentic Workflow",
    spanishName: "Flujo de trabajo agéntico",
    aliases: ["Flujo agéntico", "Flujo de trabajo agéntico", "Prompt chaining", "Encadenamiento de prompts"],
    category: "agents",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Un proceso de varios pasos donde uno o más LLMs ejecutan partes de la tarea dentro de una estructura definida por el desarrollador.",
    simpleExplanation:
      "En lugar de pedirle todo a un modelo en un solo prompt, divides la tarea: un paso extrae datos, otro los verifica, otro redacta y otro revisa. Cada paso es simple y fácil de evaluar, y el conjunto es mucho más fiable.",
    technicalExplanation:
      "Patrones comunes: **encadenamiento** (la salida de un paso es la entrada del siguiente), **enrutamiento** (un clasificador decide qué rama seguir), **paralelización** (varias llamadas simultáneas y agregación), **orquestador-trabajadores** y **evaluador-optimizador** (un modelo genera y otro critica). A diferencia de un agente totalmente autónomo, el flujo de control está mayormente definido en código, lo que mejora previsibilidad y depuración.",
    whyItMatters: "Suele ser el punto óptimo entre la flexibilidad de los LLMs y la fiabilidad del software tradicional.",
    useCases: ["Procesamiento de documentos", "Generación de reportes", "Moderación de contenido", "Pipelines de datos"],
    prerequisites: ["workflow", "prompt-engineering"],
    relatedTerms: ["workflow", "ai-agent", "orchestration", "llm-as-a-judge"],
    nextTerms: ["ai-agent", "orchestration"],
    tags: ["flujos", "encadenar", "pipeline"],
  },
  {
    slug: "workflow",
    name: "Workflow",
    spanishName: "Flujo de trabajo",
    aliases: ["Flujo de trabajo", "Pipeline"],
    category: "agents",
    secondaryCategories: ["ai-engineering"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Una secuencia predefinida de pasos para completar una tarea; en IA, un proceso cuyo orden está fijado en código aunque use modelos en algunos pasos.",
    simpleExplanation:
      "Un workflow es una receta fija: paso 1, paso 2, paso 3. Puede incluir IA (por ejemplo, «resume este correo»), pero el orden de los pasos no lo decide el modelo, lo decide quien diseñó el flujo. Eso lo hace predecible y fácil de auditar.",
    technicalExplanation:
      "Se implementa con código, herramientas de automatización o motores de orquestación. La distinción con un [[ai-agent|agente]] es quién controla el flujo: en un workflow, el programa; en un agente, el modelo. Muchos sistemas en producción son híbridos: un workflow con algunos pasos agénticos.",
    whyItMatters: "Para procesos bien definidos, un workflow suele ser más barato, rápido y confiable que un agente.",
    useCases: ["Automatización de procesos", "ETL con IA", "Clasificación y enrutamiento de tickets"],
    relatedTerms: ["agentic-workflow", "ai-agent", "orchestration"],
    nextTerms: ["agentic-workflow", "ai-agent"],
    tags: ["proceso", "automatización", "pipeline"],
  },
  {
    slug: "tool-calling",
    name: "Tool Calling",
    spanishName: "Uso de herramientas",
    aliases: ["Tool use", "Uso de herramientas", "Llamada a herramientas", "Herramientas", "Tools"],
    category: "agents",
    secondaryCategories: ["llm", "ai-engineering"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "La capacidad de un modelo de solicitar el uso de herramientas externas —buscar, calcular, consultar APIs— y usar sus resultados para responder.",
    simpleExplanation:
      "Un LLM no puede, por sí solo, consultar el clima de hoy ni revisar tu calendario. Con tool calling, el desarrollador le describe herramientas disponibles («obtener_clima(ciudad)») y el modelo decide cuándo usarlas. El programa ejecuta la herramienta y le devuelve el resultado al modelo.\n\nEl modelo no ejecuta nada directamente: solo **pide** que se ejecute.",
    realExample: {
      title: "Una llamada a herramienta paso a paso",
      dialogue: [
        { role: "user", text: "¿Necesito paraguas hoy en Guadalajara?" },
        { role: "assistant", text: "→ obtener_clima({ \"ciudad\": \"Guadalajara\" })" },
        { role: "system", text: "Resultado: { \"lluvia\": \"70%\", \"temp\": 22 }" },
        { role: "assistant", text: "Sí, conviene llevarlo: hay 70% de probabilidad de lluvia y unos 22 °C." },
      ],
    },
    technicalExplanation:
      "El desarrollador envía definiciones de herramientas (nombre, descripción y un JSON Schema de parámetros). El modelo, entrenado para ello, puede responder con una solicitud estructurada en lugar de texto. La aplicación valida y ejecuta la llamada, añade el resultado a la conversación y vuelve a invocar al modelo. Este bucle es el corazón de los [[ai-agent|agentes]].\n\n«Function calling» y «tool calling» suelen usarse como sinónimos; «tool use» a veces incluye herramientas ejecutadas por el proveedor (búsqueda web, ejecución de código). Estándares como [[model-context-protocol|MCP]] permiten conectar herramientas de forma reutilizable. Riesgos: argumentos incorrectos, acciones no deseadas y [[prompt-injection]] a través de resultados de herramientas.",
    commonMistakes: [
      "El modelo no «tiene acceso» a tus sistemas por sí mismo. Solo propone llamadas; tu código decide si se ejecutan, con qué permisos y con qué validaciones.",
    ],
    whyItMatters: "Conecta a los modelos con el mundo real: datos actualizados, cálculos exactos y acciones en otros sistemas.",
    useCases: ["Consultar bases de datos", "Búsqueda web", "Ejecutar código", "Reservas y operaciones", "Agentes de soporte"],
    prerequisites: ["llm", "structured-output"],
    relatedTerms: ["function-calling", "ai-agent", "model-context-protocol", "computer-use", "api"],
    nextTerms: ["ai-agent", "model-context-protocol", "planning"],
    tags: ["herramientas", "tools", "apis", "acciones"],
    sources: [{ title: "Toolformer: Language Models Can Teach Themselves to Use Tools", authors: "Schick et al.", year: 2023, url: "https://arxiv.org/abs/2302.04761", kind: "paper" }],
  },
  {
    slug: "function-calling",
    name: "Function Calling",
    spanishName: "Llamada a funciones",
    aliases: ["Llamada a funciones", "Llamadas a funciones"],
    category: "agents",
    secondaryCategories: ["ai-engineering"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Hacer que un modelo genere, en formato estructurado, el nombre y los argumentos de una función que la aplicación debe ejecutar.",
    simpleExplanation:
      "Es la forma concreta en que funciona el [[tool-calling|uso de herramientas]]: el modelo escribe algo como «llama a `crear_evento` con fecha = 2026-10-03 y título = Dentista». Tu programa lee eso y ejecuta la función real.",
    example: {
      code: "{\n  \"name\": \"crear_evento\",\n  \"arguments\": {\n    \"titulo\": \"Dentista\",\n    \"fecha\": \"2026-10-03T10:00\"\n  }\n}",
    },
    technicalExplanation:
      "Se basa en [[structured-output|salida estructurada]]: el modelo produce JSON que cumple el esquema de parámetros de la función. Puede solicitar varias llamadas en paralelo. Buenas prácticas: descripciones claras de cada función y parámetro, validación estricta de argumentos, manejo de errores devolviendo mensajes útiles al modelo, y confirmación humana para acciones sensibles.",
    whyItMatters: "Es el puente técnico entre el lenguaje natural y el código existente.",
    useCases: ["Integración con APIs", "Extracción de datos", "Asistentes con acciones"],
    prerequisites: ["structured-output"],
    relatedTerms: ["tool-calling", "structured-output", "api", "ai-agent"],
    nextTerms: ["tool-calling", "ai-agent"],
    tags: ["funciones", "json", "argumentos"],
  },
  {
    slug: "model-context-protocol",
    name: "Model Context Protocol",
    acronym: "MCP",
    aliases: ["MCP", "Protocolo de contexto de modelos", "Servidor MCP"],
    category: "agents",
    secondaryCategories: ["ai-engineering"],
    difficulty: "advanced",
    type: "infrastructure",
    frontier: true,
    shortDefinition: "Un protocolo abierto para conectar aplicaciones de IA con herramientas y fuentes de datos de forma estandarizada.",
    simpleExplanation:
      "Sin un estándar, cada aplicación de IA tiene que programar su propia integración con cada servicio (calendario, base de datos, repositorio de código…). MCP propone un «enchufe universal»: un servicio se expone una vez como servidor MCP y cualquier aplicación compatible puede usarlo.",
    technicalExplanation:
      "Presentado por Anthropic en noviembre de 2024 como estándar abierto, sigue una arquitectura cliente-servidor sobre JSON-RPC. Los servidores exponen **herramientas** (acciones), **recursos** (datos) y **prompts** (plantillas). Las aplicaciones anfitrionas (asistentes, IDEs) incluyen clientes MCP que descubren y usan estas capacidades. Diversos proveedores y herramientas lo han adoptado. Consideraciones de seguridad: permisos, autenticación y riesgo de [[prompt-injection]] a través de herramientas de terceros.",
    whyItMatters: "Reduce el esfuerzo de integración y facilita un ecosistema de herramientas reutilizables para agentes.",
    useCases: ["Conectar asistentes con bases de datos", "Integraciones en IDEs", "Herramientas empresariales para agentes"],
    prerequisites: ["tool-calling", "api"],
    relatedTerms: ["tool-calling", "ai-agent", "api", "orchestration"],
    nextTerms: ["ai-agent", "computer-use"],
    tags: ["mcp", "protocolo", "integraciones", "estándar"],
    sources: [{ title: "Model Context Protocol — documentación oficial", url: "https://modelcontextprotocol.io", kind: "docs" }],
  },
  {
    slug: "react-pattern",
    name: "ReAct",
    spanishName: "Razonar y actuar",
    aliases: ["ReAct", "Reason + Act", "Razonar y actuar"],
    category: "agents",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Un patrón de agentes en el que el modelo alterna entre razonar sobre qué hacer, ejecutar una acción y observar el resultado.",
    simpleExplanation:
      "ReAct formaliza cómo piensa un agente: «Pensamiento: necesito saber la población de X. Acción: buscar(X). Observación: 1.2 millones. Pensamiento: ahora puedo calcular…». Intercalar razonamiento y acciones hace al agente más preciso y más fácil de depurar.",
    technicalExplanation:
      "Propuesto por Yao et al. (2022). Combina [[chain-of-thought]] con acciones sobre herramientas en un bucle pensamiento → acción → observación. Mostró mejoras en tareas de preguntas multi-paso y entornos interactivos frente a razonar sin actuar o actuar sin razonar. Muchas implementaciones modernas de agentes usan este bucle de forma nativa mediante [[tool-calling]].",
    whyItMatters: "Es el patrón fundacional de la mayoría de los agentes basados en LLMs.",
    useCases: ["Agentes de búsqueda", "Asistentes con herramientas", "Resolución de problemas multi-paso"],
    prerequisites: ["chain-of-thought", "tool-calling"],
    relatedTerms: ["ai-agent", "chain-of-thought", "tool-calling", "planning"],
    nextTerms: ["planning", "ai-agent"],
    tags: ["react", "razonar", "actuar", "bucle"],
    sources: [{ title: "ReAct: Synergizing Reasoning and Acting in Language Models", authors: "Yao et al.", year: 2022, url: "https://arxiv.org/abs/2210.03629", kind: "paper" }],
  },
  {
    slug: "planning",
    name: "Planning",
    spanishName: "Planificación",
    aliases: ["Planificación", "Planeación", "Task decomposition", "Descomposición de tareas"],
    category: "agents",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "La capacidad de un agente de dividir un objetivo complejo en pasos y decidir en qué orden ejecutarlos.",
    simpleExplanation:
      "«Organiza un viaje a Oaxaca» es demasiado grande para resolverlo de golpe. Planificar es convertirlo en pasos: definir fechas, buscar vuelos, comparar hoteles, armar itinerario. Un buen agente también ajusta el plan cuando algo sale distinto de lo esperado.",
    technicalExplanation:
      "Enfoques: planificación explícita previa (generar un plan y luego ejecutarlo, *plan-and-execute*), planificación intercalada ([[react-pattern|ReAct]]), búsqueda sobre árboles de alternativas y replanificación tras fallos. Los [[reasoning-model|modelos de razonamiento]] mejoraron notablemente esta capacidad. Es un área activa: los agentes aún fallan en horizontes largos por acumulación de errores.",
    whyItMatters: "Determina si un agente puede completar tareas largas o se pierde a mitad del camino.",
    useCases: ["Agentes de programación", "Asistentes de investigación", "Automatización de procesos"],
    prerequisites: ["ai-agent"],
    relatedTerms: ["ai-agent", "react-pattern", "reasoning-model", "orchestration"],
    nextTerms: ["memory", "multi-agent-system"],
    tags: ["plan", "pasos", "descomponer"],
  },
  {
    slug: "memory",
    name: "Memory",
    spanishName: "Memoria (en agentes)",
    aliases: ["Memoria", "Agent memory", "Memoria de agentes"],
    category: "agents",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "Los mecanismos que permiten a un sistema de IA conservar información entre pasos, conversaciones o sesiones.",
    simpleExplanation:
      "Los LLMs no recuerdan nada por sí mismos entre una conversación y otra. La «memoria» de un asistente es algo que construye el sistema a su alrededor: guardar lo importante y volver a mostrárselo al modelo cuando haga falta.\n\nSe suele dividir en memoria de [[short-term-memory|corto plazo]] (la conversación actual) y de [[long-term-memory|largo plazo]] (datos persistentes).",
    technicalExplanation:
      "Implementaciones: historial en la [[context-window|ventana de contexto]], resúmenes progresivos, almacenamiento en [[vector-database|bases vectoriales]] con recuperación por similitud, bases estructuradas (perfiles, preferencias) y archivos de notas que el propio agente edita. El diseño debe decidir qué guardar, cuándo recuperar, cómo olvidar y cómo proteger la privacidad.",
    whyItMatters: "Sin memoria, cada interacción empieza de cero; con memoria, un asistente puede personalizarse y trabajar en tareas largas.",
    useCases: ["Asistentes personales", "Agentes de larga duración", "Tutores personalizados"],
    prerequisites: ["context-window", "ai-agent"],
    relatedTerms: ["short-term-memory", "long-term-memory", "context-window", "rag"],
    nextTerms: ["short-term-memory", "long-term-memory"],
    tags: ["recordar", "memoria", "personalización"],
    sources: [{ title: "Generative Agents: Interactive Simulacra of Human Behavior", authors: "Park et al.", year: 2023, url: "https://arxiv.org/abs/2304.03442", kind: "paper" }],
  },
  {
    slug: "short-term-memory",
    name: "Short-Term Memory",
    spanishName: "Memoria de corto plazo",
    aliases: ["Memoria de corto plazo", "Memoria de trabajo", "Working memory"],
    category: "agents",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "La información que un agente mantiene disponible durante una tarea o conversación, normalmente dentro de la ventana de contexto.",
    simpleExplanation:
      "Es lo que el agente tiene «en mente» ahora mismo: tu último mensaje, los pasos que ya dio y los resultados de sus herramientas. Desaparece cuando termina la sesión, salvo que se guarde en algún lugar.",
    technicalExplanation:
      "Se implementa como el historial de mensajes en el contexto. Cuando crece demasiado, se aplican estrategias como ventanas deslizantes, resumen de turnos antiguos o eliminación de resultados de herramientas ya usados (*context compaction*). Gestionarla bien reduce costo y evita que información irrelevante distraiga al modelo.",
    whyItMatters: "Determina qué tan coherente es un agente dentro de una misma tarea.",
    useCases: ["Chatbots", "Agentes de varios pasos"],
    prerequisites: ["memory", "context-window"],
    relatedTerms: ["long-term-memory", "memory", "context-window"],
    nextTerms: ["long-term-memory"],
    tags: ["memoria de trabajo", "historial"],
  },
  {
    slug: "long-term-memory",
    name: "Long-Term Memory",
    spanishName: "Memoria de largo plazo",
    aliases: ["Memoria de largo plazo", "Memoria persistente", "Persistent memory"],
    category: "agents",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "Información que un sistema de IA guarda fuera del modelo para recordarla en futuras sesiones.",
    simpleExplanation:
      "Si le dices a tu asistente que eres vegetariano, la memoria de largo plazo es lo que le permite recordarlo la próxima semana. Se guarda en una base de datos y se recupera cuando es relevante.",
    technicalExplanation:
      "Se almacena en bases vectoriales, bases relacionales o documentos, y se recupera por similitud semántica, por reglas o a petición del propio agente mediante herramientas de lectura y escritura. Retos: decidir qué merece recordarse, actualizar información contradictoria, evitar acumular errores y dar al usuario control para ver y borrar lo guardado.",
    whyItMatters: "Permite asistentes realmente personalizados y agentes que acumulan conocimiento del proyecto.",
    useCases: ["Asistentes personales", "Agentes de programación con notas del proyecto", "CRM con IA"],
    prerequisites: ["memory"],
    relatedTerms: ["short-term-memory", "memory", "vector-database", "rag"],
    nextTerms: ["multi-agent-system"],
    tags: ["persistente", "recordar", "personalización"],
  },
  {
    slug: "multi-agent-system",
    name: "Multi-Agent System",
    spanishName: "Sistema multiagente",
    aliases: ["Sistema multiagente", "Sistemas multiagente", "Multi-agent", "Multiagente"],
    category: "agents",
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Un sistema en el que varios agentes de IA, cada uno con un rol, colaboran o se coordinan para resolver una tarea.",
    simpleExplanation:
      "En lugar de un solo agente que lo hace todo, formas un equipo: un agente investiga, otro escribe, otro revisa. Cada uno tiene instrucciones y herramientas específicas, y un coordinador reparte el trabajo.",
    technicalExplanation:
      "Topologías: orquestador con subagentes (el más común), cadenas secuenciales, debates entre agentes y enjambres descentralizados. Ventajas: paralelismo, especialización y contextos más limpios por agente. Desventajas: mayor costo en tokens, errores de coordinación y dificultad de depuración. En muchos casos, un solo agente bien diseñado rinde igual con menos complejidad.",
    whyItMatters: "Permite abordar tareas grandes que exceden el contexto o la capacidad de un solo agente.",
    useCases: ["Investigación a gran escala", "Desarrollo de software", "Simulaciones"],
    prerequisites: ["ai-agent", "orchestration"],
    relatedTerms: ["orchestration", "ai-agent", "agentic-ai", "planning"],
    nextTerms: ["autonomous-agent"],
    tags: ["equipo", "multiagente", "colaboración"],
    sources: [{ title: "AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation", authors: "Wu et al.", year: 2023, url: "https://arxiv.org/abs/2308.08155", kind: "paper" }],
  },
  {
    slug: "orchestration",
    name: "Orchestration",
    spanishName: "Orquestación",
    aliases: ["Orquestación", "Orquestador", "Orchestrator"],
    category: "agents",
    secondaryCategories: ["ai-engineering"],
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "La coordinación de modelos, herramientas, datos y agentes para que trabajen juntos en un flujo coherente.",
    simpleExplanation:
      "Es la batuta del director de orquesta: decide quién entra, cuándo y con qué información. En una aplicación de IA, la capa de orquestación llama al modelo, ejecuta herramientas, maneja errores, guarda estado y decide qué sigue.",
    technicalExplanation:
      "Incluye gestión de estado, reintentos, límites de tiempo y costo, paralelismo, enrutamiento entre modelos (modelos pequeños para tareas simples, grandes para complejas) y registro para [[evaluation|evaluación]] y observabilidad. Puede estar en código propio o en frameworks especializados. En sistemas multiagente, un agente orquestador delega subtareas a otros.",
    whyItMatters: "Es donde se decide la fiabilidad, el costo y la latencia de un sistema de IA real.",
    useCases: ["Sistemas multiagente", "Pipelines de RAG", "Aplicaciones con varios modelos"],
    prerequisites: ["workflow"],
    relatedTerms: ["multi-agent-system", "agentic-workflow", "workflow", "ai-engineering"],
    nextTerms: ["multi-agent-system"],
    tags: ["coordinar", "orquestador"],
  },
  {
    slug: "human-in-the-loop",
    name: "Human-in-the-Loop",
    spanishName: "Humano en el ciclo",
    acronym: "HITL",
    aliases: ["Humano en el ciclo", "HITL", "Supervisión humana", "Aprobación humana"],
    category: "agents",
    secondaryCategories: ["safety"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Diseñar un sistema de IA para que una persona revise, apruebe o corrija sus decisiones en puntos clave.",
    simpleExplanation:
      "Un agente puede redactar el correo, pero tú decides si se envía. Human-in-the-loop significa poner a una persona en los momentos donde un error sería caro: pagos, envíos, borrados, decisiones médicas o legales.",
    technicalExplanation:
      "Se implementa con puntos de aprobación antes de acciones irreversibles, colas de revisión para casos de baja confianza, interfaces para corregir y retroalimentar, y límites de autonomía configurables. Las correcciones humanas también pueden alimentar [[evaluation|evaluaciones]] y datos de entrenamiento ([[preference-data]]).",
    whyItMatters: "Permite aprovechar la velocidad de la IA manteniendo control y responsabilidad humana.",
    useCases: ["Aprobación de acciones de agentes", "Moderación de contenido", "Revisión de documentos legales", "Etiquetado de datos"],
    prerequisites: ["ai-agent"],
    relatedTerms: ["ai-agent", "guardrails", "ai-safety", "autonomous-agent"],
    nextTerms: ["guardrails"],
    tags: ["supervisión", "aprobación", "control humano"],
  },
  {
    slug: "autonomous-agent",
    name: "Autonomous Agent",
    spanishName: "Agente autónomo",
    aliases: ["Agente autónomo", "Agentes autónomos"],
    category: "agents",
    difficulty: "advanced",
    type: "concept",
    frontier: true,
    shortDefinition: "Un agente que puede trabajar durante periodos largos y tomar muchas decisiones seguidas con poca o ninguna intervención humana.",
    simpleExplanation:
      "Es el extremo del espectro: le das un objetivo amplio y trabaja por su cuenta durante minutos u horas —investigando, programando, probando— hasta terminar. Cuanta más autonomía, más importante es que sea fiable y que existan límites claros.",
    technicalExplanation:
      "La autonomía se mide cada vez más por la duración y complejidad de las tareas que un agente completa con éxito sin ayuda. Requiere planificación robusta, recuperación de errores, gestión de contexto en tareas largas y controles de seguridad (sandboxes, permisos mínimos, presupuestos de costo, registro de acciones). Es un área de rápido avance y de preocupación activa en [[ai-safety]].",
    whyItMatters: "Define hasta dónde puede delegarse trabajo real a sistemas de IA.",
    useCases: ["Agentes de programación", "Investigación automatizada", "Operaciones de TI"],
    prerequisites: ["ai-agent", "planning"],
    relatedTerms: ["ai-agent", "agentic-ai", "human-in-the-loop", "ai-safety"],
    nextTerms: ["computer-use", "ai-safety"],
    tags: ["autonomía", "independiente"],
  },
  {
    slug: "computer-use",
    name: "Computer Use",
    spanishName: "Uso de computadora",
    aliases: ["Uso de computadora", "Computer-use agent", "Agentes de navegador", "Browser agent", "GUI agent"],
    category: "agents",
    secondaryCategories: ["frontier"],
    difficulty: "advanced",
    type: "technique",
    frontier: true,
    shortDefinition: "La capacidad de un modelo de operar una computadora como lo haría una persona: ver la pantalla, mover el cursor, hacer clic y escribir.",
    simpleExplanation:
      "Muchas tareas no tienen API: hay que entrar a un sitio web, llenar formularios y navegar menús. Con computer use, el modelo recibe capturas de pantalla, decide qué hacer («clic en el botón Guardar») y el sistema ejecuta esa acción. Repite hasta terminar.",
    technicalExplanation:
      "Combina un [[multimodal-model|modelo multimodal]] que interpreta capturas de pantalla (o el árbol de accesibilidad) con herramientas de acción: mover el mouse a coordenadas, hacer clic, teclear y desplazarse. Anthropic lanzó una versión pública en beta en octubre de 2024, y otros proveedores ofrecen capacidades similares. Retos: precisión en la interfaz, velocidad, y seguridad frente a [[prompt-injection]] en páginas web y acciones irreversibles; se recomienda ejecutarlo en entornos aislados y con [[human-in-the-loop|supervisión humana]].",
    whyItMatters: "Permite automatizar software que nunca fue diseñado para integrarse con IA.",
    useCases: ["Automatización de tareas web", "Pruebas de software", "Llenado de formularios", "Migración de datos entre sistemas"],
    prerequisites: ["ai-agent", "multimodal-model", "tool-calling"],
    relatedTerms: ["ai-agent", "multimodal-model", "tool-calling", "prompt-injection"],
    nextTerms: ["prompt-injection", "autonomous-agent"],
    tags: ["pantalla", "clics", "navegador", "automatización"],
    sources: [{ title: "Introducing computer use, a new Claude 3.5 Sonnet, and Claude 3.5 Haiku", authors: "Anthropic", year: 2024, url: "https://www.anthropic.com/news/3-5-models-and-computer-use", kind: "article" }],
  },
];
