import type { TermInput } from "@/types/glossary";

export const fineTuningTerms: TermInput[] = [
  {
    slug: "fine-tuning",
    name: "Fine-Tuning",
    spanishName: "Ajuste fino",
    aliases: ["Ajuste fino", "Finetuning", "Fine tuning", "Afinamiento", "Especializar un modelo"],
    category: "llm",
    secondaryCategories: ["machine-learning"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Continuar el entrenamiento de un modelo ya entrenado con datos específicos para especializarlo en una tarea, estilo o dominio.",
    simpleExplanation:
      "Un modelo preentrenado es como un recién egresado con buena educación general. El fine-tuning es su capacitación en el puesto: con relativamente pocos ejemplos aprende el vocabulario, el formato y la forma de trabajar de tu empresa.\n\nSe modifica el modelo mismo (sus [[weights|pesos]]), a diferencia del [[prompt-engineering|prompting]] o [[rag]], que solo cambian lo que el modelo ve.",
    inThirtySeconds: [
      "Partes de un modelo preentrenado.",
      "Reúnes ejemplos de la tarea (cientos a miles).",
      "Entrenas unas pocas épocas con learning rate baja.",
      "Evalúas contra el modelo original.",
      "Despliegas el modelo especializado.",
    ],
    comparison: {
      title: "Prompting vs. Fine-Tuning",
      columns: ["Prompting / RAG", "Fine-Tuning"],
      rows: [
        { aspect: "Cambia los pesos", a: "No", b: "Sí" },
        { aspect: "Datos necesarios", a: "Ninguno o pocos ejemplos", b: "Cientos a miles de ejemplos de calidad" },
        { aspect: "Velocidad de iteración", a: "Minutos", b: "Horas o días" },
        { aspect: "Mejor para", a: "Conocimiento y tareas generales", b: "Formato, estilo, tareas estrechas, modelos más pequeños y baratos" },
      ],
    },
    technicalExplanation:
      "Puede ser **completo** (se actualizan todos los parámetros) o **eficiente en parámetros** ([[peft|PEFT]], como [[lora|LoRA]]). En LLMs, las formas principales son [[supervised-fine-tuning|SFT]] con pares instrucción–respuesta y el ajuste por preferencias ([[rlhf]], [[dpo]]).\n\nRiesgos: **olvido catastrófico** (perder capacidades generales), [[overfitting]] con datasets pequeños y degradación de comportamientos de seguridad. Se recomienda probar primero con prompting y RAG, y usar fine-tuning cuando se necesita consistencia de formato, menor latencia o costo (un modelo pequeño ajustado puede igualar a uno grande en una tarea concreta).",
    commonMistakes: [
      "El fine-tuning no es la mejor forma de enseñarle a un modelo datos que cambian a menudo (precios, inventario, políticas). Para eso suele funcionar mejor [[rag]].",
    ],
    whyItMatters: "Es la forma de convertir un modelo genérico en uno especializado, más barato o con un comportamiento muy consistente.",
    useCases: ["Formatos de salida estrictos", "Tono de marca", "Clasificación especializada", "Modelos pequeños y eficientes", "Dominios técnicos"],
    prerequisites: ["training", "pretraining"],
    relatedTerms: ["supervised-fine-tuning", "lora", "peft", "rlhf", "rag", "distillation"],
    nextTerms: ["supervised-fine-tuning", "lora", "rlhf"],
    tags: ["ajuste", "especializar", "entrenar", "personalizar"],
  },
  {
    slug: "supervised-fine-tuning",
    name: "Supervised Fine-Tuning",
    spanishName: "Ajuste fino supervisado",
    acronym: "SFT",
    aliases: ["SFT", "Ajuste fino supervisado"],
    category: "llm",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Ajustar un modelo con ejemplos de entradas y las respuestas ideales que debería producir.",
    simpleExplanation:
      "Le muestras al modelo miles de ejemplos del tipo «ante esta pregunta, esta es una respuesta excelente». El modelo aprende a imitar esas respuestas. Es el primer paso para convertir un modelo preentrenado en un asistente.",
    technicalExplanation:
      "Es [[supervised-learning|aprendizaje supervisado]] estándar con pérdida de [[cross-entropy]] sobre los tokens de la respuesta (normalmente se enmascara la pérdida del prompt). La calidad y diversidad de las demostraciones importan más que la cantidad. En el pipeline típico de post-entrenamiento, SFT precede al ajuste por preferencias ([[rlhf]] o [[dpo]]).",
    whyItMatters: "Enseña al modelo el formato y el comportamiento básico de un asistente.",
    useCases: ["Crear asistentes a partir de modelos base", "Especializar modelos en tareas"],
    prerequisites: ["fine-tuning", "supervised-learning"],
    relatedTerms: ["instruction-tuning", "fine-tuning", "rlhf", "dpo"],
    nextTerms: ["rlhf", "dpo"],
    tags: ["sft", "demostraciones", "post-entrenamiento"],
  },
  {
    slug: "instruction-tuning",
    name: "Instruction Tuning",
    spanishName: "Ajuste por instrucciones",
    aliases: ["Ajuste por instrucciones", "Instruction-tuned", "Instruct model"],
    category: "llm",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Ajustar un modelo con muchas tareas descritas como instrucciones para que aprenda a seguir instrucciones en general.",
    simpleExplanation:
      "Un modelo base, si le escribes «Traduce al inglés: hola», podría continuar con otra instrucción en vez de traducir. Tras el instruction tuning, entiende que debe **obedecer** la instrucción. Los modelos «Instruct» o «Chat» pasaron por este proceso.",
    technicalExplanation:
      "Trabajos como FLAN (Wei et al., 2021) mostraron que entrenar con una gran variedad de tareas formuladas como instrucciones mejora el rendimiento [[zero-shot-learning|zero-shot]] en tareas nuevas. Es una forma de [[supervised-fine-tuning|SFT]]; en la práctica los términos se solapan.",
    whyItMatters: "Es lo que hace que los modelos sean útiles con instrucciones en lenguaje natural.",
    useCases: ["Modelos de chat", "Asistentes"],
    prerequisites: ["supervised-fine-tuning"],
    relatedTerms: ["supervised-fine-tuning", "rlhf", "zero-shot-learning"],
    nextTerms: ["rlhf"],
    tags: ["instruct", "seguir instrucciones", "flan"],
    sources: [{ title: "Finetuned Language Models Are Zero-Shot Learners", authors: "Wei et al.", year: 2021, url: "https://arxiv.org/abs/2109.01652", kind: "paper" }],
  },
  {
    slug: "peft",
    name: "Parameter-Efficient Fine-Tuning",
    spanishName: "Ajuste fino eficiente en parámetros",
    acronym: "PEFT",
    aliases: ["PEFT", "Adapters", "Adaptadores", "Fine-tuning eficiente"],
    category: "llm",
    secondaryCategories: ["ai-engineering"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Técnicas de fine-tuning que entrenan solo una pequeña fracción de parámetros adicionales en lugar de todo el modelo.",
    simpleExplanation:
      "Ajustar todos los parámetros de un modelo de miles de millones exige mucha memoria. PEFT congela el modelo original y entrena solo piezas pequeñas añadidas. Se obtiene casi la misma calidad con muchísimos menos recursos, y puedes tener varios «módulos» intercambiables sobre un mismo modelo.",
    technicalExplanation:
      "Familias: **adapters** (pequeñas capas insertadas entre capas existentes, Houlsby et al., 2019), **prefix/prompt tuning** (vectores entrenables añadidos a la entrada) y métodos de bajo rango como [[lora|LoRA]]. Reducen la memoria de gradientes y estados del optimizador, y los artefactos resultantes pesan megabytes en lugar de gigabytes.",
    whyItMatters: "Democratizó el fine-tuning de LLMs: ahora es posible en una sola GPU.",
    useCases: ["Fine-tuning con presupuesto limitado", "Múltiples especializaciones de un mismo modelo"],
    prerequisites: ["fine-tuning"],
    relatedTerms: ["lora", "qlora", "fine-tuning"],
    nextTerms: ["lora", "qlora"],
    tags: ["peft", "adapters", "eficiente"],
    sources: [{ title: "Parameter-Efficient Transfer Learning for NLP", authors: "Houlsby et al.", year: 2019, url: "https://arxiv.org/abs/1902.00751", kind: "paper" }],
  },
  {
    slug: "lora",
    name: "LoRA",
    spanishName: "Adaptación de bajo rango",
    acronym: "LoRA",
    aliases: ["Low-Rank Adaptation", "Adaptación de bajo rango", "LoRA adapter"],
    category: "llm",
    secondaryCategories: ["ai-engineering"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Una técnica de fine-tuning que congela los pesos originales y entrena pequeñas matrices adicionales de bajo rango que modifican su comportamiento.",
    simpleExplanation:
      "En vez de reescribir un libro entero para corregirlo, pegas notas adhesivas en algunas páginas. LoRA hace eso: deja el modelo intacto y añade «notas» pequeñas que ajustan su comportamiento. Esas notas ocupan una fracción mínima del tamaño del modelo.",
    technicalExplanation:
      "Hu et al. (2021) observaron que la actualización de pesos durante el fine-tuning tiene bajo «rango intrínseco». LoRA representa el cambio ΔW como el producto de dos matrices delgadas: W′ = W + BA, con B ∈ ℝᵈˣʳ, A ∈ ℝʳˣᵏ y r ≪ min(d, k). Solo A y B se entrenan. Tras el entrenamiento, BA puede fusionarse con W sin costo extra en inferencia, o mantenerse separado para intercambiar adaptadores.",
    math: {
      formula: "W′ = W + (α / r) · B · A",
      symbols: [
        { symbol: "W", meaning: "Matriz de pesos original (congelada)" },
        { symbol: "B, A", meaning: "Matrices pequeñas entrenables" },
        { symbol: "r", meaning: "Rango: típicamente entre 4 y 64" },
        { symbol: "α", meaning: "Factor de escala del ajuste" },
      ],
      explanation: "Con d = k = 4096 y r = 8, una matriz completa tiene ~16.8 millones de parámetros, mientras que A y B juntas tienen ~65 mil.",
    },
    whyItMatters: "Es la técnica de fine-tuning más usada en la práctica por su equilibrio entre calidad, costo y simplicidad.",
    useCases: ["Especializar LLMs abiertos", "Estilos en modelos de imagen", "Varios adaptadores por cliente"],
    prerequisites: ["peft", "matrix"],
    relatedTerms: ["qlora", "peft", "fine-tuning", "open-weights-model"],
    nextTerms: ["qlora", "quantization"],
    tags: ["lora", "bajo rango", "adaptadores"],
    sources: [{ title: "LoRA: Low-Rank Adaptation of Large Language Models", authors: "Hu et al.", year: 2021, url: "https://arxiv.org/abs/2106.09685", kind: "paper" }],
  },
  {
    slug: "qlora",
    name: "QLoRA",
    acronym: "QLoRA",
    aliases: ["Quantized LoRA", "LoRA cuantizado"],
    category: "llm",
    secondaryCategories: ["ai-engineering"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Una variante de LoRA que carga el modelo base cuantizado a 4 bits para poder hacer fine-tuning con mucha menos memoria.",
    simpleExplanation:
      "QLoRA combina dos ideas: comprimir el modelo original ([[quantization|cuantización]] a 4 bits) y entrenar solo adaptadores [[lora|LoRA]]. El resultado: puedes ajustar modelos grandes en una sola GPU que antes habría sido insuficiente.",
    technicalExplanation:
      "Dettmers et al. (2023) introdujeron el tipo de dato **NF4** (NormalFloat de 4 bits), la **doble cuantización** de las constantes de escala y **optimizadores paginados** para manejar picos de memoria. Los gradientes fluyen a través del modelo cuantizado congelado hacia los adaptadores LoRA en precisión mayor. Reportaron calidad comparable a fine-tuning en 16 bits en sus evaluaciones.",
    whyItMatters: "Hizo accesible el fine-tuning de modelos grandes a investigadores y equipos pequeños.",
    useCases: ["Fine-tuning en hardware de consumo", "Experimentación rápida"],
    prerequisites: ["lora", "quantization"],
    relatedTerms: ["lora", "quantization", "peft", "vram"],
    nextTerms: ["quantization"],
    tags: ["qlora", "4 bits", "nf4"],
    sources: [{ title: "QLoRA: Efficient Finetuning of Quantized LLMs", authors: "Dettmers et al.", year: 2023, url: "https://arxiv.org/abs/2305.14314", kind: "paper" }],
  },
  {
    slug: "rlhf",
    name: "RLHF",
    spanishName: "Aprendizaje por refuerzo con retroalimentación humana",
    acronym: "RLHF",
    aliases: ["Reinforcement Learning from Human Feedback", "Aprendizaje por refuerzo con retroalimentación humana", "Aprendizaje por refuerzo a partir de feedback humano"],
    category: "llm",
    secondaryCategories: ["reinforcement-learning", "safety"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Una técnica para ajustar un modelo usando preferencias humanas: personas comparan respuestas y el modelo aprende a producir las preferidas.",
    simpleExplanation:
      "Es difícil escribir una regla que defina «una buena respuesta». Pero es fácil para una persona comparar dos respuestas y decir cuál es mejor. RLHF aprovecha eso: se recolectan miles de comparaciones, se entrena un modelo que aprende a predecir qué prefieren las personas y luego se usa ese «juez» para mejorar al LLM.\n\nFue una pieza clave para que modelos como ChatGPT fueran útiles, amables y seguros.",
    diagram: {
      kind: "flow",
      title: "Las tres etapas clásicas de RLHF",
      steps: [
        { label: "1. SFT", detail: "Ajuste con demostraciones de respuestas ideales" },
        { label: "2. Datos de preferencia", detail: "Personas comparan pares de respuestas: A es mejor que B" },
        { label: "3. Reward model", detail: "Un modelo aprende a puntuar respuestas como lo harían las personas" },
        { label: "4. Optimización con RL", detail: "El LLM se ajusta (p. ej. con PPO) para maximizar esa puntuación" },
      ],
    },
    technicalExplanation:
      "Basado en Christiano et al. (2017) y aplicado a LLMs en InstructGPT (Ouyang et al., 2022). El [[reward-model|modelo de recompensa]] se entrena sobre [[preference-data|datos de preferencia]] con una pérdida de tipo Bradley-Terry. Después, la [[policy|política]] (el LLM) se optimiza con [[reinforcement-learning|RL]] —típicamente PPO— para maximizar la recompensa, con una penalización KL que evita alejarse demasiado del modelo SFT (y así limitar el *reward hacking*).\n\nAlternativas más simples como [[dpo|DPO]] optimizan directamente sobre las preferencias sin un modelo de recompensa explícito, y [[rlaif]] reemplaza parte de la retroalimentación humana por la de modelos.",
    commonMistakes: [
      "RLHF no le enseña al modelo hechos nuevos: principalmente moldea su comportamiento, tono y criterio para elegir entre respuestas que ya sabe producir.",
    ],
    whyItMatters: "Convirtió a los modelos de lenguaje en asistentes útiles y es una herramienta central de la alineación práctica.",
    useCases: ["Asistentes conversacionales", "Reducir respuestas dañinas", "Mejorar utilidad y tono"],
    prerequisites: ["supervised-fine-tuning", "reinforcement-learning", "reward-model"],
    relatedTerms: ["reward-model", "preference-data", "dpo", "rlaif", "alignment"],
    nextTerms: ["dpo", "rlaif", "constitutional-ai"],
    tags: ["preferencias humanas", "ppo", "alineación", "instructgpt"],
    sources: [
      { title: "Training language models to follow instructions with human feedback", authors: "Ouyang et al.", year: 2022, url: "https://arxiv.org/abs/2203.02155", kind: "paper" },
      { title: "Deep reinforcement learning from human preferences", authors: "Christiano et al.", year: 2017, url: "https://arxiv.org/abs/1706.03741", kind: "paper" },
    ],
  },
  {
    slug: "rlaif",
    name: "RLAIF",
    spanishName: "Aprendizaje por refuerzo con retroalimentación de IA",
    acronym: "RLAIF",
    aliases: ["Reinforcement Learning from AI Feedback", "Retroalimentación de IA"],
    category: "llm",
    secondaryCategories: ["reinforcement-learning", "safety"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Una variante de RLHF en la que las preferencias las genera un modelo de IA, guiado por principios o instrucciones, en lugar de personas.",
    simpleExplanation:
      "Recolectar millones de comparaciones humanas es caro y lento. En RLAIF, un modelo evalúa las respuestas siguiendo criterios definidos por personas. Las personas siguen definiendo qué es «bueno», pero la IA hace la mayor parte del trabajo de calificar.",
    technicalExplanation:
      "Se usa un LLM como etiquetador de preferencias, a menudo con una lista de principios (como en [[constitutional-ai|Constitutional AI]], Bai et al., 2022). Lee et al. (2023) reportaron resultados comparables a RLHF en algunas tareas. Riesgos: el modelo evaluador puede transmitir sus propios sesgos, y hace falta validación humana periódica.",
    whyItMatters: "Permite escalar la alineación a muchos más ejemplos con menor costo.",
    useCases: ["Entrenamiento de asistentes", "Reducción de respuestas dañinas"],
    prerequisites: ["rlhf"],
    relatedTerms: ["rlhf", "constitutional-ai", "llm-as-a-judge", "reward-model"],
    nextTerms: ["constitutional-ai"],
    tags: ["retroalimentación de ia", "ai feedback"],
    sources: [{ title: "RLAIF: Scaling Reinforcement Learning from Human Feedback with AI Feedback", authors: "Lee et al.", year: 2023, url: "https://arxiv.org/abs/2309.00267", kind: "paper" }],
  },
  {
    slug: "reward-model",
    name: "Reward Model",
    spanishName: "Modelo de recompensa",
    aliases: ["Modelo de recompensa", "RM", "Preference model"],
    category: "llm",
    secondaryCategories: ["reinforcement-learning", "frontier"],
    difficulty: "research",
    type: "model",
    shortDefinition: "Un modelo entrenado para asignar una puntuación a una respuesta que estima qué tan buena la considerarían las personas.",
    simpleExplanation:
      "Es el «juez» automático de RLHF. Aprende de miles de comparaciones humanas y después puede calificar millones de respuestas nuevas sin que una persona tenga que revisarlas todas.",
    technicalExplanation:
      "Suele ser un LLM con una cabeza escalar. Se entrena con pares (respuesta preferida, respuesta rechazada) maximizando σ(r(preferida) − r(rechazada)), el modelo de Bradley-Terry. Problemas: **reward hacking** (la política explota fallos del juez, por ejemplo, favoreciendo respuestas largas) y sobreoptimización. En razonamiento, se usan también recompensas verificables (tests de código, respuestas matemáticas) y **process reward models**, que evalúan cada paso del razonamiento.",
    whyItMatters: "Define qué optimiza el modelo durante el ajuste por preferencias; sus defectos se convierten en defectos del modelo.",
    useCases: ["RLHF", "Selección de respuestas (best-of-n)", "Evaluación automática"],
    prerequisites: ["preference-data", "reinforcement-learning"],
    relatedTerms: ["rlhf", "preference-data", "reward-function", "llm-as-a-judge"],
    nextTerms: ["rlhf", "dpo"],
    tags: ["recompensa", "juez", "reward hacking"],
  },
  {
    slug: "preference-data",
    name: "Preference Data",
    spanishName: "Datos de preferencia",
    aliases: ["Datos de preferencia", "Comparaciones", "Pairwise preferences"],
    category: "llm",
    difficulty: "advanced",
    type: "concept",
    shortDefinition: "Datos que indican cuál de dos o más respuestas es mejor, usados para ajustar modelos a lo que prefieren las personas.",
    simpleExplanation:
      "En lugar de escribir la respuesta perfecta, alguien ve dos respuestas y marca cuál prefiere, a veces explicando por qué. Miles de estas elecciones enseñan al modelo qué significa «mejor».",
    technicalExplanation:
      "Cada ejemplo es (prompt, respuesta_a, respuesta_b, preferencia). Puede incluir empates, escalas de intensidad o criterios separados (utilidad, veracidad, seguridad). La calidad depende de guías de anotación claras y del acuerdo entre anotadores. Se usa para entrenar [[reward-model|modelos de recompensa]] o directamente con [[dpo]].",
    whyItMatters: "Codifica los valores y criterios que el modelo terminará reflejando.",
    useCases: ["RLHF", "DPO", "Evaluación comparativa"],
    prerequisites: ["dataset", "label"],
    relatedTerms: ["reward-model", "rlhf", "dpo", "human-evaluation"],
    nextTerms: ["reward-model", "dpo"],
    tags: ["preferencias", "comparaciones", "anotación"],
  },
  {
    slug: "dpo",
    name: "Direct Preference Optimization",
    spanishName: "Optimización directa de preferencias",
    acronym: "DPO",
    aliases: ["DPO", "Optimización directa de preferencias"],
    category: "llm",
    secondaryCategories: ["safety"],
    difficulty: "research",
    type: "technique",
    shortDefinition: "Un método para ajustar un modelo con datos de preferencia directamente, sin entrenar un modelo de recompensa ni usar aprendizaje por refuerzo.",
    simpleExplanation:
      "RLHF tiene varias piezas móviles y es difícil de estabilizar. DPO llega a un objetivo similar con un truco matemático: ajusta el modelo para que aumente la probabilidad de la respuesta preferida y disminuya la de la rechazada, con una pérdida de entrenamiento sencilla.",
    technicalExplanation:
      "Rafailov et al. (2023) mostraron que, bajo el objetivo de RLHF con penalización KL, la política óptima tiene forma cerrada; reescribiendo la recompensa en función de la política se obtiene una pérdida de clasificación binaria sobre pares de preferencia, relativa a un modelo de referencia congelado. Es más simple y estable que PPO, y ha inspirado muchas variantes.",
    whyItMatters: "Simplificó el ajuste por preferencias y lo volvió accesible fuera de los grandes laboratorios.",
    useCases: ["Alineación de modelos abiertos", "Ajuste de estilo y utilidad"],
    prerequisites: ["rlhf", "preference-data"],
    relatedTerms: ["rlhf", "preference-data", "reward-model", "fine-tuning"],
    nextTerms: ["rlaif", "constitutional-ai"],
    tags: ["dpo", "preferencias", "sin rl"],
    sources: [{ title: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model", authors: "Rafailov et al.", year: 2023, url: "https://arxiv.org/abs/2305.18290", kind: "paper" }],
  },
  {
    slug: "distillation",
    name: "Knowledge Distillation",
    spanishName: "Destilación de conocimiento",
    aliases: ["Distillation", "Destilación", "Destilación de conocimiento", "Teacher-student", "Maestro-alumno", "Model distillation"],
    category: "ai-engineering",
    secondaryCategories: ["llm", "deep-learning"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Entrenar un modelo pequeño (alumno) para imitar el comportamiento de un modelo grande (maestro), conservando buena parte de su calidad.",
    simpleExplanation:
      "Un modelo enorme es potente pero caro y lento. La destilación entrena un modelo más pequeño usando las respuestas del grande como material de estudio. El alumno no llega a ser igual de bueno en todo, pero en las tareas que importan puede acercarse mucho, a una fracción del costo.",
    technicalExplanation:
      "Hinton, Vinyals y Dean (2015) propusieron entrenar al alumno con las **soft targets** del maestro: la distribución completa de probabilidades (suavizada con una temperatura), que contiene más información que la etiqueta correcta sola (por ejemplo, que un «3» se parece más a un «8» que a un «1»). En LLMs también se destila generando datasets con el modelo maestro ([[synthetic-data|datos sintéticos]]) y haciendo [[supervised-fine-tuning|SFT]] del alumno, incluso con razonamientos completos.",
    whyItMatters: "Es una de las razones por las que modelos pequeños y rápidos mejoran tan rápido.",
    useCases: ["Modelos para dispositivos móviles", "Reducir costos de inferencia", "Modelos especializados"],
    prerequisites: ["training", "softmax"],
    relatedTerms: ["model-compression", "synthetic-data", "quantization", "fine-tuning"],
    nextTerms: ["model-compression", "quantization"],
    tags: ["destilar", "maestro", "alumno", "modelo pequeño"],
    sources: [{ title: "Distilling the Knowledge in a Neural Network", authors: "Hinton, Vinyals & Dean", year: 2015, url: "https://arxiv.org/abs/1503.02531", kind: "paper" }],
  },
  {
    slug: "synthetic-data",
    name: "Synthetic Data",
    spanishName: "Datos sintéticos",
    aliases: ["Datos sintéticos", "Datos generados", "Datos artificiales"],
    category: "frontier",
    secondaryCategories: ["llm", "fundamentals"],
    difficulty: "research",
    type: "technique",
    frontier: true,
    shortDefinition: "Datos generados artificialmente —a menudo por otros modelos de IA— para entrenar o evaluar modelos.",
    simpleExplanation:
      "Cuando faltan datos reales (por privacidad, costo o escasez), se pueden generar: un modelo escribe miles de ejercicios de matemáticas con solución, o se simulan escenarios de manejo para un auto autónomo.\n\nBien usados, los datos sintéticos multiplican los datos disponibles. Mal usados, amplifican los errores del modelo que los generó.",
    technicalExplanation:
      "Métodos: generación con LLMs a partir de semillas y plantillas, auto-instrucción, reescritura de datos reales, simulación y generación con verificación automática (código que pasa pruebas, matemáticas comprobables). Trabajos como «Textbooks Are All You Need» (Gunasekar et al., 2023) mostraron que datos sintéticos de alta calidad pueden entrenar modelos pequeños competitivos. Riesgos: poca diversidad, errores sistemáticos y [[model-collapse]] si se entrena recursivamente sin datos reales.",
    whyItMatters: "Es una estrategia clave ante la escasez de datos de alta calidad para seguir entrenando modelos cada vez más capaces.",
    useCases: ["Entrenamiento de razonamiento", "Datos de instrucciones", "Privacidad en datos médicos", "Simulación para robótica"],
    prerequisites: ["dataset", "llm"],
    relatedTerms: ["model-collapse", "distillation", "data", "rlaif"],
    nextTerms: ["model-collapse", "scaling-laws"],
    tags: ["sintético", "generado", "simulación"],
    sources: [{ title: "Textbooks Are All You Need", authors: "Gunasekar et al.", year: 2023, url: "https://arxiv.org/abs/2306.11644", kind: "paper" }],
  },
];
