import type { TermInput } from "@/types/glossary";

export const frontierTerms: TermInput[] = [
  {
    slug: "world-models",
    name: "World Models",
    spanishName: "Modelos del mundo",
    aliases: ["Modelos del mundo", "World model", "Modelo del mundo"],
    category: "frontier",
    difficulty: "research",
    type: "concept",
    frontier: true,
    shortDefinition: "Modelos que aprenden una representación interna de cómo funciona un entorno y pueden predecir o simular qué pasará si se toman ciertas acciones.",
    simpleExplanation:
      "Antes de cruzar la calle, imaginas si el auto que viene alcanzará a frenar. Tienes un «modelo del mundo» en la cabeza que te permite simular el futuro. Los world models buscan dar a la IA esa capacidad: predecir consecuencias antes de actuar.\n\nSon clave para robots, vehículos autónomos y agentes que deben planificar en entornos físicos o complejos.",
    technicalExplanation:
      "Ha y Schmidhuber (2018) popularizaron el término: un modelo aprende una representación comprimida del entorno y su dinámica, y un agente puede entrenarse «soñando» dentro de ese simulador aprendido. Hoy abarca modelos generativos de video interactivos que simulan entornos, modelos de dinámica para robótica y la pregunta abierta de si los LLMs desarrollan representaciones internas del mundo. Retos: consistencia física a largo plazo, acumulación de errores y evaluación.",
    whyItMatters: "Muchos investigadores los consideran un paso clave hacia agentes capaces de planificar y actuar en el mundo real.",
    useCases: ["Robótica", "Vehículos autónomos", "Simulación para entrenar agentes", "Videojuegos generativos"],
    prerequisites: ["reinforcement-learning", "generative-ai"],
    relatedTerms: ["reinforcement-learning", "planning", "latent-space", "diffusion-model"],
    nextTerms: ["latent-reasoning"],
    tags: ["simulación", "predicción", "robótica"],
    sources: [{ title: "World Models", authors: "Ha & Schmidhuber", year: 2018, url: "https://arxiv.org/abs/1803.10122", kind: "paper" }],
  },
  {
    slug: "model-collapse",
    name: "Model Collapse",
    spanishName: "Colapso de modelos",
    aliases: ["Colapso de modelos", "Colapso del modelo"],
    category: "frontier",
    secondaryCategories: ["safety"],
    difficulty: "research",
    type: "concept",
    frontier: true,
    shortDefinition: "La degradación que sufren los modelos generativos cuando se entrenan repetidamente con datos generados por otros modelos, perdiendo diversidad y calidad.",
    simpleExplanation:
      "Es como fotocopiar una fotocopia una y otra vez: cada copia pierde un poco de detalle. Si internet se llena de texto generado por IA y los modelos futuros aprenden de ese texto, podrían ir perdiendo los matices y la diversidad del lenguaje humano real.",
    technicalExplanation:
      "Shumailov et al. (2023; publicado en Nature en 2024) mostraron que el entrenamiento recursivo con datos generados hace que las colas de la distribución original desaparezcan progresivamente: el modelo sobrerrepresenta lo más probable y olvida lo raro. Otros trabajos indican que el efecto se mitiga si los datos sintéticos se **acumulan** junto con datos reales en lugar de reemplazarlos. Es una consideración central al usar [[synthetic-data|datos sintéticos]].",
    whyItMatters: "Pone en valor los datos humanos originales y exige cuidado al entrenar con contenido generado por IA.",
    useCases: ["Diseño de pipelines de datos sintéticos", "Curación de corpus"],
    prerequisites: ["synthetic-data", "probability-distribution"],
    relatedTerms: ["synthetic-data", "data", "pretraining"],
    nextTerms: ["scaling-laws"],
    tags: ["colapso", "datos sintéticos", "degradación"],
    sources: [{ title: "The Curse of Recursion: Training on Generated Data Makes Models Forget", authors: "Shumailov et al.", year: 2023, url: "https://arxiv.org/abs/2305.17493", kind: "paper" }],
  },
  {
    slug: "emergent-capabilities",
    name: "Emergent Capabilities",
    spanishName: "Capacidades emergentes",
    aliases: ["Capacidades emergentes", "Emergent abilities", "Habilidades emergentes", "Emergencia"],
    category: "frontier",
    secondaryCategories: ["llm"],
    difficulty: "research",
    type: "concept",
    frontier: true,
    shortDefinition: "Capacidades que parecen aparecer de forma relativamente abrupta en modelos grandes y que no se observan en versiones más pequeñas.",
    simpleExplanation:
      "Con modelos pequeños, cierta habilidad —como resolver aritmética de varios pasos— no aparece. Al aumentar la escala, de pronto el modelo la domina. Nadie la programó explícitamente: «emergió» del entrenamiento a gran escala.\n\nSin embargo, existe un debate: parte de esa aparente brusquedad podría deberse a cómo se mide.",
    technicalExplanation:
      "Wei et al. (2022) documentaron capacidades con rendimiento cercano al azar por debajo de cierta escala y muy superior por encima. Schaeffer et al. (2023) argumentaron que muchas de estas discontinuidades desaparecen con métricas continuas (por ejemplo, probabilidad de la respuesta en lugar de acierto exacto), lo que sugiere mejoras graduales que parecen abruptas bajo métricas de todo o nada. El tema importa para predecir capacidades futuras y para la seguridad.",
    whyItMatters: "Afecta cuánto podemos anticipar lo que harán los próximos modelos antes de entrenarlos.",
    useCases: ["Predicción de capacidades", "Evaluaciones de seguridad"],
    prerequisites: ["scaling-laws", "llm"],
    relatedTerms: ["scaling-laws", "in-context-learning", "benchmark"],
    nextTerms: ["scaling-laws", "ai-safety"],
    tags: ["emergencia", "escala", "capacidades"],
    sources: [
      { title: "Emergent Abilities of Large Language Models", authors: "Wei et al.", year: 2022, url: "https://arxiv.org/abs/2206.07682", kind: "paper" },
      { title: "Are Emergent Abilities of Large Language Models a Mirage?", authors: "Schaeffer, Miranda & Koyejo", year: 2023, url: "https://arxiv.org/abs/2304.15004", kind: "paper" },
    ],
  },
  {
    slug: "latent-reasoning",
    name: "Latent Reasoning",
    spanishName: "Razonamiento latente",
    aliases: ["Razonamiento latente", "Razonamiento en espacio latente", "Continuous thought", "Pensamiento continuo"],
    category: "frontier",
    secondaryCategories: ["llm"],
    difficulty: "research",
    type: "technique",
    frontier: true,
    shortDefinition: "Enfoques en los que un modelo razona en sus representaciones internas (vectores) en lugar de, o además de, escribir su razonamiento como texto.",
    simpleExplanation:
      "Los modelos de razonamiento actuales «piensan en voz alta»: escriben su razonamiento palabra por palabra. Pero las palabras son un canal limitado. El razonamiento latente explora que el modelo piense directamente en su «idioma interno» de vectores, potencialmente de forma más eficiente.\n\nEl costo: ese pensamiento sería más difícil de leer y supervisar por humanos.",
    technicalExplanation:
      "Una línea de trabajo alimenta el estado oculto final del modelo de vuelta como entrada, sin decodificarlo a un token (por ejemplo, Coconut, Hao et al., 2024), lo que permite representar varias alternativas a la vez. Otras exploran arquitecturas con cómputo recurrente en profundidad. Es un área temprana: los beneficios frente al [[chain-of-thought]] explícito varían según la tarea, y plantea retos de [[interpretability|interpretabilidad]] y supervisión.",
    whyItMatters: "Podría hacer más eficiente el razonamiento de la IA, pero también menos transparente, un compromiso relevante para la seguridad.",
    useCases: ["Investigación de razonamiento", "Eficiencia de inferencia"],
    prerequisites: ["reasoning-model", "latent-space"],
    relatedTerms: ["reasoning-model", "chain-of-thought", "test-time-compute", "latent-space"],
    nextTerms: ["mechanistic-interpretability"],
    tags: ["razonamiento", "latente", "estado oculto"],
    sources: [{ title: "Training Large Language Models to Reason in a Continuous Latent Space", authors: "Hao et al.", year: 2024, url: "https://arxiv.org/abs/2412.06769", kind: "paper" }],
  },
];
