import type { TermInput } from "@/types/glossary";

export const fundamentalsTerms: TermInput[] = [
  {
    slug: "artificial-intelligence",
    name: "Inteligencia Artificial",
    acronym: "IA",
    aliases: ["Artificial Intelligence", "AI", "IA"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition:
      "El campo que construye sistemas capaces de realizar tareas que normalmente requieren inteligencia humana, como entender lenguaje, reconocer imágenes o tomar decisiones.",
    simpleExplanation:
      "La Inteligencia Artificial no es una sola tecnología: es un campo enorme con un objetivo común, lograr que las computadoras hagan cosas que antes solo podía hacer una persona.\n\nUn filtro de spam, el reconocimiento facial de tu teléfono, un traductor automático o un asistente como ChatGPT o Claude son ejemplos de IA. Hoy casi toda la IA útil se basa en [[machine-learning]]: en lugar de programar cada regla a mano, se deja que el sistema aprenda patrones a partir de [[data|datos]].",
    analogy:
      "Piensa en la IA como la medicina: es un campo completo, no un medicamento. Dentro hay especialidades —[[machine-learning]], [[deep-learning]], [[computer-vision]], [[nlp]]— igual que en la medicina hay cardiología o pediatría.",
    mentalModel: [
      { label: "IA", meaning: "El objetivo: máquinas que realizan tareas inteligentes." },
      { label: "Machine Learning", meaning: "El método dominante: aprender de ejemplos." },
      { label: "Deep Learning", meaning: "La técnica más potente de ML: redes neuronales profundas." },
      { label: "LLM", meaning: "Una aplicación de deep learning al lenguaje." },
    ],
    diagram: {
      kind: "flow",
      title: "De lo general a lo específico",
      steps: [
        { label: "Inteligencia Artificial", detail: "Cualquier sistema que realiza tareas «inteligentes»" },
        { label: "Machine Learning", detail: "Sistemas que aprenden de datos" },
        { label: "Deep Learning", detail: "Aprendizaje con redes neuronales profundas" },
        { label: "IA generativa y LLM", detail: "Modelos que generan texto, imágenes y código" },
      ],
    },
    technicalExplanation:
      "Históricamente, la IA incluyó dos grandes enfoques. La **IA simbólica** (sistemas expertos, lógica, búsqueda) codificaba el conocimiento en reglas explícitas. La **IA estadística** o [[machine-learning]] aprende funciones a partir de ejemplos.\n\nDesde aproximadamente 2012, el [[deep-learning]] domina el campo gracias a tres factores: más [[data|datos]], más [[compute|cómputo]] (especialmente [[gpu|GPUs]]) y mejores arquitecturas como el [[transformer]]. Es útil distinguir entre IA **estrecha** (resuelve tareas concretas) y la idea de IA **general** (AGI), un sistema capaz de igualar a los humanos en la mayoría de las tareas cognitivas, que sigue siendo un objetivo y un tema de debate.",
    commonMistakes: [
      "IA no es sinónimo de ChatGPT. Los asistentes conversacionales son una aplicación reciente de un campo que existe desde los años cincuenta.",
    ],
    whyItMatters:
      "Es el marco general que conecta todos los demás conceptos del glosario. Entender qué es (y qué no es) la IA ayuda a evaluar con criterio las promesas y los riesgos de cualquier producto que diga usarla.",
    useCases: ["Asistentes conversacionales", "Traducción automática", "Diagnóstico por imagen", "Recomendaciones de contenido", "Detección de fraude", "Vehículos autónomos"],
    relatedTerms: ["machine-learning", "deep-learning", "generative-ai", "llm", "algorithm"],
    nextTerms: ["machine-learning", "model", "data"],
    tags: ["ia", "inteligencia", "ai", "agi", "conceptos básicos"],
  },
  {
    slug: "machine-learning",
    name: "Machine Learning",
    spanishName: "Aprendizaje automático",
    acronym: "ML",
    aliases: ["Aprendizaje automático", "Aprendizaje de máquina", "ML"],
    category: "machine-learning",
    secondaryCategories: ["fundamentals"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition:
      "Una rama de la IA en la que las computadoras aprenden patrones a partir de datos en lugar de seguir reglas programadas a mano.",
    simpleExplanation:
      "En la programación tradicional, una persona escribe las reglas: «si el correo contiene X, márcalo como spam». En Machine Learning le das a la computadora miles de ejemplos —correos marcados como spam y como no spam— y ella descubre por sí misma qué patrones los distinguen.\n\nEl resultado de ese aprendizaje es un [[model|modelo]]: una función que, ante un ejemplo nuevo, produce una predicción.",
    analogy:
      "Es como aprender a reconocer aves. Nadie te da una lista de reglas exactas; ves muchas fotos con su nombre y, con el tiempo, tu cerebro aprende a distinguirlas. Después reconoces aves que nunca habías visto.",
    comparison: {
      title: "Programación tradicional vs. Machine Learning",
      columns: ["Programación tradicional", "Machine Learning"],
      rows: [
        { aspect: "Entrada", a: "Reglas + datos", b: "Datos + respuestas esperadas" },
        { aspect: "Salida", a: "Respuestas", b: "Un modelo (las «reglas» aprendidas)" },
        { aspect: "Quién define la lógica", a: "El programador", b: "El algoritmo de entrenamiento" },
        { aspect: "Funciona mejor cuando", a: "Las reglas son claras y estables", b: "Las reglas son difíciles de escribir (ver, leer, predecir)" },
      ],
    },
    technicalExplanation:
      "Formalmente, ML busca una función f que aproxime la relación entre entradas x y salidas y a partir de un [[dataset]]. El proceso de [[training|entrenamiento]] ajusta los [[parameters|parámetros]] de f para minimizar una [[loss-function|función de pérdida]] mediante un método de [[optimization|optimización]] como [[gradient-descent]].\n\nSe divide en paradigmas según el tipo de señal disponible: [[supervised-learning|supervisado]] (ejemplos etiquetados), [[unsupervised-learning|no supervisado]] (sin etiquetas), [[self-supervised-learning|autosupervisado]] (las etiquetas salen de los propios datos) y [[reinforcement-learning|por refuerzo]] (recompensas). El objetivo real no es memorizar los datos, sino [[generalization|generalizar]] a casos nuevos.",
    whyItMatters:
      "Es el motor de casi toda la IA actual. Cuando un producto «aprende», predice o recomienda, casi siempre hay un modelo de machine learning detrás.",
    useCases: ["Filtros de spam", "Recomendaciones", "Predicción de demanda", "Detección de fraude", "Diagnóstico médico asistido"],
    prerequisites: ["artificial-intelligence", "data"],
    relatedTerms: ["deep-learning", "model", "training", "dataset", "supervised-learning"],
    nextTerms: ["supervised-learning", "neural-network", "deep-learning"],
    tags: ["ml", "aprendizaje", "datos", "predicción"],
  },
  {
    slug: "deep-learning",
    name: "Deep Learning",
    spanishName: "Aprendizaje profundo",
    aliases: ["Aprendizaje profundo", "DL"],
    category: "deep-learning",
    secondaryCategories: ["fundamentals"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition:
      "Un tipo de machine learning que usa redes neuronales con muchas capas para aprender representaciones cada vez más abstractas de los datos.",
    simpleExplanation:
      "El Deep Learning usa [[neural-network|redes neuronales]] con muchas [[layer|capas]] apiladas. Cada capa transforma la información un poco: en una red que reconoce rostros, las primeras capas detectan bordes, las intermedias detectan ojos o narices y las últimas reconocen caras completas.\n\nLo «profundo» se refiere a esa cantidad de capas. Su gran ventaja es que aprende sola qué características son importantes, sin que una persona tenga que diseñarlas.",
    technicalExplanation:
      "Un modelo profundo compone muchas funciones parametrizadas: f(x) = f_L(…f_2(f_1(x))). Cada capa aplica una transformación lineal seguida de una [[activation-function|función de activación]] no lineal. Los parámetros se aprenden con [[backpropagation]] y [[gradient-descent]].\n\nSu éxito desde 2012 se explica por la disponibilidad de grandes [[dataset|datasets]], [[gpu|GPUs]] y mejoras como las [[residual-connection|conexiones residuales]], la [[layer-normalization|normalización]] y arquitecturas como [[cnn|CNNs]] y [[transformer|Transformers]]. Una de sus propiedades clave es el **aprendizaje de representaciones**: las capas internas construyen [[embeddings]] útiles para muchas tareas.",
    whyItMatters:
      "Todo lo que hoy llamamos IA avanzada —LLMs, generación de imágenes, reconocimiento de voz— es deep learning.",
    useCases: ["Reconocimiento de voz", "Visión por computadora", "Traducción", "Modelos de lenguaje", "Generación de imágenes"],
    prerequisites: ["machine-learning", "neural-network"],
    relatedTerms: ["neural-network", "layer", "backpropagation", "transformer", "cnn"],
    nextTerms: ["neural-network", "transformer", "embeddings"],
    tags: ["redes neuronales", "profundo", "dl"],
  },
  {
    slug: "algorithm",
    name: "Algoritmo",
    aliases: ["Algorithm"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Una secuencia finita de pasos bien definidos para resolver un problema o realizar una tarea.",
    simpleExplanation:
      "Una receta de cocina es un algoritmo: pasos concretos, en orden, que llevan de los ingredientes al platillo. En computación, un algoritmo le dice a la máquina exactamente qué hacer.\n\nEn IA conviene distinguir dos cosas: el **algoritmo de aprendizaje** (la receta para entrenar, como [[gradient-descent]]) y el [[model|modelo]] (el resultado entrenado que luego hace predicciones).",
    technicalExplanation:
      "Un algoritmo se caracteriza por su corrección y su complejidad (tiempo y memoria en función del tamaño de la entrada). En machine learning, los algoritmos de entrenamiento suelen ser iterativos y aproximados: no garantizan la solución óptima, sino una suficientemente buena. Por ejemplo, [[gradient-descent]] repite pequeños pasos de ajuste hasta que la [[loss-function|pérdida]] deja de mejorar.",
    whyItMatters:
      "Separar «algoritmo» de «modelo» evita una confusión muy común: el mismo algoritmo, con datos distintos, produce modelos completamente distintos.",
    useCases: ["Ordenar y buscar información", "Entrenar modelos", "Rutas de navegación", "Compresión de archivos"],
    relatedTerms: ["model", "machine-learning", "gradient-descent", "optimization"],
    nextTerms: ["model", "training"],
    tags: ["receta", "pasos", "programación"],
  },
  {
    slug: "model",
    name: "Modelo",
    aliases: ["Model", "Modelo de IA", "AI model", "Modelo de machine learning"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition:
      "El resultado de entrenar un algoritmo con datos: una función que recibe una entrada y produce una predicción o una respuesta.",
    simpleExplanation:
      "Un modelo es lo que queda después de que una IA aprende. Puedes imaginarlo como un archivo que contiene todo lo aprendido, guardado en forma de números llamados [[parameters|parámetros]].\n\nCuando usas ChatGPT, no hablas con «el entrenamiento»: hablas con el modelo ya entrenado, que convierte tu pregunta en una respuesta.",
    analogy:
      "Si el [[training|entrenamiento]] es estudiar para un examen, el modelo es tu cerebro ya preparado. El examen en sí sería la [[inference|inferencia]].",
    technicalExplanation:
      "Matemáticamente, un modelo es una función parametrizada f(x; θ), donde θ son los [[parameters|parámetros]] aprendidos. La **arquitectura** define la forma de la función (por ejemplo, un [[transformer]]); los **pesos** definen su comportamiento concreto.\n\nEn la práctica, un modelo se distribuye como archivos de [[weights|pesos]] más el código de la arquitectura. Su tamaño se mide en número de parámetros: desde miles en modelos clásicos hasta cientos de miles de millones en los [[llm|LLMs]] más grandes.",
    whyItMatters:
      "Es la pieza que se entrena, se evalúa, se despliega y se usa. Casi todas las decisiones de IA (costo, velocidad, calidad) dependen del modelo elegido.",
    useCases: ["Clasificar imágenes", "Predecir precios", "Generar texto", "Recomendar productos"],
    prerequisites: ["algorithm", "data"],
    relatedTerms: ["parameters", "weights", "training", "inference", "foundation-model"],
    nextTerms: ["training", "inference", "parameters"],
    tags: ["modelo", "función", "predicción"],
  },
  {
    slug: "data",
    name: "Datos",
    aliases: ["Data", "Dato"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La información —texto, imágenes, números, audio— de la que un modelo aprende y sobre la que hace predicciones.",
    simpleExplanation:
      "Los datos son la materia prima de la IA. Un modelo solo puede aprender lo que está presente en sus datos: si nunca vio fotos de gatos, no sabrá reconocer gatos.\n\nPor eso se dice «basura entra, basura sale»: datos incompletos, sesgados o erróneos producen modelos que fallan de formas parecidas.",
    technicalExplanation:
      "Los datos pueden ser **estructurados** (tablas con columnas definidas) o **no estructurados** (texto libre, imágenes, audio). Antes de entrenar se limpian, se deduplican y se transforman en representaciones numéricas: [[feature|features]], [[token|tokens]] o píxeles normalizados.\n\nLa calidad suele importar tanto como la cantidad. Problemas típicos: ruido en las [[label|etiquetas]], desbalance entre clases, datos duplicados, filtración entre entrenamiento y evaluación ([[data-contamination|contaminación]]) y [[algorithmic-bias|sesgos]] heredados de cómo se recolectaron.",
    whyItMatters:
      "En muchos proyectos reales, mejorar los datos rinde más que cambiar de modelo.",
    useCases: ["Entrenar modelos", "Evaluar modelos", "Alimentar sistemas RAG", "Analítica"],
    relatedTerms: ["dataset", "feature", "label", "synthetic-data", "algorithmic-bias"],
    nextTerms: ["dataset", "feature", "label"],
    tags: ["información", "materia prima", "calidad de datos"],
  },
  {
    slug: "dataset",
    name: "Dataset",
    spanishName: "Conjunto de datos",
    aliases: ["Conjunto de datos", "Data set", "Corpus"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Una colección organizada de ejemplos que se usa para entrenar, validar o evaluar un modelo.",
    simpleExplanation:
      "Un dataset es como el libro de ejercicios de un modelo. Puede ser una tabla con miles de casas y sus precios, un millón de fotos etiquetadas o billones de palabras de texto.\n\nNormalmente se divide en tres partes: una para **aprender** (entrenamiento), otra para **ajustar decisiones** (validación) y otra que el modelo nunca ve hasta el final, para **medir** qué tan bien funciona (prueba).",
    technicalExplanation:
      "La división train / validation / test existe para estimar la [[generalization|generalización]]: si evalúas con los mismos datos con los que entrenaste, medirás memoria, no aprendizaje. La validación se usa para elegir hiperparámetros (como la [[learning-rate]]) y detectar [[overfitting]].\n\nEn LLMs se habla de **corpus de preentrenamiento** (texto masivo de la web, libros, código) y de datasets más pequeños y curados para [[fine-tuning]] o [[preference-data|preferencias]].",
    whyItMatters: "El dataset define lo que el modelo puede aprender y cómo se medirá su éxito.",
    useCases: ["Entrenamiento", "Validación de hiperparámetros", "Benchmarks", "Fine-tuning"],
    prerequisites: ["data"],
    relatedTerms: ["data", "label", "benchmark", "training", "synthetic-data"],
    nextTerms: ["training", "supervised-learning"],
    tags: ["datos", "train", "test", "validación", "corpus"],
  },
  {
    slug: "training",
    name: "Training",
    spanishName: "Entrenamiento",
    aliases: ["Entrenamiento", "Entrenar un modelo", "Model training"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "El proceso en el que un modelo ajusta sus parámetros a partir de datos para mejorar en una tarea.",
    simpleExplanation:
      "Entrenar es enseñarle a un modelo. Se le muestran ejemplos, hace predicciones, se mide qué tan equivocado estuvo y se corrigen un poquito sus [[parameters|parámetros]]. Esto se repite millones de veces.\n\nAl principio el modelo responde casi al azar; al final ha ajustado sus números internos para cometer muy pocos errores.",
    inThirtySeconds: [
      "El modelo recibe un lote de ejemplos.",
      "Hace una predicción con sus parámetros actuales.",
      "Una función de pérdida mide el error.",
      "Backpropagation calcula cómo corregir cada parámetro.",
      "Los parámetros se ajustan un poco y se repite.",
    ],
    comparison: {
      title: "Training vs. Inference",
      columns: ["Training", "Inference"],
      rows: [
        { aspect: "Qué ocurre", a: "El modelo aprende", b: "El modelo usa lo aprendido" },
        { aspect: "Pesos", a: "Se modifican", b: "Normalmente no cambian" },
        { aspect: "Costo", a: "Muy costoso (semanas, miles de GPUs en LLMs)", b: "Mucho menor por consulta" },
        { aspect: "Cuándo", a: "Antes de publicar el modelo", b: "Cada vez que alguien lo usa" },
      ],
    },
    technicalExplanation:
      "El entrenamiento es un problema de [[optimization|optimización]]: encontrar parámetros θ que minimicen la [[loss-function|pérdida]] promedio sobre el [[dataset]]. El ciclo típico es: forward pass → cálculo de la pérdida → [[backpropagation]] para obtener el [[gradient|gradiente]] → actualización con [[gradient-descent]] (o variantes como Adam).\n\nLos datos se procesan en [[batch|batches]] durante varias [[epoch|épocas]]. En LLMs el entrenamiento se divide en fases: [[pretraining|preentrenamiento]] masivo y luego post-entrenamiento ([[supervised-fine-tuning|SFT]], [[rlhf]]).",
    whyItMatters:
      "Es la fase donde se decide lo que el modelo sabe y cómo se comporta, y la que concentra el mayor costo de cómputo.",
    useCases: ["Crear modelos desde cero", "Adaptar modelos (fine-tuning)", "Actualizar modelos con datos nuevos"],
    prerequisites: ["model", "dataset"],
    relatedTerms: ["inference", "loss-function", "gradient-descent", "epoch", "pretraining"],
    nextTerms: ["inference", "loss-function", "gradient-descent"],
    tags: ["entrenar", "aprender", "ajustar"],
  },
  {
    slug: "inference",
    name: "Inference",
    spanishName: "Inferencia",
    aliases: ["Inferencia", "Predicción", "Model inference"],
    category: "fundamentals",
    secondaryCategories: ["ai-engineering"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "El momento en que un modelo ya entrenado se usa para producir una respuesta a partir de una entrada nueva.",
    simpleExplanation:
      "Cada vez que le haces una pregunta a un chatbot, pides una traducción o tu teléfono reconoce tu cara, el modelo está haciendo inferencia: aplica lo que aprendió a un caso nuevo.\n\nDurante la inferencia el modelo normalmente **no aprende**: sus [[weights|pesos]] se quedan fijos.",
    technicalExplanation:
      "La inferencia es un forward pass: se evalúa f(x; θ) con parámetros fijos. En LLMs es autoregresiva: el modelo genera un [[token]] a la vez, y cada token nuevo se añade a la entrada para producir el siguiente. Dos fases la dominan: **prefill** (procesar el prompt completo en paralelo) y **decode** (generar token por token, limitado por el ancho de banda de memoria).\n\nMétricas clave: [[latency|latencia]], [[throughput]] y costo por token. Técnicas como [[kv-cache]], [[batching]], [[quantization]] y [[speculative-decoding]] la hacen más eficiente.",
    whyItMatters:
      "Es lo que pagan los usuarios y las empresas día a día. En un producto exitoso, el costo acumulado de inferencia puede superar al del entrenamiento.",
    useCases: ["Chatbots", "APIs de modelos", "Reconocimiento facial en el dispositivo", "Recomendaciones en tiempo real"],
    prerequisites: ["model", "training"],
    relatedTerms: ["training", "latency", "inference-optimization", "inference-server", "test-time-compute"],
    nextTerms: ["token", "inference-optimization", "latency"],
    tags: ["predicción", "usar modelo", "servir"],
  },
  {
    slug: "parameters",
    name: "Parámetros",
    aliases: ["Parameters", "Params", "Número de parámetros"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Los números internos de un modelo que se ajustan durante el entrenamiento y determinan su comportamiento.",
    simpleExplanation:
      "Imagina una mesa de mezclas de audio con millones de perillas. Cada perilla es un parámetro. Entrenar consiste en girar todas esas perillas hasta que el sonido —las respuestas del modelo— sea el correcto.\n\nCuando se dice que un modelo tiene «70B», significa 70 mil millones de parámetros.",
    technicalExplanation:
      "Los parámetros θ incluyen los [[weights|pesos]] y los [[bias|biases]] de cada capa. Son distintos de los **hiperparámetros** (como la [[learning-rate]] o el tamaño de [[batch]]), que se eligen antes de entrenar y no se aprenden.\n\nEl número de parámetros influye en la capacidad del modelo y en el costo: cada parámetro ocupa memoria (2 bytes en FP16/BF16, 0.5 bytes con [[quantization|cuantización]] a 4 bits). Un modelo de 70B en BF16 necesita unos 140 GB solo para los pesos. Más parámetros no garantiza mejor calidad: también importan los datos y el cómputo ([[scaling-laws]]).",
    whyItMatters: "Ayuda a estimar cuánta memoria, hardware y dinero hace falta para usar un modelo.",
    useCases: ["Comparar tamaños de modelos", "Estimar requisitos de VRAM", "Planear costos"],
    prerequisites: ["model"],
    relatedTerms: ["weights", "bias", "scaling-laws", "vram", "quantization"],
    nextTerms: ["weights", "training"],
    tags: ["pesos", "tamaño", "billones", "70b"],
  },
  {
    slug: "weights",
    name: "Weights",
    spanishName: "Pesos",
    aliases: ["Pesos", "Pesos del modelo", "Model weights"],
    category: "fundamentals",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Los parámetros que indican cuánta importancia da el modelo a cada conexión entre sus neuronas.",
    simpleExplanation:
      "En una [[neural-network|red neuronal]], cada conexión entre dos neuronas tiene un peso: un número que dice «esta señal importa mucho» o «esta casi no importa». Aprender es, en esencia, encontrar los pesos correctos.\n\nCuando una empresa «publica los pesos» de un modelo, está compartiendo todo lo que ese modelo aprendió.",
    technicalExplanation:
      "En una capa densa, la salida es y = σ(Wx + b), donde W es la [[matrix|matriz]] de pesos, b el vector de [[bias]] y σ una [[activation-function|función de activación]]. Los pesos se inicializan aleatoriamente y se actualizan con [[gradient-descent]] usando gradientes calculados por [[backpropagation]].\n\nLos modelos de [[open-weights-model|pesos abiertos]] permiten descargar estos archivos (por ejemplo, en formato safetensors) y ejecutarlos localmente.",
    whyItMatters: "Los pesos son el modelo: quien tiene los pesos puede ejecutarlo, ajustarlo y estudiarlo.",
    useCases: ["Distribuir modelos", "Fine-tuning", "Ejecución local"],
    prerequisites: ["parameters", "neural-network"],
    relatedTerms: ["parameters", "bias", "open-weights-model", "matrix"],
    nextTerms: ["bias", "backpropagation"],
    tags: ["pesos", "conexiones"],
  },
  {
    slug: "bias",
    name: "Bias (parámetro)",
    spanishName: "Sesgo como parámetro de una neurona",
    aliases: ["Bias term", "Término de sesgo", "Intercepto"],
    category: "fundamentals",
    secondaryCategories: ["deep-learning"],
    difficulty: "beginner",
    type: "mathematics",
    shortDefinition: "Un parámetro que se suma a la salida de una neurona y le permite desplazar su respuesta, independientemente de la entrada.",
    simpleExplanation:
      "Si los [[weights|pesos]] deciden cuánto importa cada entrada, el bias es un ajuste fijo que mueve el resultado hacia arriba o hacia abajo. Es como la ordenada al origen de una recta: sin ella, todas las rectas tendrían que pasar por cero.\n\nOjo: este «bias» técnico no tiene nada que ver con el [[algorithmic-bias|sesgo algorítmico]], que se refiere a comportamientos injustos de un modelo.",
    technicalExplanation:
      "En y = w·x + b, el término b permite que la función de decisión no esté obligada a pasar por el origen. En una capa, b es un vector con un valor por neurona. Algunas arquitecturas modernas de LLM omiten los términos de bias en ciertas capas porque la [[layer-normalization|normalización]] cumple parte de esa función.",
    whyItMatters: "Evita confundir dos significados muy distintos de la misma palabra.",
    useCases: ["Capas densas", "Regresión lineal", "Neuronas artificiales"],
    prerequisites: ["weights"],
    relatedTerms: ["weights", "artificial-neuron", "parameters", "algorithmic-bias"],
    nextTerms: ["artificial-neuron", "activation-function"],
    tags: ["intercepto", "neurona"],
  },
  {
    slug: "feature",
    name: "Feature",
    spanishName: "Característica",
    aliases: ["Característica", "Atributo", "Variable de entrada"],
    category: "machine-learning",
    secondaryCategories: ["fundamentals"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Una propiedad medible de un ejemplo que el modelo usa como entrada para hacer una predicción.",
    simpleExplanation:
      "Si quieres predecir el precio de una casa, las features serían los metros cuadrados, el número de recámaras, la colonia o la antigüedad. Cada una es una pista que el modelo puede usar.\n\nEn modelos clásicos, elegir buenas features (**feature engineering**) era gran parte del trabajo. El [[deep-learning]] aprende sus propias features automáticamente.",
    technicalExplanation:
      "Un ejemplo se representa como un [[vector]] x = (x₁, …, xₙ) donde cada xᵢ es una feature. Las features categóricas se codifican (one-hot, [[embeddings]]) y las numéricas suelen normalizarse. En [[mechanistic-interpretability|interpretabilidad]], «feature» también designa una dirección en el espacio de activaciones que representa un concepto aprendido por el modelo.",
    whyItMatters: "Las features determinan qué información tiene disponible el modelo para decidir.",
    useCases: ["Modelos tabulares", "Scoring de crédito", "Predicción de churn"],
    prerequisites: ["data"],
    relatedTerms: ["label", "vector", "embeddings", "dataset"],
    nextTerms: ["label", "supervised-learning"],
    tags: ["variable", "atributo", "entrada"],
  },
  {
    slug: "label",
    name: "Label",
    spanishName: "Etiqueta",
    aliases: ["Etiqueta", "Target", "Ground truth"],
    category: "machine-learning",
    secondaryCategories: ["fundamentals"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La respuesta correcta asociada a un ejemplo de entrenamiento, que el modelo aprende a predecir.",
    simpleExplanation:
      "En una foto de un perro, la etiqueta es «perro». En un correo, la etiqueta puede ser «spam» o «no spam». Las etiquetas son las respuestas del libro de ejercicios.\n\nMuchas etiquetas las ponen personas a mano, lo que es caro y lento. Por eso técnicas como el [[self-supervised-learning|aprendizaje autosupervisado]] son tan valiosas.",
    technicalExplanation:
      "En [[supervised-learning|aprendizaje supervisado]], cada ejemplo es un par (x, y) donde y es la etiqueta. Puede ser una clase (clasificación) o un número (regresión). La calidad de las etiquetas limita la calidad del modelo: el ruido de etiquetado introduce errores sistemáticos difíciles de detectar.",
    whyItMatters: "Sin etiquetas confiables, no se puede entrenar ni evaluar bien un modelo supervisado.",
    useCases: ["Clasificación", "Regresión", "Evaluación"],
    prerequisites: ["data"],
    relatedTerms: ["feature", "supervised-learning", "dataset", "human-evaluation"],
    nextTerms: ["supervised-learning"],
    tags: ["etiqueta", "respuesta", "anotación"],
  },
  {
    slug: "supervised-learning",
    name: "Supervised Learning",
    spanishName: "Aprendizaje supervisado",
    aliases: ["Aprendizaje supervisado"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "technique",
    shortDefinition: "Aprender a partir de ejemplos que incluyen la respuesta correcta, para luego predecirla en casos nuevos.",
    simpleExplanation:
      "Es aprender con un maestro que te da las respuestas. Le muestras al modelo miles de fotos etiquetadas como «gato» o «perro», y aprende a distinguirlos. Luego puede clasificar fotos que nunca vio.\n\nSe usa para dos tipos de problemas: **clasificación** (elegir una categoría) y **regresión** (predecir un número).",
    technicalExplanation:
      "Dado un dataset {(xᵢ, yᵢ)}, se busca una función f que minimice una [[loss-function|pérdida]] L(f(x), y). Para clasificación suele usarse [[cross-entropy]]; para regresión, error cuadrático medio. El [[supervised-fine-tuning]] de LLMs es aprendizaje supervisado sobre pares instrucción–respuesta.",
    whyItMatters: "Es el paradigma más usado en aplicaciones empresariales porque es directo de medir y controlar.",
    useCases: ["Detección de spam", "Diagnóstico por imagen", "Predicción de precios", "Análisis de sentimiento"],
    prerequisites: ["machine-learning", "label"],
    relatedTerms: ["unsupervised-learning", "self-supervised-learning", "label", "image-classification"],
    nextTerms: ["unsupervised-learning", "loss-function"],
    tags: ["clasificación", "regresión", "etiquetas"],
  },
  {
    slug: "unsupervised-learning",
    name: "Unsupervised Learning",
    spanishName: "Aprendizaje no supervisado",
    aliases: ["Aprendizaje no supervisado", "Clustering"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "technique",
    shortDefinition: "Aprender patrones y estructuras en datos que no tienen etiquetas.",
    simpleExplanation:
      "Aquí no hay respuestas correctas. Le das al modelo un montón de datos y le pides que encuentre orden por sí mismo: grupos de clientes parecidos, temas comunes en documentos o transacciones raras.\n\nEs como vaciar una caja de piezas de LEGO y separarlas por forma y color sin que nadie te diga qué categorías usar.",
    technicalExplanation:
      "Las tareas típicas son **clustering** (k-means, agrupamiento jerárquico), **reducción de dimensionalidad** (PCA, t-SNE, UMAP) y **detección de anomalías**. También incluye el modelado de la [[probability-distribution|distribución]] de los datos, idea que conecta con los modelos generativos.",
    whyItMatters: "La mayoría de los datos del mundo no tienen etiquetas; este enfoque permite aprovecharlos.",
    useCases: ["Segmentación de clientes", "Detección de fraude", "Exploración de datos", "Agrupar documentos"],
    prerequisites: ["machine-learning"],
    relatedTerms: ["supervised-learning", "self-supervised-learning", "embedding-space"],
    nextTerms: ["self-supervised-learning", "semi-supervised-learning"],
    tags: ["clustering", "agrupamiento", "sin etiquetas"],
  },
  {
    slug: "semi-supervised-learning",
    name: "Semi-Supervised Learning",
    spanishName: "Aprendizaje semisupervisado",
    aliases: ["Aprendizaje semisupervisado", "Semi supervisado"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "technique",
    shortDefinition: "Combinar pocos ejemplos etiquetados con muchos sin etiquetar para entrenar un modelo.",
    simpleExplanation:
      "Etiquetar datos es caro. Si tienes 1,000 radiografías revisadas por médicos y 100,000 sin revisar, el aprendizaje semisupervisado usa ambas: las etiquetadas enseñan la tarea y las no etiquetadas ayudan a entender la estructura general de los datos.",
    technicalExplanation:
      "Técnicas comunes: **pseudo-labeling** (el modelo etiqueta datos y se reentrena con sus predicciones más confiables), **consistency regularization** (predicciones estables ante pequeñas perturbaciones) y métodos basados en grafos. Se apoya en supuestos como que puntos cercanos en el espacio de datos comparten etiqueta.",
    whyItMatters: "Reduce drásticamente el costo de etiquetado en dominios especializados.",
    useCases: ["Imágenes médicas", "Clasificación de documentos", "Reconocimiento de voz"],
    prerequisites: ["supervised-learning", "unsupervised-learning"],
    relatedTerms: ["supervised-learning", "unsupervised-learning", "self-supervised-learning", "label"],
    nextTerms: ["self-supervised-learning"],
    tags: ["pocas etiquetas", "pseudo-labeling"],
  },
  {
    slug: "self-supervised-learning",
    name: "Self-Supervised Learning",
    spanishName: "Aprendizaje autosupervisado",
    aliases: ["Aprendizaje autosupervisado", "SSL"],
    category: "machine-learning",
    secondaryCategories: ["deep-learning"],
    difficulty: "beginner",
    type: "technique",
    shortDefinition: "Aprender de datos sin etiquetas creando la tarea a partir de los propios datos, por ejemplo, adivinar la siguiente palabra.",
    simpleExplanation:
      "Es el truco que hizo posibles a los [[llm|LLMs]]. En lugar de pagar a personas para etiquetar, se toma un texto, se oculta una parte y se le pide al modelo que la adivine. La respuesta correcta ya está en el texto.\n\nCon miles de millones de frases, el modelo aprende gramática, hechos y hasta razonamiento, sin que nadie etiquete nada.",
    technicalExplanation:
      "Las etiquetas se derivan automáticamente de la estructura de los datos. Ejemplos: [[next-token-prediction|predicción del siguiente token]] (GPT), enmascaramiento de palabras (BERT), aprendizaje contrastivo de imágenes y texto (CLIP) o reconstrucción de parches de imágenes. Técnicamente se optimiza como aprendizaje supervisado, pero sin anotación humana, lo que permite escalar a datasets gigantes.",
    whyItMatters: "Es la base del [[pretraining|preentrenamiento]] de los modelos fundacionales.",
    useCases: ["Preentrenamiento de LLMs", "Modelos de visión", "Modelos de audio", "Embeddings"],
    prerequisites: ["supervised-learning", "unsupervised-learning"],
    relatedTerms: ["pretraining", "next-token-prediction", "foundation-model", "llm"],
    nextTerms: ["pretraining", "next-token-prediction"],
    tags: ["preentrenamiento", "sin etiquetas", "predicción"],
  },
  {
    slug: "reinforcement-learning",
    name: "Reinforcement Learning",
    spanishName: "Aprendizaje por refuerzo",
    acronym: "RL",
    aliases: ["Aprendizaje por refuerzo", "RL"],
    category: "reinforcement-learning",
    secondaryCategories: ["machine-learning", "fundamentals"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Un paradigma en el que un agente aprende a tomar decisiones probando acciones y recibiendo recompensas o penalizaciones.",
    simpleExplanation:
      "Es como entrenar a un perro con premios. Nadie le explica paso a paso qué hacer: prueba cosas, y cuando algo sale bien recibe una recompensa. Con el tiempo aprende qué acciones conviene repetir.\n\nAsí aprendió AlphaGo a jugar Go mejor que cualquier humano, y así se refinan hoy muchos [[llm|LLMs]] y [[reasoning-model|modelos de razonamiento]].",
    diagram: {
      kind: "flow",
      title: "El ciclo del aprendizaje por refuerzo",
      steps: [
        { label: "Estado", detail: "El agente observa la situación" },
        { label: "Acción", detail: "Elige qué hacer según su política" },
        { label: "Entorno", detail: "El mundo responde" },
        { label: "Recompensa", detail: "Una señal indica qué tan bien salió" },
        { label: "Actualización", detail: "La política mejora y el ciclo se repite" },
      ],
    },
    technicalExplanation:
      "Se formaliza como un proceso de decisión de Markov: estados s, acciones a, transiciones P(s′|s,a) y recompensas r. El agente aprende una [[policy|política]] π(a|s) que maximiza la recompensa acumulada esperada, normalmente con descuento γ.\n\nFamilias de métodos: basados en valor ([[q-learning]]), basados en política (policy gradient, PPO) y actor-crítico. Un reto central es el balance entre [[exploration-exploitation|exploración y explotación]]. En LLMs, RL se usa en [[rlhf]] y para entrenar razonamiento con recompensas verificables (por ejemplo, si un problema de matemáticas se resolvió correctamente).",
    whyItMatters:
      "Permite aprender comportamientos secuenciales donde no existe una respuesta correcta por paso, solo un resultado final bueno o malo.",
    useCases: ["Juegos (Go, ajedrez)", "Robótica", "Alineación de LLMs", "Modelos de razonamiento", "Sistemas de recomendación"],
    prerequisites: ["machine-learning"],
    relatedTerms: ["policy", "reward-function", "rlhf", "q-learning", "reward-model"],
    nextTerms: ["policy", "rlhf", "reasoning-model"],
    tags: ["recompensa", "agente", "rl", "alphago"],
    sources: [
      { title: "Reinforcement Learning: An Introduction (2.ª ed.)", authors: "Sutton & Barto", year: 2018, url: "http://incompleteideas.net/book/the-book-2nd.html", kind: "book" },
    ],
  },
];
