import type { TermInput } from "@/types/glossary";

export const generativeTerms: TermInput[] = [
  {
    slug: "generative-ai",
    name: "Generative AI",
    spanishName: "IA generativa",
    aliases: ["IA generativa", "GenAI", "Inteligencia artificial generativa"],
    category: "generative-ai",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "IA capaz de crear contenido nuevo —texto, imágenes, código, audio o video— a partir de lo que aprendió de grandes cantidades de datos.",
    simpleExplanation:
      "La mayoría de la IA tradicional **clasifica** o **predice**: dice si un correo es spam o cuánto costará una casa. La IA generativa **crea**: escribe un correo, dibuja una ilustración o programa una función.\n\nNo copia y pega de su entrenamiento: aprende los patrones de cómo se ve un texto o una imagen y produce ejemplos nuevos que siguen esos patrones.",
    technicalExplanation:
      "Los modelos generativos aprenden (explícita o implícitamente) la [[probability-distribution|distribución de probabilidad]] de los datos, p(x), o una distribución condicional p(x | contexto), y generan muestras de ella. Familias principales: modelos autoregresivos como los [[llm|LLMs]] (predicen el siguiente [[token]]), [[diffusion-model|modelos de difusión]] (eliminan ruido progresivamente), [[gan|GANs]] y autoencoders variacionales.\n\nLa generación es probabilística: parámetros como la [[temperature|temperatura]] controlan cuánta variación hay entre respuestas.",
    commonMistakes: [
      "Que el contenido sea fluido no significa que sea correcto. Los modelos generativos pueden producir errores con total seguridad ([[hallucination|alucinaciones]]).",
    ],
    whyItMatters: "Cambió la relación entre personas y computadoras: ahora puedes pedir resultados en lenguaje natural en lugar de programarlos.",
    useCases: ["Asistentes conversacionales", "Generación de código", "Diseño e ilustración", "Resúmenes", "Doblaje y voz sintética"],
    prerequisites: ["deep-learning"],
    relatedTerms: ["llm", "diffusion-model", "foundation-model", "image-generation", "multimodal-model"],
    nextTerms: ["llm", "foundation-model", "diffusion-model"],
    tags: ["genai", "crear contenido", "chatgpt", "generar"],
  },
  {
    slug: "foundation-model",
    name: "Foundation Model",
    spanishName: "Modelo fundacional",
    aliases: ["Modelo fundacional", "Modelo base", "Base model"],
    category: "generative-ai",
    secondaryCategories: ["llm"],
    difficulty: "intermediate",
    type: "model",
    shortDefinition: "Un modelo grande entrenado con datos amplios y diversos que sirve como base para muchas tareas distintas.",
    simpleExplanation:
      "Antes, cada tarea necesitaba su propio modelo: uno para traducir, otro para resumir, otro para clasificar. Un modelo fundacional se entrena una sola vez con enormes cantidades de datos y después se adapta a cientos de tareas.\n\nEs como una persona con una educación general muy amplia que luego se especializa en poco tiempo.",
    technicalExplanation:
      "El término fue popularizado por el Stanford CRFM en 2021. Estos modelos se entrenan con [[self-supervised-learning|aprendizaje autosupervisado]] a gran escala ([[pretraining]]) y se adaptan mediante [[prompt-engineering|prompting]], [[fine-tuning]] o [[rag]]. Ejemplos: los LLMs de las familias GPT, Claude, Gemini o Llama, y modelos de visión como CLIP. Su homogeneización es una ventaja (una base para todo) y un riesgo (los defectos se heredan en todas las aplicaciones).",
    whyItMatters: "Casi todos los productos de IA actuales se construyen sobre unos pocos modelos fundacionales.",
    useCases: ["Base para chatbots", "Adaptación a dominios específicos", "Plataformas de IA empresarial"],
    prerequisites: ["model", "pretraining"],
    relatedTerms: ["llm", "pretraining", "fine-tuning", "open-weights-model"],
    nextTerms: ["llm", "fine-tuning"],
    tags: ["modelo base", "gpt", "claude", "gemini", "llama"],
    sources: [
      { title: "On the Opportunities and Risks of Foundation Models", authors: "Bommasani et al.", year: 2021, url: "https://arxiv.org/abs/2108.07258", kind: "paper" },
    ],
  },
  {
    slug: "llm",
    name: "Large Language Model",
    spanishName: "Modelo de lenguaje grande",
    acronym: "LLM",
    aliases: ["LLM", "LLMs", "Modelo de lenguaje grande", "Gran modelo de lenguaje", "Modelo de lenguaje", "Language model"],
    category: "llm",
    secondaryCategories: ["generative-ai", "nlp"],
    difficulty: "intermediate",
    type: "model",
    shortDefinition: "Un modelo de IA entrenado con enormes cantidades de texto para predecir la siguiente palabra, lo que le permite conversar, escribir, resumir y razonar.",
    simpleExplanation:
      "Un LLM es el cerebro detrás de asistentes como ChatGPT, Claude o Gemini. Aprendió leyendo una cantidad gigantesca de texto —libros, sitios web, código— con una tarea aparentemente simple: adivinar qué palabra sigue.\n\nPara hacerlo bien a esa escala, el modelo tuvo que aprender gramática, hechos del mundo, estilos de escritura e incluso formas de razonar. Después se le entrena adicionalmente para seguir instrucciones y ser útil en conversaciones.",
    analogy:
      "Imagina el autocompletado de tu teléfono, pero entrenado con una biblioteca enorme y con miles de millones de parámetros. La idea básica es la misma; la escala cambia todo.",
    inThirtySeconds: [
      "Tu texto se divide en tokens.",
      "Cada token se convierte en un embedding.",
      "Un Transformer procesa todos los tokens y sus relaciones.",
      "El modelo calcula probabilidades para el siguiente token.",
      "Elige uno, lo añade al texto y repite hasta terminar.",
    ],
    diagram: {
      kind: "flow",
      title: "Cómo genera texto un LLM",
      steps: [
        { label: "Prompt", chips: ["¿Qué", "es", "un", "LLM", "?"] },
        { label: "Tokenización y embeddings", detail: "El texto se convierte en vectores" },
        { label: "Transformer", detail: "Decenas de capas de attention y feedforward" },
        { label: "Probabilidades del siguiente token", chips: ["Un 62%", "Es 21%", "El 9%"] },
        { label: "Sampling", detail: "Se elige un token y se repite el ciclo" },
      ],
    },
    mentalModel: [
      { label: "LLM", meaning: "Un motor de lenguaje: predice texto plausible." },
      { label: "Prompt", meaning: "El volante: dirige qué produce." },
      { label: "Context window", meaning: "Su memoria de trabajo." },
      { label: "RAG / herramientas", meaning: "Acceso al mundo exterior." },
    ],
    technicalExplanation:
      "La mayoría de los LLMs actuales son [[transformer|Transformers]] de tipo [[decoder]] entrenados con [[next-token-prediction|predicción del siguiente token]] sobre billones de tokens. El entrenamiento tiene dos grandes fases: [[pretraining|preentrenamiento]] (aprender el lenguaje y el conocimiento general) y post-entrenamiento ([[supervised-fine-tuning|SFT]], [[rlhf]] u otras técnicas de preferencias) para convertirlo en un asistente útil y seguro.\n\nEn [[inference|inferencia]], genera de forma autoregresiva: calcula una distribución sobre el vocabulario con [[softmax]], elige un token mediante [[sampling]] y repite. Sus capacidades dependen de la escala ([[scaling-laws]]), de la calidad de los datos y del post-entrenamiento. Sus límites incluyen la [[context-window|ventana de contexto]], las [[hallucination|alucinaciones]] y un conocimiento congelado en la fecha de corte de sus datos.",
    commonMistakes: [
      "Un LLM no busca en internet por sí solo. Si responde con información actual, es porque el sistema a su alrededor le dio esa información (por ejemplo, con [[rag]] o [[tool-calling|herramientas]]).",
      "Un LLM no «recuerda» tus conversaciones anteriores a menos que el producto las vuelva a incluir en el contexto o use un sistema de [[memory|memoria]].",
    ],
    whyItMatters: "Los LLMs son la tecnología central de la ola actual de IA: asistentes, agentes, programación asistida y buscadores conversacionales dependen de ellos.",
    useCases: ["Asistentes conversacionales", "Programación asistida", "Resumen de documentos", "Traducción", "Agentes de IA", "Extracción de información"],
    prerequisites: ["token", "embeddings", "transformer"],
    relatedTerms: ["transformer", "token", "context-window", "pretraining", "hallucination", "reasoning-model"],
    nextTerms: ["fine-tuning", "rag", "ai-agent"],
    tags: ["chatgpt", "claude", "gemini", "gpt", "modelo de lenguaje", "chatbot"],
    sources: [
      { title: "Language Models are Few-Shot Learners (GPT-3)", authors: "Brown et al.", year: 2020, url: "https://arxiv.org/abs/2005.14165", kind: "paper" },
    ],
  },
  {
    slug: "pretraining",
    name: "Pretraining",
    spanishName: "Preentrenamiento",
    aliases: ["Preentrenamiento", "Pre-training", "Pre-entrenamiento"],
    category: "llm",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "La primera y más costosa fase de entrenamiento de un modelo fundacional, en la que aprende de enormes cantidades de datos sin etiquetar.",
    simpleExplanation:
      "Es la etapa de «educación general». Un LLM lee billones de palabras y aprende a predecir la siguiente. Al terminar, sabe mucho sobre el lenguaje y el mundo, pero todavía no sabe comportarse como asistente: si le haces una pregunta, podría continuar el texto con otra pregunta en vez de responder.\n\nEsa conducta de asistente llega después, con el [[fine-tuning]] y técnicas como [[rlhf]].",
    technicalExplanation:
      "Se optimiza una pérdida de [[cross-entropy]] sobre la [[next-token-prediction|predicción del siguiente token]] en un corpus masivo (web filtrada, libros, código, artículos científicos). Requiere miles de [[gpu|GPUs]] o [[tpu|TPUs]] durante semanas o meses, con paralelismo de datos, de tensores y de pipeline. Las decisiones críticas incluyen la mezcla y el filtrado de datos, el tamaño del modelo y el número de tokens, guiadas por [[scaling-laws]].",
    whyItMatters: "Aquí se forma la mayor parte del conocimiento y las capacidades del modelo; es también donde se gasta la mayor parte del cómputo.",
    useCases: ["Crear modelos fundacionales", "Entrenamiento continuo en dominios nuevos"],
    prerequisites: ["training", "self-supervised-learning"],
    relatedTerms: ["next-token-prediction", "foundation-model", "fine-tuning", "scaling-laws", "compute"],
    nextTerms: ["supervised-fine-tuning", "rlhf", "fine-tuning"],
    tags: ["preentrenar", "corpus", "entrenamiento masivo"],
  },
  {
    slug: "next-token-prediction",
    name: "Next-Token Prediction",
    spanishName: "Predicción del siguiente token",
    aliases: ["Predicción del siguiente token", "Predicción de la siguiente palabra", "Autoregressive", "Autoregresivo", "Causal language modeling"],
    category: "llm",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "La tarea con la que se entrenan los LLMs: dado un texto, predecir cuál es el token que sigue.",
    simpleExplanation:
      "«El cielo es…» → probablemente «azul». Un LLM aprende repitiendo este ejercicio billones de veces con textos reales. Para predecir bien la continuación de un problema de física, una receta o un fragmento de código, tiene que aprender física, cocina y programación.\n\nAl generar, repite el proceso: predice un token, lo añade al texto y predice el siguiente.",
    example: {
      title: "Probabilidades del siguiente token",
      code: "Texto:  \"La capital de Francia es\"\n\n  París      0.91\n  una        0.03\n  la         0.02\n  Lyon       0.01\n  …",
    },
    technicalExplanation:
      "El modelo estima p(xₜ | x₁, …, xₜ₋₁) y la probabilidad de una secuencia se factoriza como el producto de estas condicionales. En entrenamiento se usa **teacher forcing** y una máscara causal en la [[self-attention]] para que cada posición solo vea tokens anteriores, lo que permite calcular la pérdida de todas las posiciones en paralelo. En generación, el proceso es secuencial, lo que motiva optimizaciones como el [[kv-cache]] y el [[speculative-decoding]].",
    whyItMatters: "Explica tanto las capacidades de los LLMs como algunos de sus fallos: optimizan continuaciones plausibles, no necesariamente verdaderas.",
    useCases: ["Preentrenamiento de LLMs", "Autocompletado", "Generación de código"],
    prerequisites: ["token", "probability"],
    relatedTerms: ["pretraining", "sampling", "softmax", "llm", "decoder"],
    nextTerms: ["sampling", "temperature", "pretraining"],
    tags: ["autocompletar", "siguiente palabra", "autoregresivo"],
  },
  {
    slug: "token",
    name: "Token",
    aliases: ["Tokens", "Ficha"],
    category: "llm",
    secondaryCategories: ["fundamentals", "nlp"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La unidad básica de texto que procesa un modelo de lenguaje: puede ser una palabra, parte de una palabra o un signo.",
    simpleExplanation:
      "Los modelos no leen letras ni palabras completas: leen tokens. Una palabra común como «casa» puede ser un solo token, mientras que una palabra larga o rara como «desoxirribonucleico» se divide en varios pedazos.\n\nComo regla aproximada, en inglés un token equivale a unos ¾ de palabra; en español suele hacer falta algo más de tokens para el mismo texto. Los precios de las APIs y los límites de contexto se miden en tokens.",
    diagram: {
      kind: "flow",
      title: "De texto a tokens",
      steps: [
        { label: "Texto", chips: ["Los modelos leen tokens"] },
        { label: "Tokens", chips: ["Los", " modelos", " le", "en", " tokens"] },
        { label: "IDs numéricos", chips: ["8003", "28901", "513", "268", "11460"] },
      ],
      caption: "La división y los IDs son ilustrativos: cada tokenizer divide el texto de forma distinta.",
    },
    technicalExplanation:
      "Los tokens se definen mediante un [[tokenizer]] con un vocabulario fijo (típicamente decenas de miles a unos cientos de miles de entradas), construido con algoritmos de subpalabras como BPE. Cada token se asigna a un ID entero, que el modelo convierte en un [[embeddings|embedding]]. En modelos [[multimodal-model|multimodales]], imágenes y audio también se convierten en tokens (por ejemplo, parches de imagen).",
    commonMistakes: [
      "Un token no es lo mismo que una palabra. Por eso los modelos a veces fallan en tareas como contar letras: no «ven» las letras individuales, sino fragmentos.",
    ],
    whyItMatters: "Todo en un LLM se mide en tokens: el costo, la velocidad y cuánta información cabe en la [[context-window|ventana de contexto]].",
    useCases: ["Calcular costos de API", "Estimar límites de contexto", "Diseñar prompts eficientes"],
    prerequisites: ["llm"],
    relatedTerms: ["tokenization", "tokenizer", "context-window", "embeddings"],
    nextTerms: ["tokenization", "embeddings", "context-window"],
    tags: ["tokens", "palabras", "costo", "precio"],
  },
  {
    slug: "tokenization",
    name: "Tokenization",
    spanishName: "Tokenización",
    aliases: ["Tokenización", "BPE", "Byte Pair Encoding", "Subword tokenization"],
    category: "nlp",
    secondaryCategories: ["llm"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "El proceso de dividir un texto en tokens para que un modelo pueda procesarlo.",
    simpleExplanation:
      "Antes de que un modelo pueda leer algo, el texto se corta en pedazos (tokens) y cada pedazo se reemplaza por un número. Es como convertir una frase en una secuencia de códigos de un diccionario.\n\nLas palabras frecuentes suelen ser un solo token; las raras se dividen en partes más pequeñas que sí están en el diccionario.",
    technicalExplanation:
      "El método más usado es **Byte Pair Encoding (BPE)**: empieza con bytes o caracteres y fusiona repetidamente los pares más frecuentes del corpus hasta alcanzar el tamaño de vocabulario deseado. Alternativas: WordPiece (BERT) y Unigram (SentencePiece). Trabajar a nivel de bytes garantiza que cualquier texto sea representable.\n\nLa tokenización influye en el rendimiento multilingüe: idiomas poco representados en el corpus del tokenizer necesitan más tokens por palabra, lo que los hace más caros y consume más contexto.",
    whyItMatters: "Afecta el costo, la eficiencia y hasta la calidad del modelo en distintos idiomas.",
    useCases: ["Preprocesamiento de texto", "Diseño de vocabularios", "Estimación de costos"],
    prerequisites: ["token"],
    relatedTerms: ["token", "tokenizer", "embeddings", "nlp"],
    nextTerms: ["tokenizer", "embeddings"],
    tags: ["bpe", "subpalabras", "vocabulario"],
    sources: [
      { title: "Neural Machine Translation of Rare Words with Subword Units", authors: "Sennrich, Haddow & Birch", year: 2015, url: "https://arxiv.org/abs/1508.07909", kind: "paper" },
    ],
  },
  {
    slug: "tokenizer",
    name: "Tokenizer",
    spanishName: "Tokenizador",
    aliases: ["Tokenizador"],
    category: "nlp",
    secondaryCategories: ["llm"],
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "El componente que convierte texto en tokens (y tokens de vuelta en texto) usando un vocabulario fijo.",
    simpleExplanation:
      "Es el traductor entre el texto humano y los números que entiende el modelo. Cada modelo tiene su propio tokenizer; por eso el mismo texto puede costar distinto número de tokens en modelos diferentes.",
    technicalExplanation:
      "Un tokenizer incluye el vocabulario, las reglas de fusión (en BPE), la normalización previa (espacios, Unicode) y **tokens especiales** que marcan inicio y fin de secuencia o los roles de un chat (sistema, usuario, asistente). Se entrena antes que el modelo y queda fijo: cambiarlo exige reentrenar o adaptar la capa de embeddings.",
    whyItMatters: "Usar el tokenizer correcto es indispensable para contar tokens, estimar costos y formatear conversaciones.",
    useCases: ["Contar tokens", "Formatear conversaciones", "Preprocesar datasets"],
    prerequisites: ["tokenization"],
    relatedTerms: ["token", "tokenization", "system-prompt"],
    nextTerms: ["embeddings", "context-window"],
    tags: ["vocabulario", "tokens especiales"],
  },
  {
    slug: "context-window",
    name: "Context Window",
    spanishName: "Ventana de contexto",
    aliases: ["Ventana de contexto", "Context length", "Longitud de contexto", "Contexto", "Context size"],
    category: "llm",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "La cantidad máxima de tokens que un modelo puede considerar a la vez, incluyendo tu mensaje, el historial y su propia respuesta.",
    simpleExplanation:
      "Es la memoria de trabajo del modelo. Todo lo que el modelo «tiene presente» en un momento dado —instrucciones, conversación, documentos que le pegaste y la respuesta que está escribiendo— debe caber en esta ventana.\n\nSi la conversación la excede, algo tiene que quedar fuera: el sistema recorta o resume el historial, y el modelo simplemente deja de ver esa información.",
    analogy:
      "Es como el escritorio donde trabajas: puedes tener muchos papeles a la vista, pero el espacio es limitado. Lo que no cabe en el escritorio queda guardado en otro lugar, y no puedes consultarlo sin traerlo de vuelta.",
    technicalExplanation:
      "La ventana se mide en tokens; los modelos comerciales actuales van desde decenas de miles hasta un millón de tokens o más. El costo de la [[self-attention]] estándar crece de forma cuadrática con la longitud, y la memoria del [[kv-cache]] crece linealmente, por lo que contextos largos son caros.\n\nQue un modelo acepte un contexto largo no garantiza que use bien toda la información: estudios como «Lost in the Middle» mostraron que la información en medio de contextos largos puede aprovecharse peor. Técnicas de [[positional-encoding|codificación posicional]] como RoPE y sus extensiones permiten ampliar la ventana.",
    commonMistakes: [
      "Una ventana de contexto grande no reemplaza siempre a [[rag]]: recuperar solo lo relevante suele ser más barato, más rápido y a veces más preciso que meter todo en el prompt.",
    ],
    whyItMatters: "Determina cuánta información puede considerar un modelo durante una interacción: cuántos documentos analizar, qué tan larga puede ser una conversación y cuánto contexto necesita un agente.",
    useCases: ["Analizar documentos largos", "Conversaciones extensas", "Agentes con mucho historial", "Revisión de código de repositorios"],
    prerequisites: ["token", "llm"],
    relatedTerms: ["token", "kv-cache", "rag", "memory", "self-attention"],
    nextTerms: ["rag", "kv-cache", "memory"],
    tags: ["contexto", "memoria", "límite de tokens", "longitud"],
  },
  {
    slug: "hallucination",
    name: "Hallucination",
    spanishName: "Alucinación",
    aliases: ["Alucinación", "Alucinaciones", "Confabulación"],
    category: "llm",
    secondaryCategories: ["safety"],
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Cuando un modelo genera información falsa o inventada presentándola con seguridad como si fuera cierta.",
    simpleExplanation:
      "Un LLM puede citar un libro que no existe, inventar una estadística o atribuir una frase a quien nunca la dijo, y hacerlo con total naturalidad. A eso se le llama alucinación.\n\nOcurre porque el modelo está entrenado para producir texto **plausible**, y lo plausible no siempre es verdadero. Cuando no sabe algo, a veces completa el hueco con lo que «suena bien».",
    technicalExplanation:
      "Causas: el objetivo de [[next-token-prediction|predicción del siguiente token]] no penaliza directamente la falsedad; conocimiento escaso o contradictorio en los datos; y un post-entrenamiento que puede premiar respuestas seguras sobre admitir incertidumbre. Mitigaciones: [[grounding]] con [[rag]], uso de [[tool-calling|herramientas]] de búsqueda o cálculo, pedir citas verificables, entrenamiento para expresar incertidumbre y [[evaluation|evaluaciones]] de factualidad.",
    commonMistakes: [
      "Bajar la [[temperature|temperatura]] reduce la variabilidad, pero no elimina las alucinaciones: un modelo puede equivocarse de forma perfectamente consistente.",
    ],
    whyItMatters: "Es uno de los mayores obstáculos para usar LLMs en contextos donde la exactitud es crítica, como salud, derecho o finanzas.",
    useCases: ["Diseño de sistemas confiables", "Evaluación de factualidad", "Motivación para RAG"],
    prerequisites: ["llm"],
    relatedTerms: ["grounding", "rag", "evaluation", "guardrails"],
    nextTerms: ["grounding", "rag"],
    tags: ["inventar", "errores", "factualidad", "falso"],
  },
  {
    slug: "temperature",
    name: "Temperature",
    spanishName: "Temperatura",
    aliases: ["Temperatura"],
    category: "llm",
    secondaryCategories: ["prompt-engineering"],
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "Un parámetro que controla qué tan aleatorias o predecibles son las respuestas de un modelo generativo.",
    simpleExplanation:
      "Con temperatura baja, el modelo elige casi siempre las palabras más probables: respuestas consistentes y conservadoras. Con temperatura alta, se anima a elegir opciones menos probables: respuestas más variadas y creativas, pero también más propensas a errores.\n\nPara extraer datos o escribir código conviene una temperatura baja; para lluvia de ideas, una más alta.",
    technicalExplanation:
      "La temperatura T divide los logits antes de aplicar [[softmax]]. Con T → 0 la distribución se concentra en el token más probable (equivalente a *greedy decoding*); con T = 1 se usa la distribución original; con T > 1 se aplana. Suele combinarse con [[top-p]] o top-k para truncar la cola de tokens improbables.",
    math: {
      formula: "pᵢ = exp(zᵢ / T) / Σⱼ exp(zⱼ / T)",
      symbols: [
        { symbol: "zᵢ", meaning: "Logit (puntuación sin normalizar) del token i" },
        { symbol: "T", meaning: "Temperatura: menor a 1 agudiza, mayor a 1 aplana" },
        { symbol: "pᵢ", meaning: "Probabilidad final de elegir el token i" },
      ],
    },
    whyItMatters: "Es una de las perillas más simples y efectivas para ajustar el comportamiento de un modelo a cada caso de uso.",
    useCases: ["Extracción de datos (baja)", "Escritura creativa (alta)", "Generar variantes"],
    prerequisites: ["sampling", "softmax"],
    relatedTerms: ["top-p", "sampling", "softmax", "hallucination"],
    nextTerms: ["top-p", "sampling"],
    tags: ["creatividad", "aleatoriedad", "parámetros de generación"],
  },
  {
    slug: "top-p",
    name: "Top-P",
    spanishName: "Nucleus sampling",
    aliases: ["Top P", "Nucleus sampling", "Muestreo de núcleo", "Top-k"],
    category: "llm",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Una técnica de muestreo que elige el siguiente token solo entre las opciones más probables cuya probabilidad acumulada alcanza un umbral p.",
    simpleExplanation:
      "Con top-p = 0.9, el modelo ordena los posibles siguientes tokens de más a menos probable y se queda con los primeros hasta sumar 90% de probabilidad. Luego elige uno de ese grupo. Así evita opciones muy raras sin volverse completamente predecible.",
    technicalExplanation:
      "Propuesto como *nucleus sampling* por Holtzman et al. (2019). A diferencia de **top-k** (que conserva siempre k tokens), top-p adapta el tamaño del conjunto: si el modelo está seguro, el núcleo es pequeño; si hay incertidumbre, se amplía. Tras truncar, las probabilidades se renormalizan. Suele recomendarse ajustar temperatura o top-p, no ambos a la vez de forma agresiva.",
    whyItMatters: "Reduce el texto incoherente que aparece al muestrear tokens muy improbables.",
    useCases: ["Generación de texto", "Chatbots", "Escritura creativa"],
    prerequisites: ["sampling"],
    relatedTerms: ["temperature", "sampling", "probability-distribution"],
    nextTerms: ["temperature"],
    tags: ["muestreo", "top-k", "nucleus"],
    sources: [
      { title: "The Curious Case of Neural Text Degeneration", authors: "Holtzman et al.", year: 2019, url: "https://arxiv.org/abs/1904.09751", kind: "paper" },
    ],
  },
  {
    slug: "sampling",
    name: "Sampling",
    spanishName: "Muestreo",
    aliases: ["Muestreo", "Decoding", "Decodificación", "Greedy decoding"],
    category: "llm",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "El método con el que un modelo generativo elige el siguiente token a partir de su distribución de probabilidades.",
    simpleExplanation:
      "Un LLM no «decide» una palabra directamente: calcula probabilidades para todas las posibles. El sampling es la regla para escoger: siempre la más probable, o una al azar respetando las probabilidades, o algo intermedio.\n\nPor eso la misma pregunta puede recibir respuestas distintas.",
    technicalExplanation:
      "Estrategias: **greedy** (siempre el argmax), **beam search** (explora varias secuencias candidatas; común en traducción), **muestreo aleatorio** con [[temperature|temperatura]], **top-k** y [[top-p]]. Parámetros como penalización por repetición también modifican la distribución antes de muestrear. La elección afecta diversidad, coherencia y riesgo de repeticiones.",
    whyItMatters: "Explica por qué los modelos no son deterministas y cómo controlar su variabilidad.",
    useCases: ["Generación de texto", "Generación de código", "Traducción"],
    prerequisites: ["next-token-prediction", "probability-distribution"],
    relatedTerms: ["temperature", "top-p", "softmax", "speculative-decoding"],
    nextTerms: ["temperature", "top-p"],
    tags: ["decodificación", "greedy", "beam search"],
  },
  {
    slug: "reasoning-model",
    name: "Reasoning Model",
    spanishName: "Modelo de razonamiento",
    aliases: ["Modelo de razonamiento", "Modelos que piensan", "Thinking model", "Extended thinking", "Multimodal reasoning"],
    category: "llm",
    secondaryCategories: ["frontier"],
    difficulty: "advanced",
    type: "model",
    frontier: true,
    shortDefinition: "Un LLM entrenado para generar un proceso de razonamiento extenso antes de responder, lo que mejora su desempeño en problemas complejos.",
    simpleExplanation:
      "Un modelo tradicional responde casi de inmediato. Un modelo de razonamiento primero «piensa»: escribe pasos intermedios, prueba enfoques, detecta errores y los corrige; después da la respuesta final.\n\nEs como la diferencia entre contestar un problema de matemáticas de memoria o resolverlo en una hoja de borrador.",
    technicalExplanation:
      "Estos modelos se entrenan, típicamente con [[reinforcement-learning|aprendizaje por refuerzo]] sobre tareas con respuestas verificables (matemáticas, programación), para producir cadenas de razonamiento largas y útiles. Ejemplos públicos incluyen la serie o1 de OpenAI (2024) y DeepSeek-R1 (2025), y modos de «pensamiento extendido» en otros modelos.\n\nSu rendimiento escala con el [[test-time-compute|cómputo en tiempo de inferencia]]: permitir más tokens de razonamiento suele mejorar la precisión, a cambio de mayor [[latency|latencia]] y costo. Está relacionado con el [[chain-of-thought]], pero aquí el razonamiento es un comportamiento entrenado, no solo inducido por el prompt.",
    whyItMatters: "Marcaron un cambio en cómo mejora la IA: no solo con modelos más grandes, sino dejándolos pensar más tiempo al responder.",
    useCases: ["Matemáticas", "Programación compleja", "Análisis científico", "Planificación de agentes"],
    prerequisites: ["llm", "chain-of-thought"],
    relatedTerms: ["test-time-compute", "chain-of-thought", "reinforcement-learning", "latent-reasoning"],
    nextTerms: ["test-time-compute", "latent-reasoning"],
    tags: ["razonamiento", "pensar", "o1", "r1", "thinking"],
    sources: [
      { title: "Learning to reason with LLMs", authors: "OpenAI", year: 2024, url: "https://openai.com/index/learning-to-reason-with-llms/", kind: "article" },
      { title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning", authors: "DeepSeek-AI", year: 2025, url: "https://arxiv.org/abs/2501.12948", kind: "paper" },
    ],
  },
  {
    slug: "multimodal-model",
    name: "Multimodal Model",
    spanishName: "Modelo multimodal",
    aliases: ["Modelo multimodal", "Multimodal AI", "IA multimodal", "VLM", "Vision-language model"],
    category: "generative-ai",
    secondaryCategories: ["llm", "computer-vision"],
    difficulty: "intermediate",
    type: "model",
    shortDefinition: "Un modelo capaz de procesar y a veces generar varios tipos de información, como texto, imágenes, audio o video.",
    simpleExplanation:
      "Los primeros LLMs solo entendían texto. Un modelo multimodal puede ver una foto de tu refrigerador y sugerir recetas, leer una gráfica, escuchar un audio o describir un video.\n\nEs más parecido a cómo percibimos el mundo las personas: combinando sentidos.",
    technicalExplanation:
      "Un diseño común conecta un codificador de imágenes (por ejemplo, un [[vision-transformer]]) con un LLM mediante una capa de proyección que convierte las características visuales en «tokens» del mismo espacio de embeddings que el texto. Otros modelos se entrenan de forma nativamente multimodal desde el inicio. Para generar imágenes o audio suelen combinarse con decodificadores especializados o [[diffusion-model|modelos de difusión]].",
    whyItMatters: "Amplía enormemente lo que la IA puede hacer: entender documentos escaneados, interfaces, fotos, diagramas y conversaciones de voz.",
    useCases: ["Lectura de documentos e imágenes", "Asistentes de voz", "Análisis de gráficas", "Computer use", "Accesibilidad"],
    prerequisites: ["llm", "computer-vision"],
    relatedTerms: ["vision-transformer", "computer-use", "image-generation", "embeddings"],
    nextTerms: ["vision-transformer", "computer-use"],
    tags: ["multimodal", "visión", "audio", "imágenes"],
  },
  {
    slug: "open-weights-model",
    name: "Open-Weights Model",
    spanishName: "Modelo de pesos abiertos",
    aliases: ["Pesos abiertos", "Open weights", "Modelo abierto", "Open source model", "Open model"],
    category: "llm",
    secondaryCategories: ["ai-engineering"],
    difficulty: "intermediate",
    type: "model",
    shortDefinition: "Un modelo cuyos pesos entrenados se publican para que cualquiera pueda descargarlo, ejecutarlo y adaptarlo.",
    simpleExplanation:
      "Algunos modelos solo se pueden usar a través de la API de la empresa que los creó. Otros publican sus [[weights|pesos]]: puedes descargarlos y ejecutarlos en tu propia computadora o servidor, sin enviar tus datos a nadie.\n\n«Pesos abiertos» no siempre significa «código abierto» completo: a menudo no se publican los datos ni el código de entrenamiento, y la licencia puede tener restricciones.",
    technicalExplanation:
      "Se distribuyen como archivos de pesos (por ejemplo, safetensors) con su configuración y [[tokenizer]]. Permiten [[fine-tuning]], [[quantization|cuantización]] para hardware modesto y despliegue privado. La Open Source Initiative publicó una definición de IA de código abierto (OSAID) que exige, entre otras cosas, información suficiente sobre los datos de entrenamiento; muchos modelos «abiertos» no cumplen esa definición.",
    whyItMatters: "Da control, privacidad y la posibilidad de personalizar, a cambio de gestionar tú mismo la infraestructura.",
    useCases: ["Despliegue on-premise", "Investigación", "Fine-tuning especializado", "Ejecución local"],
    prerequisites: ["weights", "llm"],
    relatedTerms: ["weights", "fine-tuning", "quantization", "inference-server"],
    nextTerms: ["quantization", "lora"],
    tags: ["open source", "llama", "local", "descargar"],
  },
];
