import type { TermInput } from "@/types/glossary";

export const infrastructureTerms: TermInput[] = [
  {
    slug: "cpu",
    name: "CPU",
    spanishName: "Unidad central de procesamiento",
    acronym: "CPU",
    aliases: ["Procesador", "Central Processing Unit", "Unidad central de procesamiento"],
    category: "hardware",
    difficulty: "beginner",
    type: "infrastructure",
    shortDefinition: "El procesador de propósito general de una computadora, optimizado para ejecutar tareas variadas de forma secuencial y flexible.",
    simpleExplanation:
      "La CPU es el «cerebro» general de tu computadora: abre programas, navega en internet, ejecuta tu sistema operativo. Tiene pocos núcleos muy potentes y versátiles. Para IA puede funcionar, pero es lenta comparada con una [[gpu]] en los cálculos masivos que requieren las redes neuronales.",
    comparison: {
      title: "CPU vs. GPU",
      columns: ["CPU", "GPU"],
      rows: [
        { aspect: "Núcleos", a: "Pocos (decenas), muy potentes", b: "Miles, más simples" },
        { aspect: "Fuerte en", a: "Tareas variadas y secuenciales", b: "Mismo cálculo sobre muchísimos datos en paralelo" },
        { aspect: "Para deep learning", a: "Lenta en entrenamiento; útil para modelos pequeños", b: "El estándar para entrenar y servir modelos" },
        { aspect: "Memoria", a: "RAM del sistema, grande pero con menos ancho de banda", b: "VRAM con altísimo ancho de banda" },
      ],
    },
    technicalExplanation:
      "Las CPUs priorizan baja latencia por hilo, predicción de saltos y cachés grandes. Incluyen instrucciones vectoriales (AVX, NEON) que aceleran algo de álgebra lineal. En IA se usan para preprocesamiento de datos, orquestación, modelos clásicos de ML e inferencia de modelos pequeños o [[quantization|cuantizados]] cuando no hay GPU.",
    whyItMatters: "Entender su diferencia con la GPU explica por qué la IA moderna depende de hardware especializado.",
    useCases: ["Preprocesamiento de datos", "Modelos clásicos de ML", "Inferencia local de modelos pequeños"],
    relatedTerms: ["gpu", "npu", "tpu"],
    nextTerms: ["gpu"],
    tags: ["procesador", "hardware"],
  },
  {
    slug: "gpu",
    name: "GPU",
    spanishName: "Unidad de procesamiento gráfico",
    acronym: "GPU",
    aliases: ["Graphics Processing Unit", "Tarjeta gráfica", "Tarjeta de video", "Unidad de procesamiento gráfico", "H100", "Acelerador"],
    category: "hardware",
    secondaryCategories: ["fundamentals"],
    difficulty: "beginner",
    type: "infrastructure",
    shortDefinition: "Un procesador con miles de núcleos diseñado para hacer muchos cálculos en paralelo; es el hardware principal para entrenar y ejecutar modelos de IA.",
    simpleExplanation:
      "Las GPUs se inventaron para videojuegos: calcular el color de millones de píxeles al mismo tiempo. Resulta que las redes neuronales necesitan exactamente eso: millones de multiplicaciones simples en paralelo.\n\nPor eso las GPUs se convirtieron en el motor de la IA. Una CPU es como un chef experto; una GPU es como una cocina con miles de ayudantes haciendo la misma tarea a la vez.",
    comparison: {
      title: "CPU vs. GPU",
      columns: ["CPU", "GPU"],
      rows: [
        { aspect: "Núcleos", a: "Pocos y potentes", b: "Miles y simples" },
        { aspect: "Estilo", a: "Secuencial y flexible", b: "Masivamente paralelo" },
        { aspect: "En IA", a: "Tareas auxiliares", b: "Entrenamiento e inferencia" },
      ],
    },
    technicalExplanation:
      "Las GPUs ejecutan miles de hilos en paralelo (modelo SIMT) y, en generaciones recientes, incluyen [[tensor-core|Tensor Cores]] especializados en multiplicación de matrices a baja precisión. Su memoria ([[vram|VRAM]], típicamente HBM en centros de datos) tiene un ancho de banda muy alto, crucial porque la inferencia de LLMs suele estar limitada por memoria, no por cálculo. El ecosistema de software ([[cuda|CUDA]] y librerías como cuDNN) es una parte central de su ventaja. Para modelos grandes se conectan muchas GPUs mediante interconexiones rápidas en [[cluster|clusters]].",
    whyItMatters: "La disponibilidad de GPUs condiciona quién puede entrenar modelos, cuánto cuesta usarlos y qué tan rápido avanza la IA.",
    useCases: ["Entrenamiento de modelos", "Inferencia de LLMs", "Generación de imágenes", "Simulaciones científicas"],
    prerequisites: ["cpu"],
    relatedTerms: ["vram", "cuda", "tensor-core", "tpu", "cluster", "compute"],
    nextTerms: ["vram", "cuda", "tensor-core"],
    tags: ["tarjeta gráfica", "nvidia", "aceleradores", "paralelo"],
  },
  {
    slug: "tpu",
    name: "TPU",
    spanishName: "Unidad de procesamiento tensorial",
    acronym: "TPU",
    aliases: ["Tensor Processing Unit", "Unidad de procesamiento tensorial"],
    category: "hardware",
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "Un chip diseñado por Google específicamente para acelerar cálculos de redes neuronales.",
    simpleExplanation:
      "Mientras las GPUs son chips gráficos adaptados a la IA, las TPUs se diseñaron desde el principio solo para IA. Google las usa en sus propios servicios y las ofrece en su nube.",
    technicalExplanation:
      "Son ASICs basados en **arreglos sistólicos** para multiplicación de matrices, con memoria de alto ancho de banda y soporte para formatos como bfloat16. Se agrupan en *pods* con interconexión dedicada para entrenamiento a gran escala. Jouppi et al. (2017) describieron la primera generación, orientada a inferencia; las posteriores también entrenan.",
    whyItMatters: "Son una alternativa importante a las GPUs para entrenar y servir modelos a escala.",
    useCases: ["Entrenamiento de modelos grandes", "Inferencia en la nube"],
    prerequisites: ["gpu"],
    relatedTerms: ["gpu", "npu", "tensor", "cluster"],
    nextTerms: ["npu", "cluster"],
    tags: ["google", "asic", "acelerador"],
    sources: [{ title: "In-Datacenter Performance Analysis of a Tensor Processing Unit", authors: "Jouppi et al.", year: 2017, url: "https://arxiv.org/abs/1704.04760", kind: "paper" }],
  },
  {
    slug: "npu",
    name: "NPU",
    spanishName: "Unidad de procesamiento neuronal",
    acronym: "NPU",
    aliases: ["Neural Processing Unit", "Unidad de procesamiento neuronal", "Neural Engine"],
    category: "hardware",
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "Un procesador especializado en IA integrado en teléfonos, laptops y otros dispositivos para ejecutar modelos de forma eficiente.",
    simpleExplanation:
      "Tu teléfono probablemente tiene una NPU. Es la que permite que funciones como el desenfoque de fondo en fotos, el dictado por voz o la traducción en vivo funcionen rápido y sin gastar mucha batería, a veces sin conexión a internet.",
    technicalExplanation:
      "Las NPUs priorizan eficiencia energética (operaciones por watt) para inferencia, con soporte para enteros de baja precisión (INT8, INT4). Suelen ejecutar modelos [[quantization|cuantizados]] y [[model-compression|comprimidos]]. Permiten IA en el dispositivo (*on-device*), con ventajas de privacidad y latencia.",
    whyItMatters: "Llevan la IA al dispositivo del usuario, sin depender siempre de la nube.",
    useCases: ["Fotografía computacional", "Asistentes en el dispositivo", "Transcripción local"],
    prerequisites: ["gpu"],
    relatedTerms: ["tpu", "gpu", "quantization", "model-compression"],
    nextTerms: ["quantization"],
    tags: ["móvil", "on-device", "edge"],
  },
  {
    slug: "vram",
    name: "VRAM",
    spanishName: "Memoria de video",
    acronym: "VRAM",
    aliases: ["Memoria de video", "Memoria de GPU", "GPU memory", "HBM"],
    category: "hardware",
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "La memoria propia de una GPU, donde deben caber los pesos del modelo y los datos intermedios durante el cómputo.",
    simpleExplanation:
      "Para que una GPU ejecute un modelo, el modelo tiene que caber en su memoria. Si un modelo necesita 40 GB y tu GPU tiene 24 GB, no cabe tal cual: necesitas otra GPU, repartirlo entre varias o comprimirlo con [[quantization|cuantización]].\n\nPor eso la VRAM suele ser el factor limitante al elegir hardware para IA.",
    technicalExplanation:
      "En inferencia, la VRAM se ocupa con pesos (parámetros × bytes por parámetro), [[kv-cache]] (crece con la longitud del contexto y el tamaño del batch) y activaciones. En entrenamiento, además, gradientes y estados del optimizador (Adam guarda dos valores extra por parámetro), por lo que el entrenamiento completo requiere varias veces la memoria de los pesos. Las GPUs de centro de datos usan HBM, con ancho de banda de varios TB/s.",
    whyItMatters: "Determina qué modelos puedes ejecutar o entrenar en un hardware dado.",
    useCases: ["Elegir GPUs", "Planear despliegues", "Decidir cuantización"],
    prerequisites: ["gpu", "parameters"],
    relatedTerms: ["gpu", "kv-cache", "quantization", "parameters"],
    nextTerms: ["quantization", "kv-cache"],
    tags: ["memoria", "hbm", "gigabytes"],
  },
  {
    slug: "cuda",
    name: "CUDA",
    acronym: "CUDA",
    aliases: ["Compute Unified Device Architecture"],
    category: "hardware",
    secondaryCategories: ["ai-engineering"],
    difficulty: "advanced",
    type: "infrastructure",
    shortDefinition: "La plataforma de programación de NVIDIA que permite usar sus GPUs para cálculo general, incluida la IA.",
    simpleExplanation:
      "Una GPU no sirve de nada si no puedes programarla. CUDA es el conjunto de herramientas que permite escribir programas que corren en GPUs de NVIDIA. Frameworks como PyTorch lo usan por debajo, así que la mayoría de las personas lo aprovechan sin escribir CUDA directamente.",
    technicalExplanation:
      "Lanzado en 2007, CUDA ofrece un modelo de programación (kernels, hilos, bloques, memoria compartida), un compilador y librerías optimizadas (cuBLAS, cuDNN, NCCL para comunicación entre GPUs). Su madurez y ecosistema son una ventaja competitiva importante de NVIDIA. Alternativas: ROCm (AMD), Triton (lenguaje de kernels de alto nivel) y compiladores como XLA.",
    whyItMatters: "Explica por qué el software, no solo el chip, es clave en la carrera del hardware de IA.",
    useCases: ["Kernels personalizados", "Frameworks de deep learning", "Computación científica"],
    prerequisites: ["gpu"],
    relatedTerms: ["gpu", "tensor-core", "inference-optimization"],
    nextTerms: ["tensor-core"],
    tags: ["nvidia", "programación gpu", "kernels"],
  },
  {
    slug: "tensor-core",
    name: "Tensor Core",
    aliases: ["Tensor Cores", "Núcleos tensoriales"],
    category: "hardware",
    difficulty: "advanced",
    type: "infrastructure",
    shortDefinition: "Unidades especializadas dentro de las GPUs de NVIDIA que multiplican matrices pequeñas a gran velocidad y baja precisión.",
    simpleExplanation:
      "Casi todo el trabajo de una red neuronal son multiplicaciones de matrices. Los Tensor Cores son circuitos diseñados solo para eso, y lo hacen muchas veces más rápido que los núcleos normales de la GPU.",
    technicalExplanation:
      "Introducidos en la arquitectura Volta (2017), ejecutan operaciones de multiplicación y acumulación sobre bloques de matrices en formatos como FP16, BF16, TF32, FP8 e INT8, acumulando en mayor precisión. Aprovecharlos requiere dimensiones alineadas y precisión mixta. Son una razón central de las enormes mejoras de rendimiento en deep learning de las últimas generaciones de GPUs.",
    whyItMatters: "Buena parte de la velocidad de las GPUs modernas para IA viene de ellos.",
    useCases: ["Entrenamiento con precisión mixta", "Inferencia en FP8/INT8"],
    prerequisites: ["gpu", "matrix"],
    relatedTerms: ["gpu", "cuda", "flops", "quantization"],
    nextTerms: ["flops"],
    tags: ["matrices", "precisión mixta"],
  },
  {
    slug: "cluster",
    name: "Training Cluster",
    spanishName: "Cluster de entrenamiento",
    aliases: ["Cluster", "Clúster", "Training cluster", "Supercomputadora de IA", "Cluster de GPUs"],
    category: "hardware",
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "Un conjunto de muchas computadoras con GPUs o TPUs conectadas por redes muy rápidas para entrenar modelos que no caben en una sola máquina.",
    simpleExplanation:
      "Ningún chip por sí solo puede entrenar un LLM de frontera en un tiempo razonable. Se conectan miles de GPUs como si fueran una sola supercomputadora, repartiendo el modelo y los datos entre ellas.",
    technicalExplanation:
      "Se usan varias formas de paralelismo: **de datos** (cada GPU procesa un lote distinto y se sincronizan los gradientes), **de tensores** (se reparte cada matriz entre GPUs), **de pipeline** (cada grupo de GPUs ejecuta un grupo de capas) y **de expertos** (en MoE). La red (NVLink dentro del nodo, InfiniBand o Ethernet especializada entre nodos) es crítica. A esta escala, las fallas de hardware son frecuentes y requieren checkpoints y recuperación automática.",
    whyItMatters: "El tamaño de los clusters disponibles marca el ritmo del progreso de los modelos de frontera.",
    useCases: ["Preentrenamiento de LLMs", "Investigación a gran escala"],
    prerequisites: ["gpu"],
    relatedTerms: ["data-center", "gpu", "compute", "pretraining"],
    nextTerms: ["data-center"],
    tags: ["supercomputadora", "paralelismo", "gpus"],
  },
  {
    slug: "data-center",
    name: "Data Center",
    spanishName: "Centro de datos",
    aliases: ["Centro de datos", "Datacenter", "AI data center"],
    category: "hardware",
    difficulty: "beginner",
    type: "infrastructure",
    shortDefinition: "Una instalación que aloja miles de servidores, con la energía, refrigeración y red necesarias para operarlos continuamente.",
    simpleExplanation:
      "Cuando usas un asistente de IA, tu pregunta viaja a un edificio lleno de servidores —un centro de datos— donde se ejecuta el modelo. Los centros de datos para IA consumen enormes cantidades de electricidad y necesitan sistemas de refrigeración avanzados.",
    technicalExplanation:
      "Los centros de datos para IA tienen densidades de potencia por rack mucho mayores que los tradicionales, lo que impulsa la refrigeración líquida. Sus limitantes principales son el acceso a energía, la red eléctrica, el agua para refrigeración y la cadena de suministro de chips. Su huella energética es un tema creciente de debate público y regulatorio.",
    whyItMatters: "La infraestructura física —energía incluida— es hoy uno de los cuellos de botella de la IA.",
    useCases: ["Entrenamiento", "Inferencia en la nube"],
    relatedTerms: ["cluster", "gpu", "compute", "inference-server"],
    nextTerms: ["cluster", "inference-server"],
    tags: ["infraestructura", "energía", "nube"],
  },
  {
    slug: "inference-server",
    name: "Inference Server",
    spanishName: "Servidor de inferencia",
    aliases: ["Servidor de inferencia", "Model server", "Serving", "vLLM", "Model serving"],
    category: "ai-engineering",
    secondaryCategories: ["mlops", "hardware"],
    difficulty: "advanced",
    type: "infrastructure",
    shortDefinition: "El software que carga un modelo en el hardware y atiende solicitudes de muchos usuarios de forma eficiente.",
    simpleExplanation:
      "Tener un modelo no basta: hay que ponerlo a disposición de los usuarios. Un servidor de inferencia recibe las peticiones, las organiza, las ejecuta en las GPUs y devuelve las respuestas, idealmente rápido y sin desperdiciar hardware.",
    technicalExplanation:
      "Implementan [[batching|continuous batching]], gestión del [[kv-cache]] (por ejemplo, PagedAttention en vLLM), streaming de tokens, [[quantization]], paralelismo de tensores entre GPUs, prompt caching y APIs compatibles con los estándares del mercado. Se monitorean métricas como TTFT, tokens/s, utilización de GPU y colas de espera.",
    whyItMatters: "Es la pieza que convierte un modelo en un servicio usable y rentable.",
    useCases: ["Servir modelos abiertos", "APIs internas", "Despliegues on-premise"],
    prerequisites: ["inference", "gpu"],
    relatedTerms: ["inference-optimization", "batching", "kv-cache", "model-deployment"],
    nextTerms: ["model-deployment", "inference-optimization"],
    tags: ["serving", "vllm", "servidor"],
  },
  {
    slug: "ai-engineering",
    name: "AI Engineering",
    spanishName: "Ingeniería de IA",
    aliases: ["Ingeniería de IA", "AI engineer", "LLM engineering", "Ingeniero de IA"],
    category: "ai-engineering",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "La disciplina de construir productos y sistemas confiables sobre modelos de IA existentes, especialmente LLMs.",
    simpleExplanation:
      "No todo el que trabaja con IA entrena modelos. La mayoría de los equipos toman un modelo existente y construyen algo útil encima: un asistente, un buscador, un agente. La ingeniería de IA se ocupa de eso: prompts, RAG, herramientas, evaluaciones, costos y experiencia de usuario.",
    technicalExplanation:
      "Abarca: selección de modelos, [[prompt-engineering]], [[rag]], [[tool-calling|herramientas]] y [[ai-agent|agentes]], [[structured-output|salidas estructuradas]], [[evaluation|evals]] sistemáticas, [[guardrails]], observabilidad, gestión de [[latency|latencia]] y costos, y seguridad (por ejemplo, frente a [[prompt-injection]]). Se diferencia del ML tradicional en que el foco pasa de entrenar modelos a componer y evaluar sistemas alrededor de ellos.",
    whyItMatters: "Es donde la mayoría de las organizaciones generan valor con la IA hoy.",
    useCases: ["Asistentes empresariales", "Productos con LLMs", "Automatización"],
    prerequisites: ["llm", "api"],
    relatedTerms: ["api", "rag", "evaluation", "mlops", "orchestration"],
    nextTerms: ["evaluation", "rag", "ai-agent"],
    tags: ["ingeniería", "productos de ia", "desarrollo"],
  },
  {
    slug: "api",
    name: "API",
    spanishName: "Interfaz de programación de aplicaciones",
    acronym: "API",
    aliases: ["Application Programming Interface", "Interfaz de programación", "API de IA", "Endpoint"],
    category: "ai-engineering",
    secondaryCategories: ["fundamentals"],
    difficulty: "beginner",
    type: "infrastructure",
    shortDefinition: "Una interfaz que permite que un programa use los servicios de otro; en IA, la forma habitual de enviar solicitudes a un modelo alojado por un proveedor.",
    simpleExplanation:
      "Una API es como el mesero de un restaurante: tú (tu programa) pides algo en un formato acordado, el mesero lo lleva a la cocina (el modelo) y te trae el resultado. No necesitas saber cómo funciona la cocina.\n\nLa mayoría de las aplicaciones de IA no ejecutan el modelo por su cuenta: llaman a la API de un proveedor y pagan por [[token]] procesado.",
    example: {
      title: "Una solicitud típica (simplificada)",
      code: "POST /v1/messages\n{\n  \"model\": \"nombre-del-modelo\",\n  \"max_tokens\": 500,\n  \"messages\": [\n    { \"role\": \"user\", \"content\": \"Resume este texto…\" }\n  ]\n}",
    },
    technicalExplanation:
      "Las APIs de LLM suelen ser HTTP/JSON, autenticadas con claves, con parámetros como modelo, mensajes, [[temperature|temperatura]], límite de tokens y definiciones de herramientas. Ofrecen streaming de tokens, [[structured-output|salidas estructuradas]], procesamiento por lotes y caching de prompts. Aspectos operativos: límites de uso (*rate limits*), reintentos con backoff, manejo de errores, costos por tokens de entrada y salida, y protección de claves.",
    whyItMatters: "Es la puerta de entrada práctica a la IA para cualquier desarrollador.",
    useCases: ["Integrar LLMs en aplicaciones", "Automatización", "Prototipos"],
    relatedTerms: ["ai-engineering", "function-calling", "model-context-protocol", "inference"],
    nextTerms: ["function-calling", "ai-engineering"],
    tags: ["api", "integración", "desarrolladores", "endpoint"],
  },
  {
    slug: "mlops",
    name: "MLOps",
    acronym: "MLOps",
    aliases: ["Machine Learning Operations", "Operaciones de ML", "LLMOps"],
    category: "mlops",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "Las prácticas para desplegar, monitorear y mantener modelos de machine learning en producción de forma confiable.",
    simpleExplanation:
      "Entrenar un modelo en una laptop es una cosa; que funcione bien durante años para millones de usuarios es otra. MLOps aplica al machine learning la disciplina del desarrollo de software moderno: versiones, pruebas automáticas, despliegues controlados y monitoreo.",
    technicalExplanation:
      "Componentes: versionado de datos y modelos, seguimiento de experimentos, pipelines reproducibles de entrenamiento, registro de modelos, CI/CD, [[model-deployment|despliegue]] (canary, A/B), monitoreo de calidad y [[model-drift|drift]], y reentrenamiento. En sistemas con LLMs (a veces llamado LLMOps) el foco se desplaza a versionar prompts, [[evaluation|evals]] continuas, trazas de conversaciones y control de costos.",
    whyItMatters: "La mayoría de los modelos que fallan en producción fallan por problemas operativos, no de algoritmo.",
    useCases: ["Modelos en producción", "Reentrenamiento periódico", "Auditoría de modelos"],
    prerequisites: ["model", "training"],
    relatedTerms: ["model-deployment", "model-drift", "evaluation", "ai-engineering"],
    nextTerms: ["model-deployment", "model-drift"],
    tags: ["operaciones", "producción", "llmops", "devops"],
  },
  {
    slug: "model-deployment",
    name: "Model Deployment",
    spanishName: "Despliegue de modelos",
    aliases: ["Despliegue", "Despliegue de modelos", "Deployment", "Poner en producción"],
    category: "mlops",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "El proceso de poner un modelo a disposición de usuarios o sistemas reales para que haga inferencias en producción.",
    simpleExplanation:
      "Es el paso de «funciona en mi computadora» a «funciona para todos». Implica decidir dónde se ejecuta el modelo (nube, servidor propio, dispositivo), cómo se accede a él y cómo se actualiza sin romper nada.",
    technicalExplanation:
      "Modalidades: en línea (API de baja latencia), por lotes (procesar grandes volúmenes periódicamente), en streaming y en el dispositivo (*edge*). Estrategias de lanzamiento: *shadow* (el modelo nuevo corre en paralelo sin afectar usuarios), *canary* (un porcentaje pequeño de tráfico) y pruebas A/B. Requiere contenedores, [[inference-server|servidores de inferencia]], autoescalado y planes de reversión.",
    whyItMatters: "Un modelo solo genera valor cuando está desplegado y funcionando de forma confiable.",
    useCases: ["APIs de predicción", "Modelos en apps móviles", "Procesamiento batch"],
    prerequisites: ["mlops", "inference"],
    relatedTerms: ["mlops", "inference-server", "model-drift", "latency"],
    nextTerms: ["model-drift"],
    tags: ["producción", "desplegar", "canary"],
  },
  {
    slug: "model-drift",
    name: "Model Drift",
    spanishName: "Deriva del modelo",
    aliases: ["Drift", "Data drift", "Concept drift", "Deriva de datos", "Deriva del modelo", "Distribution shift"],
    category: "mlops",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "La degradación del rendimiento de un modelo en producción porque los datos o el mundo cambiaron respecto a su entrenamiento.",
    simpleExplanation:
      "Un modelo que predice compras entrenado antes de una pandemia puede fallar después: el comportamiento de la gente cambió. El modelo no «se rompió»; el mundo se movió. A eso se le llama drift.",
    technicalExplanation:
      "**Data drift**: cambia la distribución de las entradas p(x). **Concept drift**: cambia la relación entre entradas y salidas p(y|x). Se detecta comparando distribuciones (pruebas estadísticas, PSI) y monitoreando métricas de negocio y de calidad cuando hay etiquetas. Se corrige reentrenando, recalibrando o ajustando umbrales. En LLMs, el mundo cambia pero el conocimiento del modelo queda congelado en su fecha de corte, una razón más para usar [[rag]].",
    whyItMatters: "Explica por qué un modelo que funcionaba bien puede empeorar silenciosamente con el tiempo.",
    useCases: ["Monitoreo de modelos", "Detección de fraude", "Pronóstico de demanda"],
    prerequisites: ["generalization", "mlops"],
    relatedTerms: ["mlops", "generalization", "evaluation", "model-deployment"],
    nextTerms: ["evaluation"],
    tags: ["deriva", "drift", "monitoreo", "degradación"],
  },
];
