import type { TermInput } from "@/types/glossary";

export const mathTerms: TermInput[] = [
  {
    slug: "scalar",
    name: "Escalar",
    aliases: ["Scalar", "Número escalar"],
    category: "math",
    difficulty: "beginner",
    type: "mathematics",
    shortDefinition: "Un solo número, como 3, −0.5 o 1,024.",
    simpleExplanation:
      "Es el objeto matemático más simple: un número suelto. La [[learning-rate]], la [[temperature|temperatura]] o el valor de la [[loss-function|pérdida]] son escalares. Se llaman así porque «escalan» (multiplican) a otros objetos como [[vector|vectores]].",
    technicalExplanation:
      "Un escalar es un elemento de un campo (normalmente ℝ). En la jerarquía de datos de deep learning, es un [[tensor]] de orden 0; un vector es de orden 1 y una [[matrix|matriz]], de orden 2.",
    whyItMatters: "Es el punto de partida del vocabulario matemático de la IA.",
    useCases: ["Hiperparámetros", "Valores de pérdida", "Puntuaciones"],
    relatedTerms: ["vector", "matrix", "tensor"],
    nextTerms: ["vector"],
    tags: ["número"],
  },
  {
    slug: "vector",
    name: "Vector",
    aliases: ["Vectores", "Arreglo de números"],
    category: "math",
    secondaryCategories: ["vector-search", "fundamentals"],
    difficulty: "beginner",
    type: "mathematics",
    shortDefinition: "Una lista ordenada de números que puede representar un punto o una dirección en un espacio de varias dimensiones.",
    simpleExplanation:
      "Una ubicación en un mapa se describe con dos números: latitud y longitud. Eso es un vector de 2 dimensiones. En IA se usan vectores con cientos o miles de números para describir cosas mucho más complejas, como el significado de una frase.\n\nCasi todo en IA termina convertido en vectores: palabras, imágenes, usuarios, productos.",
    example: {
      code: "Punto en un mapa:        [19.43, -99.13]\nEmbedding de una frase:  [0.021, -0.87, 0.31, …]  (1,024 números)",
    },
    technicalExplanation:
      "Un vector v ∈ ℝⁿ tiene n componentes. Operaciones clave: suma, multiplicación por escalar, [[dot-product|producto punto]] y norma (su longitud, ‖v‖ = √Σvᵢ²). La similitud entre vectores se mide con [[cosine-similarity|similitud coseno]] o distancia euclidiana. Los [[embeddings]] son vectores densos aprendidos.",
    whyItMatters: "Son el lenguaje común con el que los modelos representan cualquier tipo de información.",
    useCases: ["Embeddings", "Features de un ejemplo", "Búsqueda vectorial"],
    prerequisites: ["scalar"],
    relatedTerms: ["embeddings", "matrix", "dot-product", "cosine-similarity", "vector-database"],
    nextTerms: ["dot-product", "matrix", "embeddings"],
    tags: ["lista de números", "dimensiones", "coordenadas"],
  },
  {
    slug: "matrix",
    name: "Matriz",
    aliases: ["Matrix", "Matrices", "Multiplicación de matrices", "Matmul"],
    category: "math",
    difficulty: "beginner",
    type: "mathematics",
    shortDefinition: "Una tabla rectangular de números organizada en filas y columnas.",
    simpleExplanation:
      "Una hoja de cálculo es una matriz. En IA, los [[weights|pesos]] de una capa de red neuronal se guardan en matrices, y la operación más común de toda la IA es multiplicar matrices: una GPU hace billones de estas multiplicaciones por segundo.",
    technicalExplanation:
      "Una matriz A ∈ ℝᵐˣⁿ tiene m filas y n columnas. El producto Ax transforma un vector de n dimensiones en uno de m: es una transformación lineal. Una capa densa calcula y = Wx + b. El producto de matrices (C = AB) requiere que coincidan las dimensiones internas y su costo, del orden de m·n·p operaciones, domina el cómputo de los modelos.",
    whyItMatters: "Entender matrices es entender dónde se guarda el conocimiento de un modelo y en qué gasta su cómputo.",
    useCases: ["Pesos de capas", "Attention (QKᵀ)", "LoRA", "Imágenes (matrices de píxeles)"],
    prerequisites: ["vector"],
    relatedTerms: ["vector", "tensor", "linear-algebra", "weights"],
    nextTerms: ["tensor", "linear-algebra"],
    tags: ["tabla", "filas", "columnas", "matmul"],
  },
  {
    slug: "tensor",
    name: "Tensor",
    aliases: ["Tensores", "Arreglo multidimensional"],
    category: "math",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Un arreglo de números con cualquier cantidad de dimensiones; generaliza escalares, vectores y matrices.",
    simpleExplanation:
      "Un escalar es un punto, un vector es una fila, una matriz es una tabla. Un tensor puede tener más dimensiones: una foto a color es un tensor de 3 dimensiones (alto × ancho × 3 colores); un lote de 32 fotos es uno de 4 dimensiones.\n\nPor eso el framework se llama TensorFlow y los chips tienen «Tensor Cores»: todo en deep learning son tensores.",
    technicalExplanation:
      "En deep learning, «tensor» suele significar arreglo multidimensional con una forma (*shape*), un tipo de dato (float32, bfloat16, int8) y un dispositivo (CPU/GPU). En un Transformer, las activaciones tienen forma [batch, secuencia, dimensión]. En matemáticas, el término tiene una definición más estricta ligada a transformaciones multilineales.",
    whyItMatters: "Es la estructura de datos fundamental de todos los frameworks de deep learning.",
    useCases: ["Imágenes", "Lotes de datos", "Activaciones de redes"],
    prerequisites: ["matrix"],
    relatedTerms: ["matrix", "vector", "scalar", "tensor-core"],
    nextTerms: ["linear-algebra"],
    tags: ["shape", "dimensiones", "arreglo"],
  },
  {
    slug: "linear-algebra",
    name: "Álgebra lineal",
    aliases: ["Linear Algebra", "Álgebra matricial"],
    category: "math",
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "La rama de las matemáticas que estudia vectores, matrices y transformaciones lineales; es el lenguaje de cálculo de la IA.",
    simpleExplanation:
      "Si la IA fuera un idioma, el álgebra lineal sería su gramática. Representar datos como vectores, transformarlos con matrices y medir similitudes: casi todo lo que hace una red neuronal se describe con álgebra lineal.",
    technicalExplanation:
      "Conceptos esenciales para IA: espacios vectoriales, producto punto y normas, multiplicación de matrices, rango (base de [[lora|LoRA]]), valores y vectores propios, descomposición en valores singulares (SVD) y proyecciones. Las GPUs son, esencialmente, máquinas de álgebra lineal.",
    whyItMatters: "Es el prerrequisito matemático más importante para entender cómo funcionan los modelos por dentro.",
    useCases: ["Redes neuronales", "Reducción de dimensionalidad", "Embeddings", "LoRA"],
    prerequisites: ["vector", "matrix"],
    relatedTerms: ["matrix", "vector", "dot-product", "tensor"],
    nextTerms: ["dot-product", "derivative"],
    tags: ["matemáticas", "vectores", "matrices"],
  },
  {
    slug: "dot-product",
    name: "Producto punto",
    aliases: ["Dot Product", "Producto escalar", "Producto interno", "Inner product"],
    category: "math",
    secondaryCategories: ["vector-search"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una operación entre dos vectores que multiplica sus componentes una a una y suma los resultados; mide qué tanto «apuntan en la misma dirección».",
    simpleExplanation:
      "Tomas dos listas de números, multiplicas el primero con el primero, el segundo con el segundo, y así sucesivamente, y sumas todo. El resultado es grande si los vectores se parecen y pequeño (o negativo) si son distintos.\n\nEs la operación detrás de [[attention]], de las neuronas artificiales y de la búsqueda por similitud.",
    example: {
      code: "a = [1, 2, 3]\nb = [4, 5, 6]\n\na · b = 1×4 + 2×5 + 3×6 = 32",
    },
    technicalExplanation:
      "a · b = Σᵢ aᵢbᵢ = ‖a‖‖b‖cos θ, donde θ es el ángulo entre los vectores. Si están normalizados (longitud 1), el producto punto es igual a la [[cosine-similarity|similitud coseno]]. En attention, QKᵀ calcula el producto punto entre todas las queries y keys a la vez.",
    math: {
      formula: "a · b = Σᵢ aᵢ · bᵢ = ‖a‖ · ‖b‖ · cos θ",
      symbols: [
        { symbol: "aᵢ, bᵢ", meaning: "Componentes i de cada vector" },
        { symbol: "‖a‖", meaning: "Longitud del vector a" },
        { symbol: "θ", meaning: "Ángulo entre los dos vectores" },
      ],
    },
    whyItMatters: "Es probablemente la operación más repetida en toda la IA moderna.",
    useCases: ["Attention", "Neuronas artificiales", "Búsqueda vectorial"],
    prerequisites: ["vector"],
    relatedTerms: ["cosine-similarity", "vector", "attention", "artificial-neuron"],
    nextTerms: ["cosine-similarity", "attention"],
    tags: ["producto escalar", "similitud"],
  },
  {
    slug: "cosine-similarity",
    name: "Cosine Similarity",
    spanishName: "Similitud coseno",
    aliases: ["Similitud coseno", "Similitud del coseno", "Distancia coseno", "Cosine distance"],
    category: "math",
    secondaryCategories: ["vector-search", "rag"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una medida de qué tan parecidos son dos vectores según el ángulo entre ellos, sin importar su longitud.",
    simpleExplanation:
      "Imagina dos flechas saliendo del mismo punto. Si apuntan en la misma dirección, son muy similares (valor cercano a 1). Si forman un ángulo recto, no tienen relación (0). Si apuntan en direcciones opuestas, son contrarias (−1).\n\nEn búsqueda semántica, se usa para saber qué documentos «significan» algo parecido a tu pregunta.",
    technicalExplanation:
      "Se calcula dividiendo el [[dot-product|producto punto]] entre el producto de las normas. Al ignorar la magnitud, compara solo la dirección, lo que resulta útil para [[embeddings]] donde la longitud del vector puede depender de factores irrelevantes. La distancia coseno se define como 1 − similitud. Muchas bases vectoriales normalizan los vectores y usan producto punto, que entonces equivale a coseno.",
    math: {
      formula: "cos(θ) = (a · b) / (‖a‖ · ‖b‖)",
      symbols: [
        { symbol: "a · b", meaning: "Producto punto de los vectores" },
        { symbol: "‖a‖, ‖b‖", meaning: "Longitudes (normas) de cada vector" },
        { symbol: "cos(θ)", meaning: "Resultado entre −1 (opuestos) y 1 (idénticos en dirección)" },
      ],
    },
    whyItMatters: "Es la regla de comparación estándar en búsqueda semántica y RAG.",
    useCases: ["Búsqueda semántica", "Recomendaciones", "Detección de duplicados", "Clustering"],
    prerequisites: ["dot-product", "vector"],
    relatedTerms: ["dot-product", "embeddings", "vector-search", "semantic-search"],
    nextTerms: ["vector-search", "semantic-search"],
    tags: ["similitud", "ángulo", "coseno"],
  },
  {
    slug: "probability",
    name: "Probabilidad",
    aliases: ["Probability", "Probabilidades"],
    category: "math",
    difficulty: "beginner",
    type: "mathematics",
    shortDefinition: "Un número entre 0 y 1 que expresa qué tan probable es que ocurra algo.",
    simpleExplanation:
      "0 significa imposible, 1 significa seguro, 0.5 significa tan probable como no. Los modelos de IA casi nunca dan respuestas absolutas: dan probabilidades. Un LLM, por ejemplo, calcula la probabilidad de cada posible siguiente [[token]].",
    technicalExplanation:
      "Conceptos clave para IA: probabilidad condicional P(A|B), regla de Bayes, independencia, esperanza y varianza. Los modelos de lenguaje son modelos de probabilidad condicional sobre secuencias. La salida de una [[softmax]] se interpreta como una [[probability-distribution|distribución de probabilidad]], aunque no siempre está bien calibrada.",
    whyItMatters: "La IA moderna es, en gran medida, estadística a gran escala: todo se expresa en probabilidades.",
    useCases: ["Clasificación", "Generación de texto", "Evaluación de incertidumbre"],
    relatedTerms: ["probability-distribution", "softmax", "sampling", "next-token-prediction"],
    nextTerms: ["probability-distribution", "softmax"],
    tags: ["azar", "incertidumbre", "bayes"],
  },
  {
    slug: "probability-distribution",
    name: "Distribución de probabilidad",
    aliases: ["Probability distribution", "Distribution", "Distribución", "Gaussiana", "Distribución normal"],
    category: "math",
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una descripción de todos los resultados posibles de algo incierto y de qué tan probable es cada uno.",
    simpleExplanation:
      "Cuando lanzas un dado, cada número del 1 al 6 tiene probabilidad 1/6: esa es su distribución. Cuando un LLM va a escribir la siguiente palabra, calcula una distribución sobre todo su vocabulario: «París» 91%, «una» 3%, etc. Generar texto es elegir de esa distribución.",
    technicalExplanation:
      "Puede ser discreta (sobre un conjunto finito, como el vocabulario) o continua (como la distribución normal o gaussiana, usada en el ruido de los [[diffusion-model|modelos de difusión]]). Los modelos generativos aprenden a aproximar la distribución de los datos. Medidas para comparar distribuciones: [[cross-entropy|entropía cruzada]] y divergencia KL.",
    whyItMatters: "Los modelos generativos son, en el fondo, aproximaciones de distribuciones de probabilidad.",
    useCases: ["Sampling", "Modelos generativos", "Detección de anomalías"],
    prerequisites: ["probability"],
    relatedTerms: ["probability", "softmax", "sampling", "cross-entropy"],
    nextTerms: ["softmax", "cross-entropy"],
    tags: ["distribución", "gaussiana", "normal"],
  },
  {
    slug: "softmax",
    name: "Softmax",
    aliases: ["Función softmax", "Logits"],
    category: "math",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una función que convierte una lista de números cualesquiera en probabilidades positivas que suman 1.",
    simpleExplanation:
      "La red produce puntuaciones sin forma definida: 2.0, 1.0, 0.1. Softmax las transforma en probabilidades: 66%, 24%, 10%. La puntuación más alta obtiene la mayor probabilidad, pero las demás no desaparecen.",
    example: {
      code: "logits:   [2.0,  1.0,  0.1]\nsoftmax:  [0.66, 0.24, 0.10]   → suman 1",
    },
    technicalExplanation:
      "softmax(z)ᵢ = exp(zᵢ) / Σⱼ exp(zⱼ). La exponencial asegura valores positivos y exagera las diferencias. Se usa en la [[output-layer|capa de salida]] de clasificadores y LLMs, y dentro de [[attention]] para convertir similitudes en pesos. Se implementa restando el máximo de los logits para estabilidad numérica. La [[temperature|temperatura]] divide los logits antes de aplicarla.",
    math: {
      formula: "softmax(z)ᵢ = exp(zᵢ) / Σⱼ exp(zⱼ)",
      symbols: [
        { symbol: "zᵢ", meaning: "Logit (puntuación) de la opción i" },
        { symbol: "exp", meaning: "Función exponencial: siempre positiva" },
        { symbol: "Σⱼ exp(zⱼ)", meaning: "Suma de todas las exponenciales: normaliza para que el total sea 1" },
      ],
    },
    whyItMatters: "Es el puente entre las puntuaciones internas de un modelo y las probabilidades que usamos para decidir.",
    useCases: ["Clasificación", "Predicción del siguiente token", "Attention"],
    prerequisites: ["probability"],
    relatedTerms: ["cross-entropy", "temperature", "attention", "output-layer"],
    nextTerms: ["cross-entropy", "temperature"],
    tags: ["logits", "normalizar", "probabilidades"],
  },
  {
    slug: "cross-entropy",
    name: "Cross-Entropy",
    spanishName: "Entropía cruzada",
    aliases: ["Entropía cruzada", "Cross entropy loss", "Log loss", "Pérdida logarítmica", "Divergencia KL"],
    category: "math",
    secondaryCategories: ["machine-learning"],
    difficulty: "advanced",
    type: "mathematics",
    shortDefinition: "La función de pérdida estándar para clasificación y modelos de lenguaje: penaliza al modelo cuando asigna baja probabilidad a la respuesta correcta.",
    simpleExplanation:
      "Si la respuesta correcta es «gato» y el modelo le dio 90% de probabilidad, la penalización es pequeña. Si le dio 1%, la penalización es enorme. La entropía cruzada premia al modelo por estar seguro de lo correcto y lo castiga duramente por estar seguro de lo incorrecto.",
    technicalExplanation:
      "Para una etiqueta correcta y, la pérdida es −log p(y). Entre dos distribuciones, H(p, q) = −Σ p(x) log q(x), que equivale a la entropía de p más la divergencia KL(p‖q). Minimizarla equivale a maximizar la verosimilitud de los datos. Es la pérdida del [[pretraining|preentrenamiento]] de los LLMs, promediada sobre todos los tokens; su exponencial es la [[perplexity|perplejidad]].",
    math: {
      formula: "L = −log p(y_correcto)",
      caption: "Entropía cruzada para un solo ejemplo con etiqueta correcta.",
      symbols: [
        { symbol: "p(y_correcto)", meaning: "Probabilidad que el modelo asignó a la respuesta correcta" },
        { symbol: "−log", meaning: "Convierte probabilidades altas en pérdidas pequeñas y bajas en pérdidas grandes" },
      ],
      explanation: "p = 0.9 → L ≈ 0.105. p = 0.01 → L ≈ 4.6. Equivocarse con seguridad cuesta mucho.",
    },
    whyItMatters: "Es la señal de aprendizaje con la que se entrenan prácticamente todos los clasificadores y modelos de lenguaje.",
    useCases: ["Clasificación", "Preentrenamiento de LLMs", "Fine-tuning"],
    prerequisites: ["softmax", "probability-distribution", "loss-function"],
    relatedTerms: ["loss-function", "softmax", "perplexity", "probability-distribution"],
    nextTerms: ["perplexity", "gradient-descent"],
    tags: ["pérdida", "log loss", "kl"],
  },
  {
    slug: "derivative",
    name: "Derivada",
    aliases: ["Derivative", "Derivadas", "Regla de la cadena", "Chain rule"],
    category: "math",
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una medida de qué tan rápido cambia el resultado de una función cuando cambias un poco su entrada.",
    simpleExplanation:
      "Si vas en auto, tu velocidad es la derivada de tu posición: dice cuánto cambia tu ubicación por cada segundo. En IA, la derivada dice cuánto cambiaría el error si movieras un poquito un parámetro. Eso es exactamente lo que se necesita para saber hacia dónde ajustarlo.",
    technicalExplanation:
      "f′(x) = lim_{h→0} [f(x+h) − f(x)] / h. Para funciones de varias variables se usan derivadas parciales ∂f/∂xᵢ, que forman el [[gradient|gradiente]]. La **regla de la cadena** permite derivar composiciones de funciones —como las capas de una red— y es la base de [[backpropagation]].",
    whyItMatters: "Sin derivadas no se podría entrenar ninguna red neuronal moderna.",
    useCases: ["Backpropagation", "Optimización", "Análisis de sensibilidad"],
    relatedTerms: ["gradient", "backpropagation", "gradient-descent", "optimization"],
    nextTerms: ["gradient"],
    tags: ["cálculo", "cambio", "pendiente", "regla de la cadena"],
  },
  {
    slug: "gradient",
    name: "Gradiente",
    aliases: ["Gradient", "Gradientes", "Vanishing gradient", "Gradiente que se desvanece"],
    category: "math",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Un vector que indica, para cada parámetro, en qué dirección y con qué intensidad cambia una función; apunta hacia donde la función crece más rápido.",
    simpleExplanation:
      "Si estás en una colina, el gradiente es una flecha que apunta hacia la subida más empinada. Para entrenar un modelo queremos **bajar** el error, así que caminamos en la dirección contraria al gradiente. Eso es el [[gradient-descent|descenso de gradiente]].",
    technicalExplanation:
      "∇f(θ) = (∂f/∂θ₁, …, ∂f/∂θₙ). En un modelo con miles de millones de parámetros, el gradiente tiene miles de millones de componentes, calculados eficientemente con [[backpropagation]]. Problemas típicos: gradientes que se desvanecen (demasiado pequeños para aprender en capas profundas) o que explotan (demasiado grandes); se mitigan con [[residual-connection|conexiones residuales]], normalización y *gradient clipping*.",
    whyItMatters: "Es la señal que le dice a cada parámetro cómo cambiar durante el entrenamiento.",
    useCases: ["Entrenamiento", "Ataques adversarios", "Métodos de atribución"],
    prerequisites: ["derivative", "vector"],
    relatedTerms: ["gradient-descent", "backpropagation", "derivative", "optimization"],
    nextTerms: ["gradient-descent", "backpropagation"],
    tags: ["pendiente", "dirección", "vector de derivadas"],
  },
  {
    slug: "optimization",
    name: "Optimización",
    aliases: ["Optimization", "Optimizador", "Optimizer", "Minimización"],
    category: "math",
    secondaryCategories: ["machine-learning"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Encontrar los valores que minimizan (o maximizan) una función; en IA, los parámetros que minimizan la pérdida.",
    simpleExplanation:
      "Entrenar un modelo es un problema de optimización: de todas las configuraciones posibles de sus parámetros, encontrar una que cometa pocos errores. Es como buscar el punto más bajo de un paisaje montañoso gigantesco con los ojos vendados.",
    technicalExplanation:
      "En deep learning, el problema es no convexo y de altísima dimensión, y se resuelve con métodos de primer orden basados en el [[gradient|gradiente]]: SGD, SGD con momento, Adam/AdamW. Elementos clave: [[learning-rate]] y su calendario, tamaño de [[batch]], regularización e inicialización. Sorprendentemente, en redes grandes estos métodos simples encuentran soluciones que generalizan bien.",
    whyItMatters: "Es el motor matemático del aprendizaje.",
    useCases: ["Entrenamiento de modelos", "Ajuste de hiperparámetros"],
    prerequisites: ["loss-function", "gradient"],
    relatedTerms: ["gradient-descent", "loss-function", "learning-rate", "gradient"],
    nextTerms: ["gradient-descent"],
    tags: ["minimizar", "adam", "optimizador"],
  },
];
