import type { TermInput } from "@/types/glossary";

export const neuralNetworkTerms: TermInput[] = [
  {
    slug: "neural-network",
    name: "Neural Network",
    spanishName: "Red neuronal",
    aliases: ["Red neuronal", "Red neuronal artificial", "ANN", "NN"],
    category: "deep-learning",
    secondaryCategories: ["fundamentals"],
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition:
      "Un modelo formado por capas de unidades simples conectadas entre sí, que aprende ajustando la fuerza de esas conexiones.",
    simpleExplanation:
      "Una red neuronal es un conjunto de pequeñas calculadoras —[[artificial-neuron|neuronas]]— organizadas en [[layer|capas]]. Cada neurona recibe números, los combina y pasa el resultado a la siguiente capa.\n\nNinguna neurona «sabe» nada por sí sola. El conocimiento está repartido en millones de conexiones con distintos [[weights|pesos]]. Entrenar la red es encontrar los pesos correctos.",
    analogy:
      "Piensa en una cadena de oficinas: la primera recibe documentos crudos, cada oficina resume y pasa lo importante a la siguiente, y la última toma la decisión. Nadie ve el panorama completo, pero juntas resuelven el problema.",
    diagram: { kind: "custom", id: "neural-network", title: "Una red neuronal pequeña", caption: "La información fluye de izquierda a derecha: entrada → capas ocultas → salida." },
    inThirtySeconds: [
      "La capa de entrada recibe números (píxeles, palabras codificadas…).",
      "Cada neurona multiplica sus entradas por pesos y las suma.",
      "Una función de activación decide cuánto «se activa».",
      "Las capas ocultas construyen representaciones cada vez más abstractas.",
      "La capa de salida produce la predicción.",
    ],
    technicalExplanation:
      "Una red *feedforward* aplica una secuencia de transformaciones hₗ = σ(Wₗhₗ₋₁ + bₗ), donde Wₗ es la matriz de pesos de la capa l, bₗ el bias y σ una [[activation-function|función de activación]] no lineal. Sin esa no linealidad, apilar capas sería equivalente a una sola transformación lineal.\n\nEl teorema de aproximación universal establece que una red con una sola capa oculta suficientemente ancha puede aproximar cualquier función continua en un dominio acotado, aunque en la práctica las redes **profundas** aprenden de forma mucho más eficiente. Se entrenan con [[backpropagation]] y [[gradient-descent]]. Arquitecturas especializadas incluyen [[cnn|CNNs]] (imágenes), RNNs (secuencias) y [[transformer|Transformers]].",
    commonMistakes: [
      "Las redes neuronales se inspiran vagamente en el cerebro, pero no lo simulan. Una neurona artificial es una operación matemática muy simple comparada con una neurona biológica.",
    ],
    whyItMatters: "Son el bloque de construcción de todo el deep learning moderno, incluidos los LLMs.",
    useCases: ["Reconocimiento de imágenes", "Procesamiento de lenguaje", "Reconocimiento de voz", "Predicción de series de tiempo"],
    prerequisites: ["machine-learning", "weights"],
    relatedTerms: ["artificial-neuron", "layer", "activation-function", "backpropagation", "deep-learning"],
    nextTerms: ["artificial-neuron", "backpropagation", "transformer"],
    tags: ["red neuronal", "capas", "neuronas", "perceptrón"],
  },
  {
    slug: "artificial-neuron",
    name: "Neurona artificial",
    aliases: ["Artificial Neuron", "Perceptrón", "Perceptron", "Nodo", "Unidad"],
    category: "deep-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La unidad básica de una red neuronal: combina varias entradas con pesos, suma un bias y aplica una función de activación.",
    simpleExplanation:
      "Una neurona artificial hace algo muy simple: recibe varios números, multiplica cada uno por su importancia ([[weights|peso]]), los suma y decide cuánto «encenderse».\n\nPor ejemplo, una neurona que decide si vas a ir a la playa podría considerar el clima, la distancia y si tienes tiempo, dando más peso al clima.",
    technicalExplanation:
      "Calcula y = σ(Σᵢ wᵢxᵢ + b) = σ(w·x + b). El perceptrón original (Rosenblatt, 1958) usaba una función escalón; las redes modernas usan activaciones diferenciables como ReLU o GELU para poder entrenar con [[gradient-descent]].",
    math: {
      formula: "y = σ(w · x + b)",
      symbols: [
        { symbol: "x", meaning: "Vector de entradas" },
        { symbol: "w", meaning: "Vector de pesos (uno por entrada)" },
        { symbol: "w · x", meaning: "Producto punto: suma de cada entrada por su peso" },
        { symbol: "b", meaning: "Bias: desplazamiento fijo" },
        { symbol: "σ", meaning: "Función de activación" },
      ],
    },
    whyItMatters: "Entender una neurona es entender la operación que se repite miles de millones de veces dentro de un LLM.",
    useCases: ["Bloque básico de cualquier red neuronal"],
    prerequisites: ["weights", "bias"],
    relatedTerms: ["neural-network", "activation-function", "dot-product", "layer"],
    nextTerms: ["activation-function", "layer"],
    tags: ["perceptrón", "nodo", "unidad"],
  },
  {
    slug: "layer",
    name: "Layer",
    spanishName: "Capa",
    aliases: ["Capa", "Capa neuronal"],
    category: "deep-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Un grupo de neuronas que procesa la información al mismo nivel dentro de una red neuronal.",
    simpleExplanation:
      "Las redes se organizan en capas, como pisos de un edificio. La información entra por la [[input-layer|capa de entrada]], pasa por [[hidden-layer|capas ocultas]] y sale por la [[output-layer|capa de salida]].\n\nCada capa transforma lo que recibe en una representación un poco más útil para la tarea.",
    technicalExplanation:
      "Existen muchos tipos de capa: densas (fully connected), convolucionales ([[convolution]]), de [[attention]], de normalización ([[layer-normalization]]) y de embedding. En un [[transformer]], un «bloque» combina una capa de attention y una [[feedforward-network|red feedforward]] con [[residual-connection|conexiones residuales]]. La **profundidad** es el número de capas; el **ancho**, el número de neuronas por capa.",
    whyItMatters: "El número y tipo de capas define la arquitectura y la capacidad de un modelo.",
    useCases: ["Diseño de arquitecturas", "Análisis de modelos"],
    prerequisites: ["artificial-neuron"],
    relatedTerms: ["input-layer", "hidden-layer", "output-layer", "neural-network"],
    nextTerms: ["hidden-layer", "activation-function"],
    tags: ["capa", "profundidad"],
  },
  {
    slug: "input-layer",
    name: "Input Layer",
    spanishName: "Capa de entrada",
    aliases: ["Capa de entrada"],
    category: "deep-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La primera capa de una red neuronal, que recibe los datos en forma numérica.",
    simpleExplanation:
      "Es la puerta de entrada. No hace cálculos complejos: solo recibe los números que representan los datos. En una imagen de 28×28 píxeles serían 784 valores; en un LLM, los [[embeddings]] de los [[token|tokens]].",
    technicalExplanation:
      "Su dimensión coincide con la de la entrada. En modelos de lenguaje, la «entrada» es una capa de embedding que convierte IDs de tokens en vectores densos, a veces sumados con [[positional-encoding|codificación posicional]].",
    whyItMatters: "Define cómo se representan los datos para que la red pueda procesarlos.",
    useCases: ["Recibir píxeles, audio, tokens o features tabulares"],
    prerequisites: ["layer"],
    relatedTerms: ["hidden-layer", "output-layer", "embeddings", "feature"],
    nextTerms: ["hidden-layer"],
    tags: ["entrada"],
  },
  {
    slug: "hidden-layer",
    name: "Hidden Layer",
    spanishName: "Capa oculta",
    aliases: ["Capa oculta", "Capas intermedias"],
    category: "deep-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Cualquier capa entre la entrada y la salida, donde la red construye sus representaciones internas.",
    simpleExplanation:
      "Se llaman «ocultas» porque no vemos directamente lo que producen: son pasos intermedios. Ahí es donde ocurre el aprendizaje interesante. Una red con muchas capas ocultas es una red profunda: [[deep-learning]].",
    technicalExplanation:
      "Las activaciones de las capas ocultas forman el espacio latente del modelo ([[latent-space]]). Estudiar qué representan es el objetivo de la [[interpretability|interpretabilidad]]. Más capas aumentan la capacidad, pero también la dificultad de entrenamiento (gradientes que se desvanecen), algo que mitigan las [[residual-connection|conexiones residuales]].",
    whyItMatters: "Es donde el modelo «piensa»: donde se forman los conceptos que usa para decidir.",
    useCases: ["Extracción de características", "Transfer learning"],
    prerequisites: ["layer"],
    relatedTerms: ["input-layer", "output-layer", "latent-space", "deep-learning"],
    nextTerms: ["output-layer", "latent-space"],
    tags: ["oculta", "intermedia"],
  },
  {
    slug: "output-layer",
    name: "Output Layer",
    spanishName: "Capa de salida",
    aliases: ["Capa de salida"],
    category: "deep-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La última capa de una red neuronal, que produce la predicción final.",
    simpleExplanation:
      "Es la capa que da la respuesta. En un clasificador de animales podría tener una neurona por animal, cada una con la probabilidad de que la foto sea de ese animal. En un LLM, tiene una salida por cada [[token]] posible del vocabulario.",
    technicalExplanation:
      "Su forma depende de la tarea: una sola neurona lineal para regresión, [[softmax]] sobre k clases para clasificación, o softmax sobre todo el vocabulario (decenas de miles de tokens o más) para modelos de lenguaje. Los valores previos a la softmax se llaman **logits**.",
    whyItMatters: "Traduce las representaciones internas en algo útil: una clase, un número o el siguiente token.",
    useCases: ["Clasificación", "Regresión", "Predicción del siguiente token"],
    prerequisites: ["layer"],
    relatedTerms: ["softmax", "hidden-layer", "next-token-prediction"],
    nextTerms: ["softmax", "loss-function"],
    tags: ["salida", "logits"],
  },
  {
    slug: "activation-function",
    name: "Activation Function",
    spanishName: "Función de activación",
    aliases: ["Función de activación", "ReLU", "GELU", "Sigmoide", "Sigmoid", "Tanh", "SwiGLU"],
    category: "deep-learning",
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una función no lineal que se aplica a la salida de cada neurona y permite a la red aprender relaciones complejas.",
    simpleExplanation:
      "Sin funciones de activación, una red neuronal —por más capas que tenga— solo podría dibujar líneas rectas. La activación introduce «curvas», lo que permite modelar relaciones complicadas del mundo real.\n\nLa más común, **ReLU**, es sorprendentemente simple: si el número es negativo, lo convierte en cero; si es positivo, lo deja igual.",
    technicalExplanation:
      "Funciones frecuentes: ReLU(x) = max(0, x); sigmoide σ(x) = 1/(1+e⁻ˣ), que comprime valores a (0,1); tanh, que comprime a (−1,1); GELU, una versión suave de ReLU usada en BERT y GPT; y SwiGLU, una variante con compuertas usada en muchos LLMs actuales. Deben ser diferenciables (al menos casi en todas partes) para permitir [[backpropagation]]. Las sigmoides saturadas causan gradientes que se desvanecen, uno de los motivos por los que ReLU se volvió dominante.",
    whyItMatters: "Es lo que da a las redes neuronales su poder expresivo.",
    useCases: ["Todas las capas ocultas de redes neuronales", "Compuertas en LSTMs y SwiGLU"],
    prerequisites: ["artificial-neuron"],
    relatedTerms: ["artificial-neuron", "neural-network", "softmax", "feedforward-network"],
    nextTerms: ["loss-function", "backpropagation"],
    tags: ["relu", "gelu", "sigmoide", "no linealidad"],
  },
  {
    slug: "loss-function",
    name: "Loss Function",
    spanishName: "Función de pérdida",
    aliases: ["Función de pérdida", "Función de costo", "Cost function", "Objective function", "Loss"],
    category: "machine-learning",
    secondaryCategories: ["math"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una fórmula que mide qué tan equivocadas están las predicciones del modelo; el entrenamiento busca hacerla lo más pequeña posible.",
    simpleExplanation:
      "Es la calificación inversa del modelo: cuanto más alta, peor lo está haciendo. Si el modelo dice «90% gato» y la foto es de un perro, la pérdida es alta. Si dice «95% perro», la pérdida es baja.\n\nTodo el [[training|entrenamiento]] consiste en mover los [[parameters|parámetros]] en la dirección que hace bajar este número.",
    technicalExplanation:
      "Para regresión se usa el error cuadrático medio: MSE = (1/n) Σ (yᵢ − ŷᵢ)². Para clasificación y modelos de lenguaje, la [[cross-entropy]]. La elección de la pérdida define qué considera «error» el modelo y, por tanto, qué optimiza. Suele añadirse un término de [[regularization|regularización]] para penalizar la complejidad.",
    math: {
      formula: "MSE = (1/n) · Σᵢ (yᵢ − ŷᵢ)²",
      caption: "Error cuadrático medio, la pérdida clásica para regresión.",
      symbols: [
        { symbol: "n", meaning: "Número de ejemplos" },
        { symbol: "yᵢ", meaning: "Valor real del ejemplo i" },
        { symbol: "ŷᵢ", meaning: "Predicción del modelo para el ejemplo i" },
        { symbol: "(yᵢ − ŷᵢ)²", meaning: "Error al cuadrado: penaliza más los errores grandes" },
      ],
    },
    whyItMatters: "Es la brújula del entrenamiento: el modelo mejora exactamente en lo que la pérdida mide, ni más ni menos.",
    useCases: ["Entrenamiento de cualquier modelo", "Comparar configuraciones"],
    prerequisites: ["training"],
    relatedTerms: ["cross-entropy", "gradient-descent", "optimization", "training"],
    nextTerms: ["gradient-descent", "cross-entropy"],
    tags: ["pérdida", "costo", "error", "mse"],
  },
  {
    slug: "gradient-descent",
    name: "Gradient Descent",
    spanishName: "Descenso de gradiente",
    aliases: ["Descenso de gradiente", "Descenso del gradiente", "SGD", "Stochastic Gradient Descent", "Adam"],
    category: "machine-learning",
    secondaryCategories: ["math", "deep-learning"],
    difficulty: "advanced",
    type: "mathematics",
    shortDefinition: "Un algoritmo de optimización que ajusta los parámetros de un modelo dando pequeños pasos en la dirección que más reduce el error.",
    simpleExplanation:
      "Imagina que estás en una montaña con niebla y quieres llegar al valle. No ves el camino, pero sí sientes hacia dónde baja el suelo bajo tus pies. Das un paso en esa dirección, vuelves a sentir y repites.\n\nEso es el descenso de gradiente: la «altura» es la [[loss-function|pérdida]], y cada paso ajusta los [[parameters|parámetros]] para reducirla.",
    diagram: { kind: "custom", id: "gradient-descent", title: "Bajando por la curva de pérdida", caption: "Cada punto es un paso: el tamaño del paso depende de la learning rate." },
    technicalExplanation:
      "En cada iteración se calcula el [[gradient|gradiente]] de la pérdida respecto a los parámetros, ∇L(θ), y se actualiza θ en sentido contrario. En la práctica se usa **descenso de gradiente estocástico** (SGD): el gradiente se estima con un [[batch]] pequeño de ejemplos, lo que es mucho más barato y añade ruido útil.\n\nOptimizadores modernos como **Adam** o **AdamW** adaptan el tamaño de paso de cada parámetro usando promedios de gradientes pasados. La [[learning-rate]] controla el tamaño del paso: si es muy grande, el entrenamiento diverge; si es muy pequeña, avanza demasiado lento.",
    math: {
      formula: "θ ← θ − η · ∇θ L(θ)",
      symbols: [
        { symbol: "θ", meaning: "Parámetros del modelo" },
        { symbol: "η", meaning: "Learning rate (tamaño del paso)" },
        { symbol: "∇θ L(θ)", meaning: "Gradiente: dirección en la que la pérdida crece más rápido" },
        { symbol: "−", meaning: "Se resta porque queremos bajar, no subir" },
      ],
      explanation: "El gradiente apunta «cuesta arriba»; restarlo mueve los parámetros cuesta abajo, hacia menor pérdida.",
    },
    commonMistakes: [
      "El descenso de gradiente no garantiza encontrar el mejor mínimo posible. En redes profundas basta con encontrar una región suficientemente buena, y en la práctica suele funcionar muy bien.",
    ],
    whyItMatters: "Es el mecanismo con el que se entrenan prácticamente todas las redes neuronales, desde clasificadores pequeños hasta LLMs.",
    useCases: ["Entrenamiento de redes neuronales", "Regresión logística", "Fine-tuning"],
    prerequisites: ["loss-function", "gradient", "derivative"],
    relatedTerms: ["backpropagation", "learning-rate", "batch", "optimization", "gradient"],
    nextTerms: ["backpropagation", "learning-rate"],
    tags: ["optimización", "sgd", "adam", "montaña"],
    sources: [
      { title: "Adam: A Method for Stochastic Optimization", authors: "Kingma & Ba", year: 2014, url: "https://arxiv.org/abs/1412.6980", kind: "paper" },
    ],
  },
  {
    slug: "learning-rate",
    name: "Learning Rate",
    spanishName: "Tasa de aprendizaje",
    aliases: ["Tasa de aprendizaje", "LR", "Step size"],
    category: "machine-learning",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "Un hiperparámetro que controla qué tan grandes son los ajustes que se hacen a los parámetros en cada paso de entrenamiento.",
    simpleExplanation:
      "Siguiendo la analogía de la montaña: la learning rate es el tamaño de tus pasos. Pasos enormes pueden hacerte saltar el valle y terminar más arriba. Pasos diminutos te llevan al valle, pero tardarás muchísimo.",
    technicalExplanation:
      "Es el η en la regla de [[gradient-descent]]. Suele usarse un **schedule**: un calentamiento (warmup) inicial donde crece gradualmente, seguido de un decaimiento (por ejemplo, coseno). Es probablemente el hiperparámetro más sensible del entrenamiento. En [[fine-tuning]] suelen usarse valores más bajos que en el preentrenamiento para no destruir lo aprendido.",
    whyItMatters: "Una learning rate mal elegida puede arruinar un entrenamiento que por lo demás está bien configurado.",
    useCases: ["Configurar entrenamientos", "Fine-tuning", "Estabilidad del entrenamiento"],
    prerequisites: ["gradient-descent"],
    relatedTerms: ["gradient-descent", "epoch", "batch", "optimization"],
    nextTerms: ["epoch", "batch"],
    tags: ["hiperparámetro", "tamaño de paso", "warmup"],
  },
  {
    slug: "epoch",
    name: "Epoch",
    spanishName: "Época",
    aliases: ["Época", "Epochs"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Una pasada completa del modelo por todo el dataset de entrenamiento.",
    simpleExplanation:
      "Si tu dataset es un libro de ejercicios, una época es resolverlo completo una vez. Los modelos suelen necesitar varias épocas para aprender bien, igual que repasar un tema varias veces.\n\nPero demasiadas épocas pueden llevar al [[overfitting]]: el modelo memoriza el libro en lugar de aprender.",
    technicalExplanation:
      "Una época se compone de N / B iteraciones, donde N es el tamaño del dataset y B el tamaño del [[batch]]. Los LLMs grandes a menudo entrenan aproximadamente una época sobre su corpus (o pocas repeticiones de los datos de mayor calidad), porque el dataset es enorme. Se usa **early stopping** para detenerse cuando la pérdida de validación deja de mejorar.",
    whyItMatters: "Ayuda a razonar sobre cuánto se entrena y cuándo detenerse.",
    useCases: ["Planeación de entrenamientos", "Early stopping"],
    prerequisites: ["training", "dataset"],
    relatedTerms: ["batch", "overfitting", "training", "learning-rate"],
    nextTerms: ["batch", "overfitting"],
    tags: ["época", "iteración", "pasada"],
  },
  {
    slug: "batch",
    name: "Batch",
    spanishName: "Lote",
    aliases: ["Lote", "Mini-batch", "Batch size", "Tamaño de lote"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Un grupo de ejemplos que el modelo procesa juntos antes de actualizar sus parámetros.",
    simpleExplanation:
      "En lugar de corregir al modelo después de cada ejemplo, se le muestran, por ejemplo, 64 a la vez y se promedia el error. Es más rápido (las [[gpu|GPUs]] procesan muchos ejemplos en paralelo) y las correcciones son más estables.",
    technicalExplanation:
      "El gradiente se estima como el promedio sobre el batch. Batches más grandes dan gradientes menos ruidosos y mejor uso del hardware, pero requieren más memoria y ajustar la [[learning-rate]]. Cuando no cabe en memoria, se usa **gradient accumulation**. En [[inference|inferencia]], el [[batching]] agrupa solicitudes de distintos usuarios para aumentar el [[throughput]].",
    whyItMatters: "El tamaño del batch afecta la velocidad, la memoria y la estabilidad del entrenamiento.",
    useCases: ["Entrenamiento en GPU", "Inferencia por lotes"],
    prerequisites: ["training"],
    relatedTerms: ["epoch", "gradient-descent", "batching", "gpu"],
    nextTerms: ["epoch", "gradient-descent"],
    tags: ["lote", "minibatch"],
  },
  {
    slug: "backpropagation",
    name: "Backpropagation",
    spanishName: "Retropropagación",
    aliases: ["Retropropagación", "Backprop", "Propagación hacia atrás"],
    category: "deep-learning",
    secondaryCategories: ["math"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "El algoritmo que calcula cuánto contribuyó cada parámetro de una red al error, propagando ese error desde la salida hacia atrás.",
    simpleExplanation:
      "Cuando el modelo se equivoca, hay que saber a quién «culpar». Backpropagation recorre la red desde la salida hasta la entrada y reparte la responsabilidad del error entre todas las conexiones.\n\nCon esa información, el [[gradient-descent|descenso de gradiente]] sabe cuánto ajustar cada [[weights|peso]].",
    analogy:
      "Es como analizar un partido perdido: empiezas por el gol recibido y vas hacia atrás, jugada por jugada, para entender qué tanto contribuyó cada jugador.",
    inThirtySeconds: [
      "Forward pass: la entrada recorre la red y produce una predicción.",
      "Se calcula la pérdida comparando con la respuesta correcta.",
      "Backward pass: se aplica la regla de la cadena capa por capa, de la salida a la entrada.",
      "Se obtiene un gradiente para cada parámetro.",
      "El optimizador usa esos gradientes para actualizar los pesos.",
    ],
    technicalExplanation:
      "Backpropagation es una aplicación eficiente de la **regla de la cadena** del cálculo, conocida como diferenciación automática en modo reverso. Reutiliza los valores intermedios del forward pass para calcular todos los gradientes con un costo del mismo orden que una sola evaluación de la red.\n\nFrameworks como PyTorch y JAX lo implementan automáticamente construyendo un grafo de cómputo. Problemas clásicos: gradientes que se desvanecen o explotan en redes profundas, mitigados con [[residual-connection|conexiones residuales]], [[layer-normalization|normalización]], buena inicialización y gradient clipping.",
    math: {
      formula: "∂L/∂w = (∂L/∂y) · (∂y/∂z) · (∂z/∂w)",
      caption: "La regla de la cadena para un peso w en una neurona con z = w·x + b y salida y = σ(z).",
      symbols: [
        { symbol: "∂L/∂w", meaning: "Cuánto cambia la pérdida si cambia un poco el peso w" },
        { symbol: "∂L/∂y", meaning: "Sensibilidad de la pérdida a la salida de la neurona (viene de las capas siguientes)" },
        { symbol: "∂y/∂z", meaning: "Derivada de la función de activación" },
        { symbol: "∂z/∂w", meaning: "Igual a la entrada x" },
      ],
    },
    whyItMatters: "Sin backpropagation no sería práctico entrenar redes con millones o miles de millones de parámetros.",
    useCases: ["Entrenamiento de toda red neuronal moderna"],
    prerequisites: ["neural-network", "derivative", "gradient"],
    relatedTerms: ["gradient-descent", "gradient", "derivative", "loss-function"],
    nextTerms: ["gradient-descent", "overfitting"],
    tags: ["regla de la cadena", "gradientes", "autograd"],
    sources: [
      { title: "Learning representations by back-propagating errors", authors: "Rumelhart, Hinton & Williams", year: 1986, url: "https://www.nature.com/articles/323533a0", kind: "paper" },
    ],
  },
  {
    slug: "overfitting",
    name: "Overfitting",
    spanishName: "Sobreajuste",
    aliases: ["Sobreajuste", "Sobreentrenamiento"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Cuando un modelo memoriza los datos de entrenamiento, incluido su ruido, y falla con datos nuevos.",
    simpleExplanation:
      "Es como un estudiante que memoriza las respuestas de los exámenes anteriores sin entender el tema. Saca 10 en la práctica, pero reprueba el examen real con preguntas nuevas.\n\nSe detecta cuando el modelo es excelente con sus datos de entrenamiento pero mediocre con datos de validación.",
    diagram: { kind: "custom", id: "fit-curves", title: "Underfitting, buen ajuste y overfitting", caption: "El modelo sobreajustado pasa por todos los puntos, pero su curva no representa la tendencia real." },
    technicalExplanation:
      "Ocurre cuando la capacidad del modelo es alta en relación con la cantidad y variedad de datos. Síntoma: la pérdida de entrenamiento sigue bajando mientras la de validación sube. Remedios: más datos, [[regularization|regularización]] (weight decay, dropout), data augmentation, early stopping o un modelo más simple.\n\nCuriosamente, en redes muy grandes se observa el fenómeno de **double descent**: al seguir aumentando el tamaño, el error de prueba puede volver a bajar.",
    whyItMatters: "Un modelo sobreajustado da una falsa sensación de éxito durante el desarrollo y falla en producción.",
    useCases: ["Diagnóstico de entrenamiento", "Selección de modelos"],
    prerequisites: ["training", "dataset"],
    relatedTerms: ["underfitting", "generalization", "regularization", "epoch"],
    nextTerms: ["underfitting", "generalization", "regularization"],
    tags: ["memorizar", "sobreajuste", "validación"],
  },
  {
    slug: "underfitting",
    name: "Underfitting",
    spanishName: "Subajuste",
    aliases: ["Subajuste"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "Cuando un modelo es demasiado simple o está poco entrenado y no logra capturar los patrones de los datos.",
    simpleExplanation:
      "Es el problema contrario al [[overfitting]]: el estudiante que no estudió lo suficiente. Le va mal tanto en la práctica como en el examen real. Intentar predecir el clima con una línea recta sería un ejemplo de subajuste.",
    technicalExplanation:
      "Se manifiesta como pérdida alta tanto en entrenamiento como en validación: el modelo tiene alto **sesgo** en el sentido estadístico (bias-variance tradeoff). Soluciones: un modelo con más capacidad, mejores [[feature|features]], entrenar más tiempo o reducir la regularización.",
    whyItMatters: "Indica que el modelo aún no aprovecha la información disponible.",
    useCases: ["Diagnóstico de entrenamiento"],
    prerequisites: ["training"],
    relatedTerms: ["overfitting", "generalization", "model"],
    nextTerms: ["generalization"],
    tags: ["subajuste", "demasiado simple"],
  },
  {
    slug: "generalization",
    name: "Generalization",
    spanishName: "Generalización",
    aliases: ["Generalización", "Capacidad de generalizar"],
    category: "machine-learning",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La capacidad de un modelo de funcionar bien con datos que no vio durante el entrenamiento.",
    simpleExplanation:
      "Es el verdadero objetivo del machine learning. No queremos un modelo que recuerde los ejemplos, sino uno que entienda el patrón y pueda aplicarlo a casos nuevos.\n\nUn niño que aprendió a sumar con manzanas puede sumar naranjas: eso es generalizar.",
    technicalExplanation:
      "Se estima con un conjunto de prueba independiente. La brecha de generalización es la diferencia entre el error de entrenamiento y el de prueba. Un problema práctico es el cambio de distribución (*distribution shift*): datos de producción distintos a los de entrenamiento, lo que se vigila con monitoreo de [[model-drift|drift]].",
    whyItMatters: "Un modelo solo es útil si generaliza. Todo lo demás es memoria.",
    useCases: ["Evaluación de modelos", "Diseño de experimentos"],
    prerequisites: ["overfitting", "underfitting"],
    relatedTerms: ["overfitting", "underfitting", "evaluation", "benchmark"],
    nextTerms: ["evaluation", "regularization"],
    tags: ["generalizar", "datos nuevos"],
  },
  {
    slug: "regularization",
    name: "Regularization",
    spanishName: "Regularización",
    aliases: ["Regularización", "Dropout", "Weight decay", "L2", "L1"],
    category: "machine-learning",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Técnicas que limitan la complejidad de un modelo para evitar que memorice los datos y mejorar su generalización.",
    simpleExplanation:
      "Es ponerle reglas al modelo para que no «haga trampa» memorizando. Por ejemplo, **dropout** apaga neuronas al azar durante el entrenamiento, obligando a la red a no depender de ninguna en particular, como un equipo que practica con jugadores ausentes.",
    technicalExplanation:
      "Formas comunes: penalización L2 (weight decay) o L1 sobre los pesos añadida a la pérdida; dropout; data augmentation; early stopping; y label smoothing. Desde un punto de vista bayesiano, la regularización L2 equivale a una distribución previa gaussiana sobre los parámetros.",
    whyItMatters: "Es la herramienta principal contra el overfitting.",
    useCases: ["Entrenamiento con pocos datos", "Redes profundas", "Fine-tuning"],
    prerequisites: ["overfitting"],
    relatedTerms: ["overfitting", "generalization", "loss-function"],
    nextTerms: ["generalization"],
    tags: ["dropout", "weight decay", "l2"],
    sources: [
      { title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting", authors: "Srivastava et al.", year: 2014, url: "https://jmlr.org/papers/v15/srivastava14a.html", kind: "paper" },
    ],
  },
];
