import type { TermInput } from "@/types/glossary";

export const optimizationTerms: TermInput[] = [
  {
    slug: "quantization",
    name: "Quantization",
    spanishName: "Cuantización",
    aliases: ["Cuantización", "Cuantizar", "4-bit quantization", "8-bit quantization", "Cuantización a 4 bits", "Cuantización a 8 bits", "INT8", "INT4", "FP8", "GGUF"],
    category: "ai-engineering",
    secondaryCategories: ["llm", "hardware"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Reducir la precisión numérica de los pesos (y a veces activaciones) de un modelo para que ocupe menos memoria y se ejecute más rápido.",
    simpleExplanation:
      "Los pesos de un modelo suelen guardarse con números de 16 bits. Cuantizar es representarlos con menos bits —8 o incluso 4—, como redondear 3.14159265 a 3.14. Se pierde un poco de precisión, pero el modelo ocupa entre 2 y 4 veces menos memoria.\n\nGracias a esto, modelos que necesitarían un servidor pueden correr en una laptop o incluso en un teléfono.",
    example: {
      title: "Memoria para los pesos de un modelo de 70B parámetros",
      code: "FP16 / BF16   16 bits  →  ~140 GB\nINT8           8 bits  →   ~70 GB\nINT4           4 bits  →   ~35 GB",
      description: "Estimación solo de los pesos; la inferencia requiere memoria adicional para activaciones y [[kv-cache]].",
    },
    technicalExplanation:
      "Se mapea un rango de valores reales a un conjunto discreto usando una escala (y a veces un punto cero): q = round(x / s). La cuantización puede ser **post-entrenamiento** (PTQ; métodos como GPTQ o AWQ usan datos de calibración para minimizar el error) o **durante el entrenamiento** (QAT). La granularidad de las escalas (por tensor, por canal, por grupo de pesos) afecta la calidad.\n\nEn LLMs, la cuantización de solo pesos a 4 bits suele conservar bien la calidad en muchos modelos, aunque la degradación varía con la tarea y el tamaño. Además de memoria, reduce el ancho de banda necesario, que es el cuello de botella de la fase de decodificación; formatos como FP8 aprovechan soporte nativo en [[gpu|GPUs]] recientes.",
    commonMistakes: [
      "Cuantizar no es gratis: modelos pequeños o tareas exigentes (matemáticas, código) pueden degradarse notablemente. Siempre conviene [[evaluation|evaluar]] el modelo cuantizado en tu caso de uso.",
    ],
    whyItMatters: "Es la técnica más directa para reducir el costo de ejecutar modelos y para llevarlos a hardware modesto.",
    useCases: ["Ejecutar LLMs en local", "Reducir costos de servidores", "IA en dispositivos móviles", "QLoRA"],
    prerequisites: ["parameters", "inference"],
    relatedTerms: ["model-compression", "pruning", "qlora", "vram", "inference-optimization"],
    nextTerms: ["inference-optimization", "qlora", "pruning"],
    tags: ["cuantizar", "4 bits", "8 bits", "comprimir", "int4", "int8"],
    sources: [
      { title: "LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale", authors: "Dettmers et al.", year: 2022, url: "https://arxiv.org/abs/2208.07339", kind: "paper" },
      { title: "Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference", authors: "Jacob et al.", year: 2017, url: "https://arxiv.org/abs/1712.05877", kind: "paper" },
    ],
  },
  {
    slug: "pruning",
    name: "Pruning",
    spanishName: "Poda",
    aliases: ["Poda", "Poda de redes", "Network pruning"],
    category: "ai-engineering",
    secondaryCategories: ["deep-learning"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Eliminar pesos, neuronas o capas poco importantes de un modelo para hacerlo más pequeño y rápido.",
    simpleExplanation:
      "Como podar un árbol: se cortan las ramas que aportan poco para que el resto crezca mejor. En una red neuronal, muchas conexiones tienen pesos casi cero y apenas influyen; quitarlas reduce el tamaño con poca pérdida de calidad.",
    technicalExplanation:
      "**No estructurada**: elimina pesos individuales (por ejemplo, los de menor magnitud), creando matrices dispersas que requieren hardware o kernels especiales para acelerar. **Estructurada**: elimina neuronas, cabezas de atención o capas completas, lo que acelera directamente en hardware estándar. Suele seguirse de un reentrenamiento breve para recuperar calidad. La hipótesis del «boleto de lotería» (Frankle y Carbin, 2018) sugiere que las redes grandes contienen subredes pequeñas entrenables.",
    whyItMatters: "Complementa a la cuantización y la destilación para desplegar modelos eficientes.",
    useCases: ["Modelos para edge", "Reducción de latencia"],
    prerequisites: ["weights", "neural-network"],
    relatedTerms: ["quantization", "model-compression", "sparse-model", "distillation"],
    nextTerms: ["model-compression"],
    tags: ["poda", "sparsity"],
    sources: [{ title: "The Lottery Ticket Hypothesis: Finding Sparse, Trainable Neural Networks", authors: "Frankle & Carbin", year: 2018, url: "https://arxiv.org/abs/1803.03635", kind: "paper" }],
  },
  {
    slug: "model-compression",
    name: "Model Compression",
    spanishName: "Compresión de modelos",
    aliases: ["Compresión", "Compresión de modelos", "Compression"],
    category: "ai-engineering",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "El conjunto de técnicas para reducir el tamaño y el costo computacional de un modelo manteniendo su calidad.",
    simpleExplanation:
      "Un modelo más pequeño es más barato, más rápido y puede correr en más dispositivos. Comprimirlo combina varias estrategias: usar números más pequeños (cuantización), quitar partes (poda) o enseñar a un modelo pequeño a imitar a uno grande (destilación).",
    technicalExplanation:
      "Técnicas principales: [[quantization|cuantización]], [[pruning|poda]], [[distillation|destilación]], factorización de bajo rango y compartición de pesos. Se combinan a menudo (Han et al., 2015, «Deep Compression», combinó poda, cuantización y codificación Huffman). El objetivo se mide en tamaño, latencia, consumo energético y degradación de calidad en evaluaciones relevantes.",
    whyItMatters: "Hace viable la IA en dispositivos y reduce costos a escala.",
    useCases: ["IA en el dispositivo", "Reducción de costos", "Baja latencia"],
    prerequisites: ["model"],
    relatedTerms: ["quantization", "pruning", "distillation", "inference-optimization"],
    nextTerms: ["quantization", "distillation"],
    tags: ["comprimir", "eficiencia", "modelo pequeño"],
    sources: [{ title: "Deep Compression: Compressing Deep Neural Networks with Pruning, Trained Quantization and Huffman Coding", authors: "Han, Mao & Dally", year: 2015, url: "https://arxiv.org/abs/1510.00149", kind: "paper" }],
  },
  {
    slug: "latency",
    name: "Latency",
    spanishName: "Latencia",
    aliases: ["Latencia", "TTFT", "Time to first token", "Tiempo de respuesta"],
    category: "ai-engineering",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "El tiempo que tarda un sistema en responder a una solicitud.",
    simpleExplanation:
      "Es cuánto esperas. En un chatbot importan dos momentos: cuánto tarda en aparecer la primera palabra y a qué velocidad aparecen las siguientes. Una respuesta brillante que tarda 30 segundos puede ser peor experiencia que una buena que tarda 2.",
    technicalExplanation:
      "En LLMs se mide con **TTFT** (*time to first token*, dominado por la fase de prefill del prompt) y **TPOT** o latencia entre tokens (dominada por la decodificación, limitada por el ancho de banda de memoria). La latencia total ≈ TTFT + tokens_generados × TPOT. Factores: tamaño del modelo, longitud del prompt, carga del servidor, red y el [[test-time-compute|razonamiento extendido]]. Se reduce con modelos más pequeños, [[quantization]], [[kv-cache]], prompt caching y [[speculative-decoding]].",
    whyItMatters: "Define si una aplicación de IA se siente instantánea o lenta.",
    useCases: ["Asistentes de voz", "Autocompletado de código", "Chat en tiempo real"],
    prerequisites: ["inference"],
    relatedTerms: ["throughput", "inference-optimization", "kv-cache", "speculative-decoding"],
    nextTerms: ["throughput", "inference-optimization"],
    tags: ["velocidad", "tiempo de respuesta", "ttft"],
  },
  {
    slug: "throughput",
    name: "Throughput",
    spanishName: "Rendimiento de procesamiento",
    aliases: ["Tokens por segundo", "Tasa de procesamiento", "Capacidad"],
    category: "ai-engineering",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "La cantidad de trabajo que un sistema procesa por unidad de tiempo, por ejemplo, tokens o solicitudes por segundo.",
    simpleExplanation:
      "Si la latencia es qué tan rápido atiende un cajero a un cliente, el throughput es cuántos clientes atiende el banco por hora. Un servidor puede tener buena latencia individual pero bajo throughput, o al revés.",
    technicalExplanation:
      "Existe un compromiso entre latencia y throughput: agrupar más solicitudes ([[batching]]) aprovecha mejor la GPU y aumenta los tokens totales por segundo, pero puede alargar la espera de cada usuario. Se optimiza con continuous batching, gestión eficiente del [[kv-cache]] y paralelismo. Determina directamente el costo por token de un servicio.",
    whyItMatters: "Determina cuántos usuarios puede atender una infraestructura y cuánto cuesta cada respuesta.",
    useCases: ["Dimensionar servidores", "Procesamiento por lotes", "Planeación de costos"],
    prerequisites: ["latency"],
    relatedTerms: ["latency", "batching", "inference-server", "gpu"],
    nextTerms: ["batching"],
    tags: ["tokens por segundo", "capacidad", "escala"],
  },
  {
    slug: "batching",
    name: "Batching",
    spanishName: "Procesamiento por lotes",
    aliases: ["Continuous batching", "Dynamic batching", "Agrupamiento de solicitudes", "Batch inference"],
    category: "ai-engineering",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Agrupar varias solicitudes para procesarlas juntas en el hardware y aprovecharlo mejor.",
    simpleExplanation:
      "Una GPU es como un autobús: cuesta casi lo mismo llevar a una persona que a cuarenta. Agrupar solicitudes de distintos usuarios en un mismo «viaje» multiplica cuántas respuestas se generan con el mismo hardware.",
    technicalExplanation:
      "El batching estático espera a llenar un lote; el **continuous batching** (o *in-flight batching*) inserta y retira solicitudes del lote en cada paso de decodificación, evitando que las respuestas cortas esperen a las largas. Es la técnica central de servidores de inferencia modernos. Las APIs también ofrecen modos «batch» asíncronos con descuento para trabajos que no requieren respuesta inmediata.",
    whyItMatters: "Es una de las principales razones por las que servir LLMs a escala es económicamente viable.",
    useCases: ["Servidores de inferencia", "Procesamiento masivo de documentos"],
    prerequisites: ["batch", "inference"],
    relatedTerms: ["throughput", "inference-server", "kv-cache", "batch"],
    nextTerms: ["inference-server"],
    tags: ["lotes", "continuous batching"],
  },
  {
    slug: "speculative-decoding",
    name: "Speculative Decoding",
    spanishName: "Decodificación especulativa",
    aliases: ["Decodificación especulativa", "Speculative sampling", "Draft model"],
    category: "ai-engineering",
    secondaryCategories: ["llm"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Acelerar la generación haciendo que un modelo pequeño proponga varios tokens y que el modelo grande los verifique de una sola vez.",
    simpleExplanation:
      "Un asistente rápido escribe un borrador de las siguientes palabras; el experto lento solo revisa y acepta las que estén bien. Como revisar es más rápido que escribir palabra por palabra, el resultado final llega antes y es el mismo que habría producido el experto.",
    technicalExplanation:
      "Un modelo borrador genera k tokens; el modelo objetivo los evalúa en paralelo en un solo forward pass y acepta el prefijo más largo compatible mediante un esquema de muestreo por rechazo que garantiza la **misma distribución** de salida que el modelo objetivo (Leviathan et al., 2022). La aceleración depende de la tasa de aceptación. Variantes usan cabezas de predicción extra o n-gramas del propio prompt en lugar de un modelo separado.",
    whyItMatters: "Reduce la latencia sin sacrificar calidad, algo poco común en optimización.",
    useCases: ["Chat de baja latencia", "Autocompletado de código", "Servidores de inferencia"],
    prerequisites: ["next-token-prediction", "sampling"],
    relatedTerms: ["latency", "inference-optimization", "kv-cache", "sampling"],
    nextTerms: ["inference-optimization"],
    tags: ["borrador", "acelerar", "draft"],
    sources: [{ title: "Fast Inference from Transformers via Speculative Decoding", authors: "Leviathan, Kalman & Matias", year: 2022, url: "https://arxiv.org/abs/2211.17192", kind: "paper" }],
  },
  {
    slug: "inference-optimization",
    name: "Inference Optimization",
    spanishName: "Optimización de inferencia",
    aliases: ["Optimización de inferencia", "Serving optimization", "FlashAttention"],
    category: "ai-engineering",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "El conjunto de técnicas para ejecutar modelos más rápido, con menos memoria y a menor costo sin perder calidad.",
    simpleExplanation:
      "Entrenar un modelo se hace pocas veces; usarlo, millones de veces al día. Cada milisegundo y cada centavo ahorrado por respuesta se multiplica. La optimización de inferencia reúne todos los trucos para lograrlo.",
    technicalExplanation:
      "Palancas principales: a nivel de modelo ([[quantization]], [[distillation]], [[pruning]], arquitecturas [[mixture-of-experts|MoE]]); a nivel de algoritmo ([[kv-cache]], [[speculative-decoding]], kernels de atención eficientes como FlashAttention, que reorganizan el cálculo para minimizar lecturas de memoria); y a nivel de sistema ([[batching|continuous batching]], paralelismo de tensores, prompt caching, enrutamiento a modelos más pequeños). Se mide con [[latency|latencia]], [[throughput]] y costo por millón de tokens.",
    whyItMatters: "Determina si un producto de IA es rentable y si se siente rápido.",
    useCases: ["APIs de LLM", "Asistentes de alto tráfico", "Despliegue en dispositivos"],
    prerequisites: ["inference"],
    relatedTerms: ["quantization", "kv-cache", "batching", "speculative-decoding", "inference-server"],
    nextTerms: ["inference-server", "quantization"],
    tags: ["optimizar", "rendimiento", "costos", "flashattention"],
    sources: [{ title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness", authors: "Dao et al.", year: 2022, url: "https://arxiv.org/abs/2205.14135", kind: "paper" }],
  },
  {
    slug: "mixture-of-experts",
    name: "Mixture of Experts",
    spanishName: "Mezcla de expertos",
    acronym: "MoE",
    aliases: ["MoE", "Mezcla de expertos", "Expert", "Experto", "Expertos", "Sparse MoE"],
    category: "llm",
    secondaryCategories: ["deep-learning", "transformers"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Una arquitectura que divide parte del modelo en varios «expertos» y activa solo algunos para cada token, logrando mucha capacidad con menor costo por consulta.",
    simpleExplanation:
      "Imagina un hospital con muchos especialistas. Un paciente no pasa por todos: una recepcionista (el [[router]]) lo envía a los dos más adecuados. Así, el hospital tiene muchísimo conocimiento total, pero cada consulta solo ocupa a unos pocos médicos.\n\nUn modelo MoE puede tener cientos de miles de millones de parámetros, pero usar solo una fracción en cada token.",
    diagram: { kind: "custom", id: "mixture-of-experts", title: "Un token pasa por el router", caption: "Solo los expertos seleccionados (top-2 en este ejemplo) procesan el token." },
    technicalExplanation:
      "En un Transformer MoE, la [[feedforward-network|capa feedforward]] se reemplaza por N expertos (FFNs independientes) y un [[router]] que calcula puntuaciones y envía cada token a los k mejores (típicamente k = 1 o 2). La salida es la suma ponderada de los expertos elegidos. Esto desacopla los **parámetros totales** de los **parámetros activos** por token, que determinan el costo de cómputo.\n\nLa idea moderna viene de Shazeer et al. (2017); Switch Transformer (Fedus et al., 2021) la simplificó con top-1. Retos: balancear la carga entre expertos (pérdidas auxiliares), inestabilidad de entrenamiento y la memoria necesaria para alojar todos los expertos aunque no se usen a la vez. Se reporta que varios modelos de frontera y abiertos recientes usan MoE.",
    commonMistakes: [
      "Los «expertos» no suelen corresponder a temas humanos claros (un experto en historia, otro en química). Se especializan de formas que emergen del entrenamiento y que a menudo son difíciles de interpretar.",
      "MoE reduce el cómputo por token, no la memoria: todos los expertos deben estar cargados.",
    ],
    whyItMatters: "Permite escalar la capacidad de los modelos sin que el costo de inferencia crezca en la misma proporción.",
    useCases: ["LLMs de gran escala", "Modelos eficientes de alta capacidad"],
    prerequisites: ["transformer", "feedforward-network"],
    relatedTerms: ["router", "sparse-model", "dense-model", "scaling-laws", "feedforward-network"],
    nextTerms: ["router", "sparse-model", "scaling-laws"],
    tags: ["moe", "expertos", "sparse", "escalamiento"],
    sources: [
      { title: "Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer", authors: "Shazeer et al.", year: 2017, url: "https://arxiv.org/abs/1701.06538", kind: "paper" },
      { title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity", authors: "Fedus, Zoph & Shazeer", year: 2021, url: "https://arxiv.org/abs/2101.03961", kind: "paper" },
    ],
  },
  {
    slug: "router",
    name: "Router",
    spanishName: "Enrutador",
    aliases: ["Enrutador", "Gating network", "Red de compuerta", "Model router"],
    category: "llm",
    difficulty: "advanced",
    type: "concept",
    shortDefinition: "El componente que decide a qué expertos (en MoE) o a qué modelo (en un sistema) se envía cada entrada.",
    simpleExplanation:
      "Es el recepcionista que dirige el tráfico. En un modelo [[mixture-of-experts|MoE]], decide qué expertos procesan cada token. En una aplicación, un router puede decidir si una pregunta simple la responde un modelo pequeño y barato o una compleja la resuelve uno grande.",
    technicalExplanation:
      "En MoE, el router es una capa lineal que produce logits sobre los expertos, seguida de softmax y selección top-k. Se añaden pérdidas de balanceo para evitar que colapse enviando todo a pocos expertos, y límites de capacidad por experto. A nivel de sistema, el enrutamiento de modelos usa clasificadores o reglas para optimizar costo y calidad.",
    whyItMatters: "Su calidad determina la eficiencia de un MoE y el costo de sistemas con varios modelos.",
    useCases: ["Modelos MoE", "Enrutamiento entre modelos", "Optimización de costos"],
    prerequisites: ["mixture-of-experts"],
    relatedTerms: ["mixture-of-experts", "sparse-model", "orchestration"],
    nextTerms: ["sparse-model"],
    tags: ["gating", "enrutar"],
  },
  {
    slug: "sparse-model",
    name: "Sparse Model",
    spanishName: "Modelo disperso",
    aliases: ["Modelo disperso", "Sparse models", "Sparsity", "Dispersión"],
    category: "llm",
    secondaryCategories: ["deep-learning"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Un modelo en el que solo una parte de sus parámetros se usa (o es distinta de cero) para procesar cada entrada.",
    simpleExplanation:
      "En un modelo disperso no todo trabaja siempre. Como un edificio donde solo se encienden las luces de los pisos ocupados: hay mucha capacidad, pero el consumo depende de lo que realmente se usa.",
    technicalExplanation:
      "La dispersión puede ser **de activación condicional** (como en [[mixture-of-experts|MoE]], donde partes distintas del modelo se activan según la entrada) o **de pesos** (muchos pesos en cero tras [[pruning|poda]]). La primera reduce FLOPs por token; la segunda requiere soporte de hardware para traducirse en aceleración real (por ejemplo, patrones 2:4 en algunas GPUs).",
    whyItMatters: "Es una de las vías principales para escalar modelos de forma eficiente.",
    useCases: ["LLMs MoE", "Modelos podados para edge"],
    prerequisites: ["mixture-of-experts"],
    relatedTerms: ["dense-model", "mixture-of-experts", "pruning"],
    nextTerms: ["dense-model"],
    tags: ["disperso", "sparsity"],
  },
  {
    slug: "dense-model",
    name: "Dense Model",
    spanishName: "Modelo denso",
    aliases: ["Modelo denso", "Dense models"],
    category: "llm",
    secondaryCategories: ["deep-learning"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Un modelo en el que todos los parámetros participan en el procesamiento de cada entrada.",
    simpleExplanation:
      "Es el diseño «clásico»: cada token pasa por todas las capas y todos los pesos. Es más simple de entrenar y servir que un modelo disperso, pero su costo crece directamente con su tamaño.",
    technicalExplanation:
      "En un Transformer denso, el cómputo por token es aproximadamente 2 × (número de parámetros) FLOPs en el forward pass. Comparado con un MoE del mismo costo por token, un denso tiene menos parámetros totales pero usa menos memoria y tiene un comportamiento de entrenamiento más estable y predecible.",
    whyItMatters: "Sirve de referencia para comparar arquitecturas y costos.",
    useCases: ["La mayoría de modelos pequeños y medianos"],
    prerequisites: ["parameters"],
    relatedTerms: ["sparse-model", "mixture-of-experts", "flops"],
    nextTerms: ["sparse-model", "mixture-of-experts"],
    tags: ["denso"],
  },
  {
    slug: "scaling-laws",
    name: "Scaling Laws",
    spanishName: "Leyes de escalamiento",
    aliases: ["Leyes de escalamiento", "Leyes de escala", "Chinchilla", "Compute-optimal"],
    category: "frontier",
    secondaryCategories: ["llm"],
    difficulty: "research",
    type: "concept",
    shortDefinition: "Relaciones empíricas que describen cómo mejora el rendimiento de un modelo al aumentar sus parámetros, sus datos y su cómputo.",
    simpleExplanation:
      "Los investigadores descubrieron algo sorprendente: al aumentar el tamaño del modelo, la cantidad de datos y el cómputo, el error baja de forma muy predecible, siguiendo curvas casi exactas.\n\nEso permitió planear entrenamientos de cientos de millones de dólares con confianza: puedes estimar qué tan bueno será un modelo antes de entrenarlo, a partir de experimentos pequeños.",
    technicalExplanation:
      "Kaplan et al. (2020) encontraron que la pérdida sigue leyes de potencia respecto a parámetros N, datos D y cómputo C, a lo largo de varios órdenes de magnitud. Hoffmann et al. (2022, «Chinchilla») revisaron el balance óptimo: para un presupuesto fijo de cómputo, conviene escalar parámetros y tokens aproximadamente en proporción (del orden de ~20 tokens por parámetro), lo que indicaba que muchos modelos previos estaban subentrenados. En la práctica, muchos modelos se entrenan con muchos más tokens de los «óptimos» para abaratar su inferencia.\n\nLas leyes predicen la pérdida, no directamente capacidades concretas. Más recientemente se estudia el escalamiento del [[test-time-compute|cómputo en inferencia]] y del aprendizaje por refuerzo.",
    math: {
      formula: "L(N, D) ≈ E + A / N^α + B / D^β",
      caption: "Forma funcional usada en el análisis de Chinchilla.",
      symbols: [
        { symbol: "L", meaning: "Pérdida del modelo (menor es mejor)" },
        { symbol: "N", meaning: "Número de parámetros" },
        { symbol: "D", meaning: "Número de tokens de entrenamiento" },
        { symbol: "E", meaning: "Pérdida irreducible (entropía del lenguaje)" },
        { symbol: "A, B, α, β", meaning: "Constantes ajustadas empíricamente" },
      ],
    },
    whyItMatters: "Guían las decisiones de inversión más grandes de la industria de la IA.",
    useCases: ["Planeación de entrenamientos", "Predicción de rendimiento", "Asignación de presupuesto de cómputo"],
    prerequisites: ["parameters", "compute", "pretraining"],
    relatedTerms: ["compute", "flops", "test-time-compute", "emergent-capabilities"],
    nextTerms: ["test-time-compute", "emergent-capabilities"],
    tags: ["escalamiento", "chinchilla", "leyes de potencia"],
    sources: [
      { title: "Scaling Laws for Neural Language Models", authors: "Kaplan et al.", year: 2020, url: "https://arxiv.org/abs/2001.08361", kind: "paper" },
      { title: "Training Compute-Optimal Large Language Models", authors: "Hoffmann et al.", year: 2022, url: "https://arxiv.org/abs/2203.15556", kind: "paper" },
    ],
  },
  {
    slug: "compute",
    name: "Compute",
    spanishName: "Cómputo",
    aliases: ["Cómputo", "Poder de cómputo", "Capacidad de cómputo", "Recursos de cómputo"],
    category: "hardware",
    secondaryCategories: ["frontier"],
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "La cantidad de procesamiento que se usa para entrenar o ejecutar un modelo, normalmente medida en FLOPs o en horas de GPU.",
    simpleExplanation:
      "Es el «combustible» de la IA. Entrenar un modelo de frontera requiere miles de chips funcionando durante meses. Junto con los datos y los algoritmos, el cómputo es uno de los tres ingredientes que determinan qué tan capaces son los modelos.",
    technicalExplanation:
      "Se mide en [[flops|FLOPs]] totales (entrenamiento) o en GPU-horas. Para un Transformer, el cómputo de entrenamiento se aproxima como C ≈ 6·N·D (N parámetros, D tokens). El cómputo usado en los modelos más grandes ha crecido muy rápido en la última década. También se distingue el cómputo de entrenamiento del de inferencia, cuya importancia crece con los [[reasoning-model|modelos de razonamiento]].",
    whyItMatters: "Es un recurso escaso y caro que condiciona quién puede entrenar modelos de frontera, y un eje clave de la política de IA.",
    useCases: ["Planeación de entrenamientos", "Estimación de costos", "Políticas públicas de IA"],
    prerequisites: ["training"],
    relatedTerms: ["flops", "gpu", "scaling-laws", "cluster", "test-time-compute"],
    nextTerms: ["flops", "scaling-laws"],
    tags: ["cómputo", "gpu horas", "recursos"],
  },
  {
    slug: "flops",
    name: "FLOPs",
    spanishName: "Operaciones de punto flotante",
    acronym: "FLOPs",
    aliases: ["FLOP", "FLOPS", "Operaciones de punto flotante", "PetaFLOPs", "TFLOPS"],
    category: "hardware",
    secondaryCategories: ["math"],
    difficulty: "advanced",
    type: "mathematics",
    shortDefinition: "Operaciones de punto flotante: la unidad para medir cuánto cálculo requiere un modelo (FLOPs) o cuánto puede hacer un chip por segundo (FLOP/s).",
    simpleExplanation:
      "Cada suma o multiplicación de números con decimales es una operación de punto flotante. Contar cuántas hace un modelo permite comparar el costo de entrenar o usar modelos distintos. Un modelo grande puede requerir del orden de 10²⁴ o más operaciones para entrenarse.",
    technicalExplanation:
      "Hay ambigüedad de notación: «FLOPs» (cantidad total) vs. «FLOPS» o FLOP/s (tasa por segundo, que mide el rendimiento del hardware). Para un Transformer denso, el forward pass cuesta ≈ 2N FLOPs por token y el entrenamiento ≈ 6N por token. La utilización real (MFU, *model FLOPs utilization*) suele estar muy por debajo del máximo teórico del hardware por cuellos de botella de memoria y comunicación.",
    whyItMatters: "Es la moneda común para comparar costos de modelos y capacidad de hardware.",
    useCases: ["Estimar costos de entrenamiento", "Comparar chips", "Regulación basada en umbrales de cómputo"],
    prerequisites: ["compute"],
    relatedTerms: ["compute", "gpu", "tensor-core", "scaling-laws"],
    nextTerms: ["gpu", "scaling-laws"],
    tags: ["operaciones", "flop/s", "rendimiento"],
  },
  {
    slug: "test-time-compute",
    name: "Test-Time Compute",
    spanishName: "Cómputo en tiempo de inferencia",
    aliases: ["Inference-time scaling", "Inference-Time Compute", "Escalamiento en inferencia", "Test-time scaling", "Cómputo en inferencia"],
    category: "frontier",
    secondaryCategories: ["llm"],
    difficulty: "research",
    type: "technique",
    frontier: true,
    shortDefinition: "Mejorar las respuestas de un modelo dándole más cómputo al momento de responder: pensar más, generar varias opciones o verificar.",
    simpleExplanation:
      "Durante años, la forma principal de mejorar la IA fue entrenar modelos más grandes. El test-time compute propone otra palanca: dejar que el modelo **piense más** antes de responder. Igual que una persona responde mejor un problema difícil si tiene 10 minutos en vez de 10 segundos.",
    inThirtySeconds: [
      "Un problema difícil llega al modelo.",
      "En lugar de responder de inmediato, razona durante más tokens.",
      "Puede explorar varias soluciones y comparar.",
      "Verifica y corrige sus errores.",
      "Más cómputo al responder → mejor precisión (con rendimientos decrecientes).",
    ],
    technicalExplanation:
      "Estrategias: cadenas de razonamiento largas entrenadas con RL ([[reasoning-model|modelos de razonamiento]]), muestreo de múltiples respuestas con votación (*self-consistency*) o selección con un verificador o [[reward-model|modelo de recompensa]] (*best-of-N*), y búsqueda sobre árboles de pasos guiada por process reward models. Snell et al. (2024) estudiaron cómo asignar óptimamente este cómputo y encontraron que, en ciertos problemas, puede ser más eficiente que escalar parámetros.\n\nEl resultado es una nueva dimensión de las [[scaling-laws|leyes de escalamiento]]: el rendimiento mejora con el presupuesto de inferencia, a cambio de más [[latency|latencia]] y costo por respuesta.",
    whyItMatters: "Cambió la economía de la IA: la calidad ya no depende solo del entrenamiento, sino también de cuánto «pensar» se paga en cada respuesta.",
    useCases: ["Matemáticas y ciencia", "Programación compleja", "Agentes que planifican", "Tareas de alto valor donde la precisión importa más que la velocidad"],
    prerequisites: ["inference", "chain-of-thought", "reasoning-model"],
    relatedTerms: ["reasoning-model", "scaling-laws", "chain-of-thought", "reward-model", "latent-reasoning"],
    nextTerms: ["latent-reasoning", "scaling-laws"],
    tags: ["pensar más", "inferencia", "razonamiento", "escalamiento"],
    sources: [
      { title: "Scaling LLM Test-Time Compute Optimally can be More Effective than Scaling Model Parameters", authors: "Snell et al.", year: 2024, url: "https://arxiv.org/abs/2408.03314", kind: "paper" },
      { title: "Learning to reason with LLMs", authors: "OpenAI", year: 2024, url: "https://openai.com/index/learning-to-reason-with-llms/", kind: "article" },
    ],
  },
];
