import type { TermInput } from "@/types/glossary";

export const ragTerms: TermInput[] = [
  {
    slug: "rag",
    name: "Retrieval-Augmented Generation",
    spanishName: "Generación aumentada por recuperación",
    acronym: "RAG",
    aliases: ["RAG", "Retrieval Augmented Generation", "Generación aumentada por recuperación", "Generación aumentada con recuperación"],
    category: "rag",
    secondaryCategories: ["llm", "ai-engineering"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition:
      "Una técnica que conecta un LLM con fuentes de información externas: primero busca documentos relevantes y luego genera la respuesta basándose en ellos.",
    simpleExplanation:
      "Un LLM solo sabe lo que aprendió durante su entrenamiento: no conoce los documentos de tu empresa ni las noticias de ayer. RAG resuelve esto en dos pasos: **buscar** la información relevante en tus documentos y **pegarla** en el prompt para que el modelo responda con ella.\n\nAsí, el modelo puede contestar preguntas sobre información privada o actual, y citar de dónde la sacó.",
    analogy:
      "LLM sin RAG: un examen de memoria. LLM con RAG: un examen a libro abierto. El estudiante es igual de listo, pero ahora puede consultar las páginas correctas antes de responder.",
    inThirtySeconds: [
      "Los documentos se dividen en fragmentos (chunks).",
      "Cada fragmento se convierte en un embedding y se guarda en una base vectorial.",
      "La pregunta del usuario también se convierte en embedding.",
      "Se recuperan los fragmentos más similares.",
      "El LLM responde usando esos fragmentos como contexto.",
    ],
    diagram: {
      kind: "flow",
      title: "Pipeline de RAG",
      steps: [
        { label: "Pregunta", detail: "«¿Cuál es la política de vacaciones?»" },
        { label: "Embedding", detail: "La pregunta se convierte en un vector" },
        { label: "Vector Database", detail: "Búsqueda por similitud entre millones de fragmentos" },
        { label: "Documentos relevantes", chips: ["politica-rh.pdf §4", "faq-permisos.md"] },
        { label: "LLM", detail: "Prompt = instrucciones + fragmentos + pregunta" },
        { label: "Respuesta con fuentes", detail: "Basada en los documentos recuperados" },
      ],
    },
    realExample: {
      title: "Asistente interno de recursos humanos",
      dialogue: [
        { role: "user", text: "¿Cuántos días de vacaciones tengo si llevo 3 años en la empresa?" },
        { role: "system", text: "Recupera: «Política de vacaciones 2026, sección 4: a partir del tercer año corresponden 16 días hábiles…»" },
        { role: "assistant", text: "Según la Política de vacaciones 2026 (sección 4), con 3 años de antigüedad te corresponden 16 días hábiles." },
      ],
    },
    mentalModel: [
      { label: "LLM", meaning: "Motor de lenguaje." },
      { label: "RAG", meaning: "Biblioteca externa conectada al motor." },
      { label: "Embeddings", meaning: "Sistema para encontrar los libros relevantes." },
      { label: "Vector DB", meaning: "Catálogo semántico de la biblioteca." },
      { label: "Reranker", meaning: "Bibliotecario que ordena lo encontrado por relevancia." },
    ],
    comparison: {
      title: "RAG vs. Fine-Tuning",
      columns: ["RAG", "Fine-Tuning"],
      rows: [
        { aspect: "Qué cambia", a: "La información que el modelo ve", b: "Los pesos del modelo" },
        { aspect: "Ideal para", a: "Conocimiento que cambia o es privado", b: "Estilo, formato, comportamiento o tareas especializadas" },
        { aspect: "Actualizar datos", a: "Inmediato: reindexar documentos", b: "Requiere volver a entrenar" },
        { aspect: "Citas y trazabilidad", a: "Sí, puede señalar sus fuentes", b: "Difícil" },
        { aspect: "Costo inicial", a: "Bajo a moderado", b: "Moderado a alto" },
      ],
    },
    technicalExplanation:
      "El término proviene de Lewis et al. (2020). Un sistema RAG tiene dos fases. **Indexación** (offline): los documentos se dividen con [[chunking]], se convierten en vectores con un [[embedding-model|modelo de embeddings]] y se almacenan en una [[vector-database|base de datos vectorial]]. **Consulta** (online): se genera el embedding de la pregunta, se ejecuta una [[vector-search|búsqueda vectorial]] (a menudo [[hybrid-search|híbrida]] con búsqueda por palabras clave), se aplica [[reranking]] y los mejores fragmentos se insertan en el prompt.\n\nLa calidad depende sobre todo de la recuperación: si el fragmento correcto no se recupera, el modelo no puede usarlo. Se evalúa por separado la recuperación (recall@k, precisión) y la generación (fidelidad a las fuentes, relevancia). Variantes avanzadas incluyen reescritura de consultas, búsqueda en varios pasos y [[agentic-rag]].",
    commonMistakes: [
      "RAG no hace que el modelo «aprenda» permanentemente los documentos. La información solo está disponible durante esa consulta, dentro de la [[context-window|ventana de contexto]].",
      "RAG reduce las [[hallucination|alucinaciones]], pero no las elimina: el modelo puede malinterpretar o ignorar los fragmentos recuperados.",
    ],
    whyItMatters:
      "Es la forma más común de construir asistentes de IA sobre datos propios: es más barato que reentrenar, se actualiza al instante y permite citar fuentes.",
    useCases: ["Asistentes sobre documentación interna", "Soporte al cliente", "Búsqueda en bases legales", "Q&A sobre manuales técnicos", "Copilotos de investigación"],
    prerequisites: ["llm", "embeddings", "vector-database"],
    relatedTerms: ["semantic-search", "retrieval", "chunking", "reranking", "grounding", "hybrid-search"],
    nextTerms: ["agentic-rag", "hybrid-search", "reranking"],
    tags: ["recuperación", "documentos", "conocimiento", "búsqueda", "base de conocimiento"],
    sources: [
      { title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks", authors: "Lewis et al.", year: 2020, url: "https://arxiv.org/abs/2005.11401", kind: "paper" },
      { title: "Retrieval-Augmented Generation for Large Language Models: A Survey", authors: "Gao et al.", year: 2023, url: "https://arxiv.org/abs/2312.10997", kind: "paper" },
    ],
  },
  {
    slug: "retrieval",
    name: "Retrieval",
    spanishName: "Recuperación de información",
    aliases: ["Recuperación", "Recuperación de información", "Information retrieval", "Document retrieval", "Recuperación de documentos"],
    category: "rag",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "El proceso de encontrar, dentro de una colección grande, los documentos o fragmentos más relevantes para una consulta.",
    simpleExplanation:
      "Es la «R» de RAG: la parte de buscar. Cuando haces una pregunta, el sistema tiene que encontrar, entre miles de documentos, los pocos párrafos que realmente sirven para responderla. Si esta búsqueda falla, todo lo demás falla.",
    technicalExplanation:
      "La recuperación de información es un campo clásico. Métodos **dispersos** (léxicos) como BM25 puntúan por coincidencia de términos; métodos **densos** usan [[embeddings]] y [[vector-search|búsqueda vectorial]]. Se suele medir con recall@k (¿está el documento correcto entre los k primeros?), MRR y nDCG. La recuperación de documentos completos (*document retrieval*) y de pasajes cortos requieren estrategias de indexación distintas.",
    whyItMatters: "La calidad de un sistema RAG está limitada por la calidad de su recuperación.",
    useCases: ["Buscadores", "RAG", "Sistemas de preguntas y respuestas", "E-discovery legal"],
    prerequisites: ["semantic-search"],
    relatedTerms: ["retriever", "rag", "semantic-search", "keyword-search", "reranking"],
    nextTerms: ["retriever", "reranking"],
    tags: ["búsqueda", "recuperar", "bm25", "document retrieval"],
  },
  {
    slug: "retriever",
    name: "Retriever",
    spanishName: "Recuperador",
    aliases: ["Recuperador", "Buscador"],
    category: "rag",
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "El componente de un sistema RAG que recibe una consulta y devuelve los fragmentos más relevantes.",
    simpleExplanation:
      "Si RAG es un equipo, el retriever es el investigador que va a la biblioteca y regresa con los documentos correctos. El LLM después redacta la respuesta con lo que el retriever le trajo.",
    technicalExplanation:
      "Un retriever puede ser denso (bi-encoder que compara embeddings de consulta y documentos, como DPR), disperso (BM25) o híbrido. Suele devolver un conjunto amplio de candidatos que luego un [[reranking|reranker]] reordena con mayor precisión. En [[agentic-rag]], el retriever se expone al modelo como una [[tool-calling|herramienta]] que puede invocar varias veces.",
    whyItMatters: "Es el componente que decide qué información verá el modelo.",
    useCases: ["RAG", "Buscadores semánticos", "Agentes con acceso a documentos"],
    prerequisites: ["retrieval", "embeddings"],
    relatedTerms: ["retrieval", "embedding-model", "reranking", "vector-database"],
    nextTerms: ["reranking", "hybrid-search"],
    tags: ["recuperador", "dpr", "bi-encoder"],
    sources: [{ title: "Dense Passage Retrieval for Open-Domain Question Answering", authors: "Karpukhin et al.", year: 2020, url: "https://arxiv.org/abs/2004.04906", kind: "paper" }],
  },
  {
    slug: "semantic-search",
    name: "Semantic Search",
    spanishName: "Búsqueda semántica",
    aliases: ["Búsqueda semántica", "Búsqueda por significado", "Dense retrieval"],
    category: "vector-search",
    secondaryCategories: ["rag"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Buscar información por su significado en lugar de por coincidencia exacta de palabras.",
    simpleExplanation:
      "Un buscador tradicional busca las palabras exactas que escribiste. Si buscas «cómo arreglar una llanta ponchada», podría no encontrar un artículo titulado «reparar un neumático pinchado». La búsqueda semántica sí lo encuentra, porque compara significados, no palabras.",
    technicalExplanation:
      "Se implementa con [[embeddings]]: consulta y documentos se convierten en vectores y se recuperan los más cercanos según [[cosine-similarity|similitud coseno]] o producto punto, usando [[vector-search|búsqueda vectorial]] aproximada. Su punto débil son coincidencias exactas (códigos, nombres propios, números de pieza), donde la [[keyword-search|búsqueda léxica]] funciona mejor; por eso se combina en [[hybrid-search]].",
    whyItMatters: "Permite encontrar información aunque el usuario no conozca las palabras exactas del documento.",
    useCases: ["RAG", "Buscadores internos", "Soporte al cliente", "E-commerce", "Búsqueda multilingüe"],
    prerequisites: ["embeddings", "cosine-similarity"],
    relatedTerms: ["embeddings", "vector-search", "keyword-search", "hybrid-search", "rag"],
    nextTerms: ["vector-database", "hybrid-search"],
    tags: ["buscar por significado", "semántica", "búsqueda inteligente"],
  },
  {
    slug: "keyword-search",
    name: "Keyword Search",
    spanishName: "Búsqueda por palabras clave",
    aliases: ["Búsqueda por palabras clave", "Búsqueda léxica", "Lexical search", "BM25", "Full-text search", "Sparse retrieval"],
    category: "vector-search",
    secondaryCategories: ["rag"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Buscar documentos según las palabras exactas que contienen, puntuando qué tan relevantes son esas coincidencias.",
    simpleExplanation:
      "Es la búsqueda clásica: encuentra documentos que contienen las palabras que escribiste. Parece anticuada frente a la búsqueda semántica, pero es excelente para nombres propios, códigos de producto o términos técnicos exactos.",
    technicalExplanation:
      "Se basa en índices invertidos y funciones de puntuación como TF-IDF o **BM25**, que premia términos frecuentes en el documento pero raros en la colección, con normalización por longitud. Es rápida, interpretable y no requiere entrenamiento. Se representa como vectores dispersos (*sparse*), en contraste con los embeddings densos.",
    whyItMatters: "Complementa a la búsqueda semántica y sigue siendo parte esencial de los buenos sistemas de recuperación.",
    useCases: ["Buscadores de texto completo", "Búsqueda híbrida", "Catálogos de productos"],
    prerequisites: ["retrieval"],
    relatedTerms: ["semantic-search", "hybrid-search", "retrieval"],
    nextTerms: ["hybrid-search"],
    tags: ["bm25", "tf-idf", "léxica", "palabras exactas"],
  },
  {
    slug: "embedding-model",
    name: "Embedding Model",
    spanishName: "Modelo de embeddings",
    aliases: ["Modelo de embeddings", "Text embedding model", "Sentence transformer", "Bi-encoder"],
    category: "vector-search",
    secondaryCategories: ["rag"],
    difficulty: "intermediate",
    type: "model",
    shortDefinition: "Un modelo especializado en convertir textos (u otros datos) en embeddings útiles para buscar y comparar.",
    simpleExplanation:
      "No todos los modelos sirven para lo mismo. Un LLM genera texto; un modelo de embeddings convierte texto en un vector que resume su significado. Es la pieza que hace posible la búsqueda semántica y RAG.",
    technicalExplanation:
      "Suelen ser [[encoder|encoders]] Transformer entrenados con **aprendizaje contrastivo**: se acercan en el espacio los pares relacionados (pregunta y respuesta, textos parafraseados) y se alejan los no relacionados. Producen un vector por texto mediante pooling de los tokens. Características a comparar: dimensión, longitud máxima, soporte multilingüe, rendimiento en benchmarks como MTEB y costo. Cambiar de modelo obliga a recalcular todos los vectores del índice.",
    whyItMatters: "Elegir un buen modelo de embeddings, adecuado al idioma y dominio, suele ser la mejora más directa de un sistema RAG.",
    useCases: ["Indexación para RAG", "Búsqueda semántica", "Clustering de documentos", "Recomendaciones"],
    prerequisites: ["embeddings"],
    relatedTerms: ["embeddings", "vector-database", "semantic-search", "encoder"],
    nextTerms: ["vector-database", "chunking"],
    tags: ["modelo de embeddings", "contrastivo", "mteb"],
  },
  {
    slug: "vector-database",
    name: "Vector Database",
    spanishName: "Base de datos vectorial",
    aliases: ["Base de datos vectorial", "Base de vectores", "Vector DB", "Vector store", "Almacén vectorial", "Bases de datos de vectores"],
    category: "vector-search",
    secondaryCategories: ["rag", "ai-engineering"],
    difficulty: "intermediate",
    type: "infrastructure",
    shortDefinition: "Una base de datos diseñada para almacenar embeddings y encontrar rápidamente los más parecidos a una consulta.",
    simpleExplanation:
      "Una base de datos tradicional responde preguntas como «dame los clientes de Monterrey». Una base de datos vectorial responde «dame los 5 documentos cuyo significado se parezca más a esta pregunta», incluso entre millones de documentos y en milisegundos.\n\nEs la pieza de almacenamiento típica de un sistema [[rag]].",
    analogy:
      "Es el catálogo de una biblioteca organizado por temas en lugar de por orden alfabético: los libros sobre temas parecidos están en estantes cercanos, así que encontrar «algo similar» es rapidísimo.",
    technicalExplanation:
      "Almacena vectores junto con metadatos y el texto original, y construye índices de [[approximate-nearest-neighbor|búsqueda aproximada de vecinos más cercanos]] (ANN) como HNSW o IVF para evitar comparar la consulta con cada vector. Funciones clave: filtrado por metadatos, búsqueda [[hybrid-search|híbrida]], actualización incremental y escalado horizontal.\n\nExisten bases especializadas y también extensiones de bases tradicionales (por ejemplo, pgvector para PostgreSQL). Para colecciones pequeñas, una búsqueda exacta en memoria puede ser suficiente.",
    commonMistakes: [
      "No siempre necesitas una base de datos vectorial dedicada. Para unos miles de documentos, una extensión de tu base actual o incluso un índice en memoria suele bastar.",
    ],
    whyItMatters: "Permite que la búsqueda semántica funcione a escala, con latencias compatibles con una conversación.",
    useCases: ["RAG", "Recomendaciones", "Búsqueda de imágenes similares", "Deduplicación", "Memoria de largo plazo para agentes"],
    prerequisites: ["embeddings", "vector"],
    relatedTerms: ["vector-search", "approximate-nearest-neighbor", "embeddings", "rag", "semantic-search"],
    nextTerms: ["rag", "hybrid-search", "reranking"],
    tags: ["vector db", "pgvector", "índice", "almacenamiento"],
  },
  {
    slug: "vector-search",
    name: "Vector Search",
    spanishName: "Búsqueda vectorial",
    aliases: ["Búsqueda vectorial", "Similarity search", "Búsqueda por similitud", "Nearest neighbor search", "k-NN"],
    category: "vector-search",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Encontrar los vectores más cercanos a un vector de consulta dentro de una colección.",
    simpleExplanation:
      "Si cada documento es un punto en un mapa de significados, buscar es simplemente encontrar los puntos más cercanos al punto de tu pregunta. Eso es la búsqueda vectorial.",
    technicalExplanation:
      "La búsqueda exacta de k vecinos más cercanos (k-NN) compara la consulta con todos los vectores: O(n·d). Para millones de vectores se usa búsqueda [[approximate-nearest-neighbor|aproximada]], que sacrifica un poco de recall a cambio de enorme velocidad. Métricas: [[cosine-similarity|coseno]], [[dot-product|producto punto]] o distancia euclidiana; con vectores normalizados, coseno y producto punto dan el mismo orden.",
    whyItMatters: "Es la operación fundamental detrás de la búsqueda semántica y RAG.",
    useCases: ["Búsqueda semántica", "Recomendaciones", "Detección de duplicados"],
    prerequisites: ["embeddings", "cosine-similarity"],
    relatedTerms: ["vector-database", "approximate-nearest-neighbor", "semantic-search", "cosine-similarity"],
    nextTerms: ["approximate-nearest-neighbor", "vector-database"],
    tags: ["similitud", "vecinos", "knn"],
  },
  {
    slug: "approximate-nearest-neighbor",
    name: "Approximate Nearest Neighbor",
    spanishName: "Vecinos más cercanos aproximados",
    acronym: "ANN",
    aliases: ["ANN", "HNSW", "IVF", "Vecino más cercano aproximado", "Índice vectorial"],
    category: "vector-search",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Algoritmos que encuentran vectores muy cercanos a una consulta sin compararla con todos, a cambio de una pequeña pérdida de exactitud.",
    simpleExplanation:
      "Buscar el punto más cercano entre mil millones comparando uno por uno sería lentísimo. Los algoritmos ANN organizan los vectores de forma inteligente —como un mapa con autopistas y calles locales— para llegar a una zona prometedora rápidamente y buscar solo ahí.",
    technicalExplanation:
      "**HNSW** (Hierarchical Navigable Small World) construye un grafo de varios niveles: los superiores tienen pocas conexiones largas y los inferiores muchas cortas; la búsqueda desciende de forma voraz. **IVF** agrupa los vectores con k-means y solo explora los clusters más cercanos. La **cuantización de producto** (PQ) comprime los vectores para ahorrar memoria. Se ajusta el equilibrio entre recall, latencia y memoria con parámetros como ef_search o nprobe.",
    whyItMatters: "Hace posible la búsqueda semántica en tiempo real sobre colecciones gigantes.",
    useCases: ["Bases de datos vectoriales", "Motores de recomendación", "Búsqueda de imágenes"],
    prerequisites: ["vector-search"],
    relatedTerms: ["vector-database", "vector-search", "quantization"],
    nextTerms: ["vector-database"],
    tags: ["hnsw", "ivf", "faiss", "índice"],
    sources: [{ title: "Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs", authors: "Malkov & Yashunin", year: 2016, url: "https://arxiv.org/abs/1603.09320", kind: "paper" }],
  },
  {
    slug: "chunking",
    name: "Chunking",
    spanishName: "Fragmentación de documentos",
    aliases: ["Chunk", "Chunks", "Fragmentación", "Fragmentos", "Text splitting", "Dividir documentos"],
    category: "rag",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Dividir documentos largos en fragmentos más pequeños (chunks) para indexarlos y recuperarlos en un sistema RAG.",
    simpleExplanation:
      "No tiene sentido recuperar un manual de 300 páginas para responder una pregunta concreta. Por eso los documentos se cortan en fragmentos —de unos cuantos párrafos— y se busca el fragmento exacto que responde.\n\nSi los fragmentos son demasiado pequeños, pierden contexto; si son demasiado grandes, mezclan temas y diluyen la búsqueda.",
    example: {
      code: "manual.pdf (120 páginas)\n  ├─ chunk 1: «1. Introducción…»          ~400 tokens\n  ├─ chunk 2: «2. Instalación…»            ~400 tokens\n  ├─ chunk 3: «2.1 Requisitos…»            ~400 tokens\n  └─ …  (con ~50 tokens de solapamiento)",
    },
    technicalExplanation:
      "Estrategias: tamaño fijo en tokens con **solapamiento** (overlap) para no cortar ideas; división recursiva por separadores (secciones, párrafos, oraciones); división por estructura (encabezados Markdown, funciones de código); y **chunking semántico**, que corta donde cambia el tema según embeddings. Es útil guardar metadatos (título, sección, página) y a veces añadir a cada chunk un resumen del documento para conservar contexto. El tamaño óptimo depende del modelo de embeddings y del tipo de preguntas, y conviene ajustarlo con evaluaciones.",
    whyItMatters: "Es una de las decisiones que más impactan la calidad de un sistema RAG, y una de las más subestimadas.",
    useCases: ["Indexación para RAG", "Procesamiento de PDFs", "Búsqueda en código"],
    prerequisites: ["rag", "token"],
    relatedTerms: ["rag", "embedding-model", "retrieval", "knowledge-base"],
    nextTerms: ["reranking", "retrieval"],
    tags: ["fragmentos", "chunk", "overlap", "dividir"],
  },
  {
    slug: "reranking",
    name: "Reranking",
    spanishName: "Reordenamiento",
    aliases: ["Reranker", "Re-ranking", "Reordenamiento", "Cross-encoder"],
    category: "rag",
    secondaryCategories: ["vector-search"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Un segundo paso que reordena los resultados de búsqueda con un modelo más preciso para quedarse con los más relevantes.",
    simpleExplanation:
      "La primera búsqueda es rápida pero algo tosca: trae, digamos, 50 candidatos. Un reranker los lee con más cuidado —uno por uno junto con la pregunta— y los ordena por relevancia real. Solo los mejores 5 llegan al LLM.",
    technicalExplanation:
      "Los rerankers suelen ser **cross-encoders**: procesan consulta y documento juntos en un mismo Transformer, lo que permite atención entre ambos y juicios más finos que comparar embeddings independientes (bi-encoders). Son más lentos, por eso solo se aplican al top-k. También pueden usarse LLMs como rerankers. Mejoran notablemente la precisión de RAG con un costo de latencia moderado.",
    whyItMatters: "Suele ser una de las mejoras con mejor relación costo-beneficio en un pipeline de recuperación.",
    useCases: ["RAG", "Buscadores", "Recomendaciones"],
    prerequisites: ["retrieval", "embedding-model"],
    relatedTerms: ["retriever", "hybrid-search", "rag", "encoder"],
    nextTerms: ["hybrid-search", "agentic-rag"],
    tags: ["reranker", "cross-encoder", "relevancia"],
    sources: [{ title: "Passage Re-ranking with BERT", authors: "Nogueira & Cho", year: 2019, url: "https://arxiv.org/abs/1901.04085", kind: "paper" }],
  },
  {
    slug: "hybrid-search",
    name: "Hybrid Search",
    spanishName: "Búsqueda híbrida",
    aliases: ["Búsqueda híbrida", "Reciprocal rank fusion", "RRF"],
    category: "vector-search",
    secondaryCategories: ["rag"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Combinar búsqueda semántica (vectores) y búsqueda por palabras clave para obtener lo mejor de ambas.",
    simpleExplanation:
      "La búsqueda semántica entiende sinónimos pero falla con códigos exactos como «error E-4021». La búsqueda por palabras clave es lo contrario. La búsqueda híbrida ejecuta ambas y combina los resultados.",
    technicalExplanation:
      "Se ejecutan en paralelo una búsqueda densa ([[vector-search]]) y una dispersa ([[keyword-search|BM25]]), y se fusionan los rankings, por ejemplo con **Reciprocal Rank Fusion** (RRF), que suma 1/(k + rango) de cada lista, o con una combinación ponderada de puntuaciones normalizadas. Suele seguirse de [[reranking]].",
    whyItMatters: "En la práctica supera a cualquiera de los dos métodos por separado en la mayoría de los dominios.",
    useCases: ["RAG empresarial", "Documentación técnica", "E-commerce"],
    prerequisites: ["semantic-search", "keyword-search"],
    relatedTerms: ["semantic-search", "keyword-search", "reranking", "vector-database"],
    nextTerms: ["reranking", "agentic-rag"],
    tags: ["híbrida", "bm25", "rrf"],
  },
  {
    slug: "knowledge-base",
    name: "Knowledge Base",
    spanishName: "Base de conocimiento",
    aliases: ["Base de conocimiento", "KB", "Base de conocimientos"],
    category: "rag",
    difficulty: "beginner",
    type: "concept",
    shortDefinition: "La colección organizada de documentos e información que un sistema de IA puede consultar para responder.",
    simpleExplanation:
      "Es la biblioteca de tu asistente: manuales, políticas, preguntas frecuentes, tickets resueltos, fichas de producto. Un sistema [[rag]] busca aquí antes de responder. Si la información no está en la base de conocimiento (o está desactualizada), el asistente no podrá dar una buena respuesta.",
    technicalExplanation:
      "Técnicamente incluye las fuentes originales, el pipeline de ingesta (extracción de texto, limpieza, [[chunking]]), el índice ([[vector-database]] y/o índice léxico) y los metadatos para filtrar por permisos, fecha o tipo. Mantenerla sincronizada, deduplicada y con control de acceso es un reto de ingeniería clave. También puede estructurarse como un grafo de conocimiento (GraphRAG).",
    whyItMatters: "La calidad de las respuestas de un asistente nunca supera la calidad de su base de conocimiento.",
    useCases: ["Soporte al cliente", "Asistentes internos", "Documentación de producto"],
    prerequisites: ["data"],
    relatedTerms: ["rag", "chunking", "vector-database", "grounding"],
    nextTerms: ["rag", "chunking"],
    tags: ["documentos", "biblioteca", "faq"],
  },
  {
    slug: "grounding",
    name: "Grounding",
    spanishName: "Anclaje en fuentes",
    aliases: ["Anclaje", "Fundamentación", "Grounded generation", "Citas"],
    category: "rag",
    secondaryCategories: ["safety"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Hacer que las respuestas de un modelo se basen en fuentes concretas y verificables en lugar de solo en su memoria.",
    simpleExplanation:
      "Una respuesta «anclada» es aquella que puedes rastrear hasta un documento. En lugar de «confía en mí», el modelo dice «según el documento X, página 4…». Esto reduce las [[hallucination|alucinaciones]] y permite verificar.",
    technicalExplanation:
      "Se logra proporcionando fuentes en el contexto ([[rag]], resultados de búsqueda web, datos de [[tool-calling|herramientas]]), instruyendo al modelo a responder solo con base en ellas y a citar, y evaluando la **fidelidad** (*faithfulness*): que cada afirmación esté respaldada por las fuentes. Algunas APIs ofrecen citas estructuradas que vinculan fragmentos de la respuesta con pasajes específicos.",
    whyItMatters: "Es indispensable para usar IA en contextos donde las respuestas deben poder auditarse.",
    useCases: ["Asistentes legales y médicos", "Buscadores con IA", "Reportes con citas"],
    prerequisites: ["rag", "hallucination"],
    relatedTerms: ["rag", "hallucination", "knowledge-base", "evaluation"],
    nextTerms: ["evaluation", "agentic-rag"],
    tags: ["citas", "fuentes", "verificable", "fidelidad"],
  },
  {
    slug: "agentic-rag",
    name: "Agentic RAG",
    spanishName: "RAG agéntico",
    aliases: ["RAG agéntico", "RAG con agentes"],
    category: "rag",
    secondaryCategories: ["agents"],
    difficulty: "advanced",
    type: "technique",
    frontier: true,
    shortDefinition: "Una variante de RAG en la que un agente decide cuándo, qué y cuántas veces buscar, en lugar de hacer una sola búsqueda fija.",
    simpleExplanation:
      "El RAG clásico siempre hace lo mismo: una búsqueda y responde. En el RAG agéntico, el modelo actúa como un investigador: descompone la pregunta, busca, lee, se da cuenta de que le falta algo, busca de nuevo en otra fuente y solo entonces responde.",
    technicalExplanation:
      "La recuperación se expone como [[tool-calling|herramientas]] (búsqueda vectorial, SQL, búsqueda web) dentro de un bucle de [[ai-agent|agente]]. El modelo puede reescribir consultas, hacer búsquedas en varios pasos (*multi-hop*), verificar si la evidencia es suficiente y elegir fuentes. Gana precisión en preguntas complejas a cambio de más latencia, costo y menor previsibilidad, por lo que requiere buenas [[evaluation|evaluaciones]].",
    whyItMatters: "Permite responder preguntas que requieren combinar información de varios documentos o fuentes.",
    useCases: ["Investigación profunda", "Análisis de documentos múltiples", "Asistentes empresariales avanzados"],
    prerequisites: ["rag", "ai-agent", "tool-calling"],
    relatedTerms: ["rag", "ai-agent", "tool-calling", "planning"],
    nextTerms: ["ai-agent", "multi-agent-system"],
    tags: ["agentes", "rag avanzado", "multi-hop", "deep research"],
  },
];
