import type { TermInput } from "@/types/glossary";

const attentionPaper = {
  title: "Attention Is All You Need",
  authors: "Vaswani et al.",
  year: 2017,
  url: "https://arxiv.org/abs/1706.03762",
  kind: "paper" as const,
};

export const transformerTerms: TermInput[] = [
  {
    slug: "transformer",
    name: "Transformer",
    aliases: ["Transformers", "Arquitectura Transformer", "Transformador"],
    category: "transformers",
    secondaryCategories: ["deep-learning", "llm"],
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition:
      "Una arquitectura de red neuronal que procesa secuencias usando mecanismos de atención para relacionar cada elemento con todos los demás.",
    simpleExplanation:
      "Antes del Transformer, los modelos leían un texto palabra por palabra, en orden, y tendían a «olvidar» lo que venía al principio. El Transformer cambió eso: mira todas las palabras a la vez y decide, para cada una, a cuáles otras debe prestar atención.\n\nEn la frase «El trofeo no cabía en la maleta porque **era** demasiado grande», el Transformer puede aprender que «era» se refiere al trofeo. Esa capacidad de relacionar palabras lejanas es la que hizo posibles a los [[llm|LLMs]].",
    analogy:
      "Imagina una reunión donde cada persona puede escuchar a todas las demás al mismo tiempo y decidir a quién hacerle más caso según el tema. Después de varias rondas de conversación, cada persona tiene una comprensión mucho más rica del contexto.",
    inThirtySeconds: [
      "Recibe tokens.",
      "Los convierte en embeddings y añade información de posición.",
      "Attention identifica qué tokens se relacionan entre sí.",
      "Capas feedforward transforman cada representación.",
      "Tras muchas capas, el modelo produce su salida.",
    ],
    diagram: {
      kind: "flow",
      title: "Dentro de un Transformer",
      steps: [
        { label: "Texto", chips: ["El", "gato", "duerme"] },
        { label: "Tokenización", detail: "El texto se divide en tokens" },
        { label: "Embeddings + posición", detail: "Cada token se vuelve un vector que sabe dónde está" },
        { label: "Self-Attention", detail: "Cada token mira a los demás y toma contexto" },
        { label: "Feedforward", detail: "Cada vector se procesa por separado" },
        { label: "× N capas", detail: "El bloque se repite decenas de veces" },
        { label: "Representación contextual", detail: "Vectores que capturan el significado en contexto" },
      ],
    },
    mentalModel: [
      { label: "Embeddings", meaning: "Qué significa cada token por sí solo." },
      { label: "Attention", meaning: "Con qué otros tokens debe combinarse." },
      { label: "Feedforward", meaning: "Qué conocimiento aplicar a cada token." },
      { label: "Capas apiladas", meaning: "Comprensión cada vez más abstracta." },
    ],
    technicalExplanation:
      "Propuesto por Vaswani et al. (2017) en «Attention Is All You Need», el Transformer reemplazó la recurrencia de las RNNs por [[self-attention]], lo que permite procesar todos los tokens de una secuencia en paralelo durante el entrenamiento.\n\nCada bloque contiene [[multi-head-attention|multi-head attention]] seguida de una [[feedforward-network|red feedforward]] aplicada posición por posición, ambas envueltas en [[residual-connection|conexiones residuales]] y [[layer-normalization]]. Como la atención no distingue el orden por sí sola, se añade [[positional-encoding|codificación posicional]].\n\nExisten tres variantes: solo [[encoder]] (BERT, para comprensión y embeddings), solo [[decoder]] (GPT y la mayoría de los LLMs actuales, para generación) y [[encoder-decoder]] (el diseño original, T5, traducción). La arquitectura también se usa en visión ([[vision-transformer]]), audio y biología.",
    math: {
      formula: "Attention(Q, K, V) = softmax(QKᵀ / √dₖ) · V",
      caption: "La operación central del Transformer (scaled dot-product attention).",
      symbols: [
        { symbol: "Q", meaning: "Queries: lo que cada token está buscando" },
        { symbol: "K", meaning: "Keys: lo que cada token ofrece para ser encontrado" },
        { symbol: "V", meaning: "Values: la información que cada token aporta" },
        { symbol: "QKᵀ", meaning: "Similitud entre cada query y cada key (productos punto)" },
        { symbol: "√dₖ", meaning: "Factor de escala para estabilizar los valores" },
        { symbol: "softmax", meaning: "Convierte las similitudes en pesos que suman 1" },
      ],
      explanation: "El resultado es, para cada token, un promedio ponderado de los values de todos los tokens, donde los pesos dependen de qué tan relevante es cada uno.",
    },
    commonMistakes: [
      "«Transformer» no es un modelo concreto, sino una arquitectura. GPT, Claude, Gemini, Llama o BERT son modelos distintos construidos sobre variantes de ella.",
    ],
    whyItMatters:
      "Es la arquitectura detrás de prácticamente todos los LLMs modernos y de muchos modelos de visión, audio y ciencia. Entenderla es entender la base técnica de la IA actual.",
    useCases: ["Modelos de lenguaje", "Traducción automática", "Visión por computadora", "Reconocimiento de voz", "Predicción de estructuras de proteínas"],
    prerequisites: ["neural-network", "token", "embeddings"],
    relatedTerms: ["attention", "self-attention", "embeddings", "token", "positional-encoding", "llm", "encoder", "decoder"],
    nextTerms: ["self-attention", "llm", "mixture-of-experts"],
    tags: ["arquitectura", "attention", "gpt", "bert", "vaswani"],
    sources: [attentionPaper],
  },
  {
    slug: "attention",
    name: "Attention",
    spanishName: "Mecanismo de atención",
    aliases: ["Atención", "Mecanismo de atención", "Attention mechanism", "Scaled dot-product attention"],
    category: "transformers",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Un mecanismo que permite a un modelo decidir qué partes de la entrada son más relevantes para procesar cada elemento.",
    simpleExplanation:
      "Cuando lees «El banco estaba lleno de peces», tu cerebro usa la palabra «peces» para entender que «banco» se refiere a un grupo de peces y no a una institución financiera. Attention hace algo similar: para cada palabra, calcula cuánto debe fijarse en cada una de las demás.\n\nEl resultado es que cada palabra se enriquece con el contexto que realmente importa.",
    diagram: { kind: "custom", id: "attention", title: "¿A qué presta atención «duerme»?", caption: "El grosor de cada línea representa el peso de atención. Valores ilustrativos." },
    technicalExplanation:
      "Cada token produce tres vectores mediante proyecciones lineales aprendidas: query, key y value ([[query-key-value|QKV]]). El peso de atención entre dos tokens se calcula con el [[dot-product|producto punto]] entre la query de uno y la key del otro, escalado por √dₖ y normalizado con [[softmax]]. La salida es la suma ponderada de los values.\n\nAttention se introdujo en traducción automática (Bahdanau et al., 2014) para modelos recurrentes; el [[transformer]] la convirtió en el componente central. Su costo es cuadrático en la longitud de la secuencia, lo que motiva variantes eficientes y optimizaciones como FlashAttention.",
    math: {
      formula: "Attention(Q, K, V) = softmax(QKᵀ / √dₖ) · V",
      symbols: [
        { symbol: "Q, K, V", meaning: "Matrices de queries, keys y values (una fila por token)" },
        { symbol: "dₖ", meaning: "Dimensión de los vectores key" },
        { symbol: "softmax", meaning: "Normaliza cada fila para que los pesos sumen 1" },
      ],
      explanation:
        "Dividir entre √dₖ evita que los productos punto crezcan demasiado con la dimensión, lo que haría que la softmax se volviera casi un «todo o nada» y dificultaría el entrenamiento.",
    },
    whyItMatters: "Es la idea que permitió a los modelos manejar contexto de forma flexible y escalar a los LLMs actuales.",
    useCases: ["Transformers", "Traducción", "Modelos multimodales", "Resumen de documentos"],
    prerequisites: ["embeddings", "dot-product"],
    relatedTerms: ["self-attention", "multi-head-attention", "query-key-value", "transformer", "softmax"],
    nextTerms: ["self-attention", "query-key-value", "multi-head-attention"],
    tags: ["atención", "contexto", "pesos de atención"],
    sources: [attentionPaper, { title: "Neural Machine Translation by Jointly Learning to Align and Translate", authors: "Bahdanau, Cho & Bengio", year: 2014, url: "https://arxiv.org/abs/1409.0473", kind: "paper" }],
  },
  {
    slug: "self-attention",
    name: "Self-Attention",
    spanishName: "Autoatención",
    aliases: ["Autoatención", "Auto-atención", "Causal attention", "Atención causal"],
    category: "transformers",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Una forma de atención en la que cada elemento de una secuencia se relaciona con los demás elementos de la misma secuencia.",
    simpleExplanation:
      "En self-attention, el texto se «mira a sí mismo». Cada palabra consulta a todas las demás palabras de la misma frase para entender mejor su propio significado.\n\nEn un modelo que genera texto, se añade una regla: cada palabra solo puede mirar hacia atrás, nunca a las palabras futuras (que aún no existen).",
    technicalExplanation:
      "Q, K y V se obtienen de la misma secuencia de entrada, a diferencia de la *cross-attention*, donde las queries vienen de una secuencia y las keys/values de otra (por ejemplo, del [[encoder]] en un [[encoder-decoder]]). En modelos [[decoder]] se usa una **máscara causal** que asigna −∞ a las posiciones futuras antes de la [[softmax]]. Su costo en tiempo y memoria es O(n²) respecto a la longitud n de la secuencia.",
    whyItMatters: "Es lo que permite que cada token tenga una representación que depende de todo su contexto.",
    useCases: ["Todos los Transformers", "Modelos de lenguaje", "Vision Transformers"],
    prerequisites: ["attention"],
    relatedTerms: ["attention", "multi-head-attention", "query-key-value", "kv-cache", "context-window"],
    nextTerms: ["multi-head-attention", "positional-encoding"],
    tags: ["autoatención", "máscara causal"],
    sources: [attentionPaper],
  },
  {
    slug: "multi-head-attention",
    name: "Multi-Head Attention",
    spanishName: "Atención multicabeza",
    aliases: ["Atención multicabeza", "MHA", "Attention heads", "Cabezas de atención", "GQA", "Grouped-query attention"],
    category: "transformers",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Ejecutar varios mecanismos de atención en paralelo para que el modelo capture distintos tipos de relaciones a la vez.",
    simpleExplanation:
      "Una sola atención solo puede fijarse en un tipo de relación a la vez. Con varias «cabezas», una puede seguir la gramática (qué sujeto va con qué verbo), otra las referencias (a quién se refiere «ella») y otra el tema general. Luego se combinan todas las perspectivas.",
    technicalExplanation:
      "Con h cabezas, Q, K y V se proyectan a h subespacios de dimensión d/h, se calcula la atención en cada uno de forma independiente y los resultados se concatenan y proyectan de nuevo. Variantes como **multi-query attention** (MQA) y **grouped-query attention** (GQA) comparten keys y values entre cabezas para reducir el tamaño del [[kv-cache]] y acelerar la inferencia.",
    whyItMatters: "Aumenta la capacidad expresiva de la atención sin multiplicar su costo.",
    useCases: ["Transformers de lenguaje y visión"],
    prerequisites: ["self-attention", "query-key-value"],
    relatedTerms: ["attention", "self-attention", "kv-cache", "transformer"],
    nextTerms: ["kv-cache", "feedforward-network"],
    tags: ["cabezas", "heads", "gqa", "mqa"],
    sources: [attentionPaper, { title: "GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints", authors: "Ainslie et al.", year: 2023, url: "https://arxiv.org/abs/2305.13245", kind: "paper" }],
  },
  {
    slug: "query-key-value",
    name: "Query, Key y Value",
    acronym: "QKV",
    aliases: ["QKV", "Query", "Key", "Value", "Consulta, clave y valor"],
    category: "transformers",
    difficulty: "advanced",
    type: "mathematics",
    shortDefinition: "Los tres vectores que cada token genera en el mecanismo de atención: lo que busca (query), cómo se le encuentra (key) y lo que aporta (value).",
    simpleExplanation:
      "Piensa en una biblioteca. Tu **query** es lo que buscas («libros sobre volcanes»). Cada libro tiene una **key**, como su ficha del catálogo. Comparas tu búsqueda con todas las fichas y, según qué tan bien coinciden, tomas más o menos del **value**: el contenido del libro.\n\nEn attention, cada token hace de lector y de libro al mismo tiempo.",
    technicalExplanation:
      "Dado el vector de un token x, se calculan q = xW_Q, k = xW_K y v = xW_V con matrices de pesos aprendidas. La similitud q·k determina el peso de atención, y la salida es Σ pesos × v. Separar keys de values permite que la información con la que un token es «encontrado» sea distinta de la información que «entrega». Durante la generación, las keys y values de tokens anteriores se guardan en el [[kv-cache]].",
    whyItMatters: "Entender QKV es entender cómo decide el modelo qué información combinar.",
    useCases: ["Attention en Transformers", "Diseño de optimizaciones de inferencia"],
    prerequisites: ["attention", "matrix"],
    relatedTerms: ["attention", "self-attention", "kv-cache", "dot-product"],
    nextTerms: ["multi-head-attention", "kv-cache"],
    tags: ["query", "key", "value", "consulta", "clave", "valor"],
  },
  {
    slug: "encoder",
    name: "Encoder",
    spanishName: "Codificador",
    aliases: ["Codificador", "Encoder-only", "BERT"],
    category: "transformers",
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition: "La parte de un modelo que convierte una entrada en una representación interna rica en contexto.",
    simpleExplanation:
      "Un encoder lee toda la entrada —mirando hacia adelante y hacia atrás— y la resume en vectores que capturan su significado. No genera texto; lo comprende. Es ideal para clasificar, buscar o crear [[embeddings]].",
    technicalExplanation:
      "En un Transformer encoder, la self-attention es **bidireccional** (sin máscara causal). BERT (Devlin et al., 2018) es el ejemplo clásico, preentrenado con enmascaramiento de palabras. Muchos [[embedding-model|modelos de embeddings]] y [[reranking|rerankers]] actuales son encoders.",
    whyItMatters: "Los encoders siguen siendo la opción eficiente para búsqueda, clasificación y embeddings.",
    useCases: ["Embeddings", "Clasificación de texto", "Reranking", "Reconocimiento de entidades"],
    prerequisites: ["transformer"],
    relatedTerms: ["decoder", "encoder-decoder", "embedding-model", "transformer"],
    nextTerms: ["decoder", "encoder-decoder"],
    tags: ["bert", "bidireccional", "comprensión"],
    sources: [{ title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", authors: "Devlin et al.", year: 2018, url: "https://arxiv.org/abs/1810.04805", kind: "paper" }],
  },
  {
    slug: "decoder",
    name: "Decoder",
    spanishName: "Decodificador",
    aliases: ["Decodificador", "Decoder-only", "GPT"],
    category: "transformers",
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition: "La parte de un modelo que genera una secuencia de salida, un elemento a la vez, a partir de lo anterior.",
    simpleExplanation:
      "Un decoder es un generador: escribe token por token, y cada token nuevo depende de los anteriores. La mayoría de los LLMs actuales (GPT, Claude, Llama y otros) son Transformers de tipo «solo decoder».",
    technicalExplanation:
      "Un Transformer decoder-only usa [[self-attention]] con máscara causal y se entrena con [[next-token-prediction|predicción del siguiente token]]. Su simplicidad y buena escalabilidad lo convirtieron en la arquitectura dominante de los LLMs. En el diseño [[encoder-decoder]], el decoder además incluye cross-attention hacia la salida del encoder.",
    whyItMatters: "Es la arquitectura base de casi todos los asistentes de IA actuales.",
    useCases: ["LLMs", "Generación de código", "Chatbots"],
    prerequisites: ["transformer"],
    relatedTerms: ["encoder", "encoder-decoder", "next-token-prediction", "llm"],
    nextTerms: ["llm", "kv-cache"],
    tags: ["gpt", "generación", "decoder-only"],
  },
  {
    slug: "encoder-decoder",
    name: "Encoder-Decoder",
    spanishName: "Codificador-decodificador",
    aliases: ["Codificador-decodificador", "Seq2seq", "Sequence to sequence", "T5"],
    category: "transformers",
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition: "Una arquitectura en la que un encoder comprende la entrada y un decoder genera la salida a partir de esa comprensión.",
    simpleExplanation:
      "Es como un intérprete: primero escucha y entiende toda la frase en un idioma (encoder) y luego la produce en otro idioma (decoder). Fue el diseño original del Transformer, pensado para traducción.",
    technicalExplanation:
      "El decoder usa **cross-attention**: sus queries atienden a las keys y values producidas por el encoder. Modelos como T5 y BART siguen este esquema. Es especialmente eficaz cuando entrada y salida son secuencias distintas (traducción, resumen, reconocimiento de voz como en Whisper).",
    whyItMatters: "Sigue siendo una arquitectura fuerte para tareas de transformación de secuencias.",
    useCases: ["Traducción automática", "Resumen", "Reconocimiento de voz"],
    prerequisites: ["encoder", "decoder"],
    relatedTerms: ["encoder", "decoder", "machine-translation", "transformer"],
    nextTerms: ["machine-translation"],
    tags: ["seq2seq", "t5", "traducción"],
  },
  {
    slug: "positional-encoding",
    name: "Positional Encoding",
    spanishName: "Codificación posicional",
    aliases: ["Codificación posicional", "Positional embeddings", "RoPE", "Rotary embeddings"],
    category: "transformers",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Información que se añade a cada token para que el modelo sepa en qué posición de la secuencia se encuentra.",
    simpleExplanation:
      "Attention, por sí sola, trata el texto como una bolsa de palabras sin orden: «el perro muerde al hombre» y «el hombre muerde al perro» se verían iguales. La codificación posicional le dice al modelo dónde está cada palabra, y así el orden vuelve a importar.",
    technicalExplanation:
      "El Transformer original sumaba vectores sinusoidales de distintas frecuencias a los embeddings. Otras opciones son embeddings de posición aprendidos y, en la mayoría de los LLMs actuales, **RoPE** (*Rotary Position Embedding*), que rota los vectores de query y key según su posición, de modo que el producto punto depende de la distancia relativa entre tokens. Extensiones de RoPE permiten ampliar la [[context-window|ventana de contexto]] tras el entrenamiento.",
    whyItMatters: "Sin ella, los Transformers no podrían entender el orden, esencial en el lenguaje.",
    useCases: ["Transformers de lenguaje", "Extensión de contexto"],
    prerequisites: ["self-attention", "embeddings"],
    relatedTerms: ["transformer", "embeddings", "context-window", "self-attention"],
    nextTerms: ["context-window"],
    tags: ["posición", "orden", "rope", "sinusoidal"],
    sources: [attentionPaper, { title: "RoFormer: Enhanced Transformer with Rotary Position Embedding", authors: "Su et al.", year: 2021, url: "https://arxiv.org/abs/2104.09864", kind: "paper" }],
  },
  {
    slug: "embeddings",
    name: "Embeddings",
    spanishName: "Representaciones vectoriales",
    aliases: ["Embedding", "Incrustaciones", "Vector embeddings", "Representaciones vectoriales", "Word embeddings", "Word2Vec"],
    category: "vector-search",
    secondaryCategories: ["transformers", "rag", "nlp"],
    difficulty: "intermediate",
    type: "concept",
    shortDefinition:
      "Una forma de convertir información como palabras, imágenes o documentos en listas de números que una computadora puede comparar matemáticamente.",
    simpleExplanation:
      "Imagina un enorme mapa donde los conceptos parecidos aparecen cerca unos de otros. «Perro» estaría más cerca de «gato» que de «avión».\n\nUn embedding es la coordenada de cada concepto dentro de ese mapa. La diferencia es que este mapa no tiene 2 dimensiones, sino cientos o miles. Gracias a eso, una computadora puede medir qué tan parecidos son dos textos aunque no compartan ni una palabra.",
    diagram: { kind: "custom", id: "embedding-map", title: "Un espacio de embeddings (simplificado a 2D)", caption: "Los conceptos similares forman grupos. Los embeddings reales tienen cientos o miles de dimensiones." },
    example: {
      title: "De texto a vector",
      description: "Un [[embedding-model|modelo de embeddings]] convierte cualquier texto en un vector de tamaño fijo:",
      code: "\"Apple fabrica el iPhone.\"\n\n        ↓  modelo de embeddings\n\n[0.021, -0.87, 0.31, 0.09, …]   (p. ej. 1,024 números)",
    },
    realExample: {
      title: "Búsqueda que entiende significado",
      description: "Un usuario busca en la documentación de su empresa:",
      flow: [
        "Consulta: «¿cómo pido días libres?»",
        "Se convierte en embedding",
        "Se compara con los embeddings de todos los documentos",
        "El más cercano: «Política de vacaciones y permisos»",
      ],
    },
    technicalExplanation:
      "Un embedding es una representación vectorial densa x ∈ ℝᵈ, donde d suele estar entre unos cientos y algunos miles. Se aprende de forma que conceptos semánticamente similares tiendan a quedar cerca bajo métricas como la [[cosine-similarity|similitud coseno]] o el [[dot-product|producto punto]].\n\nHay dos usos distintos. Dentro de un LLM, la **capa de embedding** convierte cada ID de [[token]] en un vector que el [[transformer]] procesa. Para búsqueda, un [[embedding-model|modelo de embeddings]] (típicamente un [[encoder]]) produce un vector por fragmento de texto completo, entrenado con aprendizaje contrastivo para que textos relacionados queden cerca. Word2Vec (Mikolov et al., 2013) popularizó la idea con el famoso ejemplo rey − hombre + mujer ≈ reina.",
    math: {
      formula: "sim(a, b) = (a · b) / (‖a‖ · ‖b‖)",
      caption: "Similitud coseno entre dos embeddings a y b.",
      symbols: [
        { symbol: "a · b", meaning: "Producto punto de los dos vectores" },
        { symbol: "‖a‖", meaning: "Longitud (norma) del vector a" },
        { symbol: "sim", meaning: "Valor cercano a 1 = muy similares; cercano a 0 = sin relación" },
      ],
    },
    mentalModel: [
      { label: "Embedding", meaning: "Coordenadas de significado." },
      { label: "Espacio de embeddings", meaning: "El mapa donde viven esas coordenadas." },
      { label: "Similitud coseno", meaning: "La regla para medir distancias." },
      { label: "Vector database", meaning: "El catálogo para buscar rápido en millones de puntos." },
    ],
    commonMistakes: [
      "Los números individuales de un embedding no suelen tener un significado interpretable por sí solos («dimensión 12 = tamaño»). El significado está en las posiciones relativas entre vectores.",
    ],
    whyItMatters:
      "Son la forma en que las máquinas representan significado. Sin embeddings no existirían la búsqueda semántica, los sistemas RAG ni los recomendadores modernos.",
    useCases: ["Búsqueda semántica", "Sistemas RAG", "Recomendaciones", "Clasificación", "Clustering", "Detección de duplicados"],
    prerequisites: ["vector", "token"],
    relatedTerms: ["vector", "vector-database", "cosine-similarity", "semantic-search", "rag", "transformer", "embedding-space"],
    nextTerms: ["embedding-model", "vector-database", "semantic-search"],
    tags: ["vectores", "significado", "semántica", "representación"],
    sources: [{ title: "Efficient Estimation of Word Representations in Vector Space (Word2Vec)", authors: "Mikolov et al.", year: 2013, url: "https://arxiv.org/abs/1301.3781", kind: "paper" }],
  },
  {
    slug: "embedding-space",
    name: "Embedding Space",
    spanishName: "Espacio de embeddings",
    aliases: ["Espacio de embeddings", "Espacio vectorial", "Espacio semántico"],
    category: "vector-search",
    secondaryCategories: ["transformers"],
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "El espacio de muchas dimensiones donde viven los embeddings y donde la distancia entre puntos refleja similitud de significado.",
    simpleExplanation:
      "Si cada embedding es una coordenada, el espacio de embeddings es el mapa completo. En él aparecen «barrios» de conceptos relacionados: animales por un lado, vehículos por otro, emociones en otra zona.",
    technicalExplanation:
      "Es un espacio vectorial ℝᵈ con una métrica de similitud. Las direcciones pueden codificar relaciones (por ejemplo, género o tiempo verbal), aunque esta estructura lineal es aproximada. Técnicas como t-SNE o UMAP proyectan el espacio a 2D para visualizarlo, a costa de distorsionar distancias. Cada modelo de embeddings define su propio espacio: los vectores de dos modelos distintos no son comparables entre sí.",
    whyItMatters: "Explica por qué la búsqueda semántica funciona y por qué no se pueden mezclar embeddings de modelos distintos.",
    useCases: ["Visualización de datos", "Clustering", "Búsqueda semántica"],
    prerequisites: ["embeddings"],
    relatedTerms: ["embeddings", "latent-space", "cosine-similarity", "vector-search"],
    nextTerms: ["latent-space", "vector-search"],
    tags: ["espacio vectorial", "mapa", "dimensiones"],
  },
  {
    slug: "latent-space",
    name: "Latent Space",
    spanishName: "Espacio latente",
    aliases: ["Espacio latente", "Representación latente", "Latent representation"],
    category: "deep-learning",
    secondaryCategories: ["generative-ai"],
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "El espacio de representaciones internas y comprimidas que un modelo aprende para describir sus datos.",
    simpleExplanation:
      "Un modelo no guarda imágenes o textos tal cual: los traduce a un «idioma interno» más compacto donde lo importante queda y lo irrelevante se descarta. Ese idioma interno es el espacio latente.\n\nEn generación de imágenes, moverse suavemente por el espacio latente produce transiciones suaves entre imágenes: de un rostro sonriente a uno serio, por ejemplo.",
    technicalExplanation:
      "«Latente» significa oculto: variables no observadas directamente que explican los datos. En autoencoders, el espacio latente es la salida del codificador; en [[latent-diffusion]], la difusión ocurre en ese espacio comprimido en vez de en píxeles; en LLMs, las activaciones de las [[hidden-layer|capas ocultas]] forman un espacio latente que la [[mechanistic-interpretability|interpretabilidad]] intenta descifrar. El [[embedding-space]] es un caso particular.",
    whyItMatters: "Es donde ocurre el «pensamiento» del modelo y donde operan muchas técnicas de generación e interpretabilidad.",
    useCases: ["Generación de imágenes", "Compresión", "Interpretabilidad", "Edición de imágenes"],
    prerequisites: ["embeddings", "hidden-layer"],
    relatedTerms: ["embedding-space", "latent-diffusion", "latent-reasoning", "representation-engineering"],
    nextTerms: ["latent-diffusion", "latent-reasoning"],
    tags: ["latente", "representación interna", "compresión"],
  },
  {
    slug: "feedforward-network",
    name: "Feedforward Network",
    spanishName: "Red feedforward",
    acronym: "FFN",
    aliases: ["Red feedforward", "FFN", "MLP", "Perceptrón multicapa", "Red prealimentada"],
    category: "transformers",
    secondaryCategories: ["deep-learning"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Una red neuronal en la que la información fluye en una sola dirección; en un Transformer, procesa cada token por separado después de la atención.",
    simpleExplanation:
      "Si attention es el momento en que los tokens «se comunican», la capa feedforward es el momento en que cada token «reflexiona» por su cuenta usando el conocimiento que el modelo tiene guardado.\n\nMuchos investigadores piensan que una parte importante del conocimiento factual de un LLM está almacenada en estas capas.",
    technicalExplanation:
      "En un Transformer, la FFN es un MLP de dos capas aplicado posición por posición: FFN(x) = W₂ · σ(W₁x + b₁) + b₂, con una dimensión intermedia típicamente unas 4 veces mayor que la del modelo. Variantes como SwiGLU añaden compuertas. Contiene la mayoría de los parámetros de cada bloque. En arquitecturas [[mixture-of-experts|Mixture of Experts]], esta FFN se reemplaza por varios «expertos» y un [[router]].",
    whyItMatters: "Concentra buena parte de los parámetros y del conocimiento de un Transformer.",
    useCases: ["Bloques de Transformer", "Clasificadores simples", "Expertos en MoE"],
    prerequisites: ["neural-network", "transformer"],
    relatedTerms: ["transformer", "mixture-of-experts", "activation-function", "residual-connection"],
    nextTerms: ["residual-connection", "mixture-of-experts"],
    tags: ["mlp", "ffn", "perceptrón multicapa"],
  },
  {
    slug: "residual-connection",
    name: "Residual Connection",
    spanishName: "Conexión residual",
    aliases: ["Conexión residual", "Skip connection", "ResNet", "Atajo residual"],
    category: "deep-learning",
    secondaryCategories: ["transformers"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Un atajo que suma la entrada de una capa a su salida, facilitando el entrenamiento de redes muy profundas.",
    simpleExplanation:
      "En lugar de que cada capa tenga que reconstruir toda la información desde cero, solo tiene que añadir una «corrección» a lo que ya existía. La información original viaja por una vía rápida y cada capa le hace ajustes.\n\nEsto permite entrenar redes con decenas o cientos de capas sin que la señal se pierda.",
    technicalExplanation:
      "La salida es y = x + F(x), donde F es la transformación de la capa. Introducidas en ResNet (He et al., 2015), mitigan el problema del gradiente que se desvanece: el gradiente puede fluir directamente por el atajo. En Transformers, la secuencia de sumas residuales forma el **residual stream**, un concepto central en [[mechanistic-interpretability|interpretabilidad mecanicista]]: cada capa lee de él y escribe en él.",
    whyItMatters: "Hizo posible el deep learning realmente profundo, incluidos los LLMs.",
    useCases: ["Transformers", "Redes convolucionales profundas"],
    prerequisites: ["layer", "backpropagation"],
    relatedTerms: ["layer-normalization", "transformer", "backpropagation", "deep-learning"],
    nextTerms: ["layer-normalization"],
    tags: ["resnet", "skip connection", "residual stream"],
    sources: [{ title: "Deep Residual Learning for Image Recognition", authors: "He et al.", year: 2015, url: "https://arxiv.org/abs/1512.03385", kind: "paper" }],
  },
  {
    slug: "layer-normalization",
    name: "Layer Normalization",
    spanishName: "Normalización de capa",
    aliases: ["Normalización de capa", "LayerNorm", "RMSNorm", "Batch normalization"],
    category: "deep-learning",
    secondaryCategories: ["transformers"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Una técnica que reescala los valores dentro de cada capa para mantenerlos en un rango estable y hacer el entrenamiento más confiable.",
    simpleExplanation:
      "Al pasar por muchas capas, los números pueden crecer o encogerse demasiado, lo que desestabiliza el aprendizaje. La normalización los «recentra» en cada paso, como ajustar el volumen para que no sature ni se vuelva inaudible.",
    technicalExplanation:
      "LayerNorm (Ba et al., 2016) normaliza cada vector restando su media y dividiendo entre su desviación estándar, y luego aplica una escala y un desplazamiento aprendidos. A diferencia de *batch normalization*, no depende del tamaño del batch, lo que la hace adecuada para secuencias. Muchos LLMs usan **RMSNorm**, una variante más simple sin centrado, y la colocan antes de cada subcapa (*pre-norm*) para mayor estabilidad.",
    whyItMatters: "Es una pieza pequeña pero esencial para que los Transformers grandes entrenen de forma estable.",
    useCases: ["Transformers", "Redes recurrentes"],
    prerequisites: ["layer"],
    relatedTerms: ["residual-connection", "transformer", "bias"],
    nextTerms: ["transformer"],
    tags: ["layernorm", "rmsnorm", "estabilidad"],
    sources: [{ title: "Layer Normalization", authors: "Ba, Kiros & Hinton", year: 2016, url: "https://arxiv.org/abs/1607.06450", kind: "paper" }],
  },
  {
    slug: "kv-cache",
    name: "KV Cache",
    spanishName: "Caché de keys y values",
    aliases: ["KV-cache", "Key-value cache", "Caché KV", "Prompt caching", "PagedAttention"],
    category: "ai-engineering",
    secondaryCategories: ["transformers", "llm"],
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Una memoria que guarda las keys y values ya calculadas de los tokens anteriores para no recalcularlas en cada paso de generación.",
    simpleExplanation:
      "Al generar texto, un LLM produce un token a la vez. Sin caché, para cada token nuevo tendría que volver a procesar todo el texto anterior desde cero. El KV cache guarda el trabajo ya hecho, así que cada paso solo calcula lo del token nuevo.\n\nEs como tomar notas mientras lees un libro: no necesitas releer desde la primera página para entender el siguiente párrafo.",
    technicalExplanation:
      "En cada capa de atención, las [[query-key-value|keys y values]] de los tokens previos se almacenan; en el paso t solo se calculan q, k, v del nuevo token y se atiende sobre el caché. Esto reduce el costo de generación de cuadrático a lineal por token, pero el caché ocupa mucha memoria: crece con capas × cabezas × dimensión × longitud × batch.\n\nOptimizaciones: GQA/MQA (menos keys/values), cuantización del caché, **PagedAttention** (gestión de memoria por páginas, usada en vLLM) y **prompt caching**, que reutiliza el caché de prefijos repetidos (como un system prompt largo) entre solicitudes para reducir costo y [[latency|latencia]].",
    whyItMatters: "Es clave para que la generación de texto sea rápida y asequible, y es uno de los principales consumidores de [[vram|VRAM]] en inferencia.",
    useCases: ["Servir LLMs", "Contextos largos", "Prompt caching en APIs"],
    prerequisites: ["query-key-value", "inference"],
    relatedTerms: ["inference-optimization", "multi-head-attention", "vram", "context-window", "latency"],
    nextTerms: ["speculative-decoding", "inference-optimization"],
    tags: ["caché", "memoria", "generación", "vllm"],
    sources: [{ title: "Efficient Memory Management for Large Language Model Serving with PagedAttention", authors: "Kwon et al.", year: 2023, url: "https://arxiv.org/abs/2309.06180", kind: "paper" }],
  },
];
