import type { TermInput } from "@/types/glossary";

export const visionTerms: TermInput[] = [
  {
    slug: "computer-vision",
    name: "Computer Vision",
    spanishName: "Visión por computadora",
    aliases: ["Visión por computadora", "Visión artificial", "Visión computacional", "CV"],
    category: "computer-vision",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "El campo de la IA que permite a las computadoras interpretar y entender imágenes y video.",
    simpleExplanation:
      "Para una computadora, una foto es solo una tabla enorme de números (los píxeles). La visión por computadora le enseña a pasar de esos números a conceptos: «aquí hay un perro», «esta persona sonríe», «este tumor mide 2 cm».",
    technicalExplanation:
      "Tareas principales: [[image-classification|clasificación]], [[object-detection|detección de objetos]], [[image-segmentation|segmentación]], estimación de pose, seguimiento en video, reconstrucción 3D y [[image-generation|generación de imágenes]]. Durante la década de 2010 dominaron las [[cnn|CNNs]]; hoy conviven con [[vision-transformer|Vision Transformers]] y [[multimodal-model|modelos multimodales]] que combinan visión y lenguaje.",
    whyItMatters: "Permite automatizar tareas que dependen de la vista: inspección, diagnóstico, conducción, accesibilidad.",
    useCases: ["Imágenes médicas", "Vehículos autónomos", "Control de calidad industrial", "Desbloqueo facial", "Lectura de documentos"],
    prerequisites: ["deep-learning"],
    relatedTerms: ["cnn", "vision-transformer", "object-detection", "image-segmentation", "multimodal-model"],
    nextTerms: ["cnn", "image-classification", "vision-transformer"],
    tags: ["visión", "imágenes", "video", "cv"],
  },
  {
    slug: "cnn",
    name: "Convolutional Neural Network",
    spanishName: "Red neuronal convolucional",
    acronym: "CNN",
    aliases: ["CNN", "Red convolucional", "Red neuronal convolucional", "ConvNet"],
    category: "computer-vision",
    secondaryCategories: ["deep-learning"],
    difficulty: "intermediate",
    type: "architecture",
    shortDefinition: "Un tipo de red neuronal diseñado para imágenes que aprende a detectar patrones locales —bordes, texturas, formas— usando filtros que recorren la imagen.",
    simpleExplanation:
      "En lugar de mirar toda la imagen de golpe, una CNN la examina por partes con pequeños «filtros», como una lupa que se desliza. Las primeras capas detectan bordes; las siguientes, combinaciones como esquinas y texturas; las últimas, objetos completos como ruedas u ojos.",
    technicalExplanation:
      "Se compone de capas de [[convolution|convolución]] (filtros aprendidos compartidos en toda la imagen), activaciones no lineales y *pooling* para reducir la resolución. Dos sesgos inductivos la hacen eficiente: localidad (cada neurona mira una región pequeña) y compartición de pesos (el mismo filtro sirve en cualquier posición), lo que da cierta invariancia a traslaciones. Hitos: LeNet (1998), AlexNet (2012, que impulsó la revolución del deep learning), VGG y ResNet.",
    whyItMatters: "Fueron la arquitectura que demostró el poder del deep learning y siguen siendo muy usadas en visión eficiente.",
    useCases: ["Clasificación de imágenes", "Detección de objetos", "Imágenes médicas", "Visión en dispositivos"],
    prerequisites: ["neural-network", "convolution"],
    relatedTerms: ["convolution", "computer-vision", "vision-transformer", "residual-connection"],
    nextTerms: ["image-classification", "vision-transformer"],
    tags: ["convolucional", "resnet", "alexnet", "filtros"],
    sources: [{ title: "Gradient-based learning applied to document recognition", authors: "LeCun, Bottou, Bengio & Haffner", year: 1998, url: "https://ieeexplore.ieee.org/document/726791", kind: "paper" }],
  },
  {
    slug: "convolution",
    name: "Convolution",
    spanishName: "Convolución",
    aliases: ["Convolución", "Filtro convolucional", "Kernel"],
    category: "computer-vision",
    secondaryCategories: ["math"],
    difficulty: "intermediate",
    type: "mathematics",
    shortDefinition: "Una operación que desliza un pequeño filtro sobre una imagen (u otra señal) y calcula en cada posición qué tanto coincide con un patrón.",
    simpleExplanation:
      "Imagina una plantilla de 3×3 que detecta líneas verticales. La deslizas por toda la imagen y en cada posición anotas qué tan bien coincide. El resultado es un nuevo mapa que resalta dónde hay líneas verticales. Una CNN aprende cientos de plantillas así por sí sola.",
    technicalExplanation:
      "Para cada posición se calcula la suma de productos elemento a elemento entre el filtro (kernel) y la región de la entrada: técnicamente, en deep learning suele ser una correlación cruzada. Hiperparámetros: tamaño del kernel, *stride* (paso), *padding* y número de canales de salida. Cada canal de salida es un «mapa de características».",
    whyItMatters: "Es la operación básica que permitió a las máquinas «ver» de forma eficiente.",
    useCases: ["CNNs", "Procesamiento de audio", "Filtros de imagen"],
    prerequisites: ["matrix", "dot-product"],
    relatedTerms: ["cnn", "computer-vision", "tensor"],
    nextTerms: ["cnn"],
    tags: ["filtro", "kernel", "stride"],
  },
  {
    slug: "image-classification",
    name: "Image Classification",
    spanishName: "Clasificación de imágenes",
    aliases: ["Clasificación de imágenes", "ImageNet"],
    category: "computer-vision",
    difficulty: "beginner",
    type: "technique",
    shortDefinition: "La tarea de asignar una etiqueta a una imagen completa, por ejemplo «gato», «perro» o «avión».",
    simpleExplanation:
      "Es la tarea más básica de visión: ver una foto y decir qué es. La respuesta es una sola etiqueta (o una lista de probabilidades) para toda la imagen.",
    technicalExplanation:
      "Se entrena con [[supervised-learning|aprendizaje supervisado]] y pérdida de [[cross-entropy]], con una [[softmax]] sobre las clases. El benchmark ImageNet (1,000 clases) impulsó gran parte del progreso de la década de 2010. Hoy, modelos preentrenados como CLIP permiten clasificación [[zero-shot-learning|zero-shot]] comparando imágenes con descripciones en texto.",
    whyItMatters: "Es la base de muchas aplicaciones y el punto de partida para entender la visión por computadora.",
    useCases: ["Moderación de imágenes", "Organización de fotos", "Diagnóstico asistido", "Control de calidad"],
    prerequisites: ["computer-vision", "supervised-learning"],
    relatedTerms: ["object-detection", "cnn", "image-segmentation", "softmax"],
    nextTerms: ["object-detection", "image-segmentation"],
    tags: ["clasificar", "imagenet", "etiquetas"],
  },
  {
    slug: "object-detection",
    name: "Object Detection",
    spanishName: "Detección de objetos",
    aliases: ["Detección de objetos", "YOLO", "Bounding boxes", "Cajas delimitadoras"],
    category: "computer-vision",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Encontrar qué objetos hay en una imagen y dónde están, marcando cada uno con un recuadro y una etiqueta.",
    simpleExplanation:
      "La clasificación dice «hay un perro». La detección dice «hay un perro aquí, dos personas allá y una bicicleta en esta esquina», dibujando un rectángulo alrededor de cada uno.",
    technicalExplanation:
      "El modelo predice cajas delimitadoras (coordenadas), clases y puntuaciones de confianza. Familias: detectores de dos etapas (R-CNN y sucesores), de una etapa (YOLO, SSD) y basados en Transformers (DETR). Se evalúa con mAP usando IoU (intersección sobre unión) entre cajas predichas y reales. Se usa supresión de no máximos para eliminar detecciones duplicadas.",
    whyItMatters: "Es clave en cualquier sistema que necesita localizar cosas en el mundo físico.",
    useCases: ["Vehículos autónomos", "Videovigilancia", "Conteo en inventarios", "Robótica"],
    prerequisites: ["image-classification"],
    relatedTerms: ["image-segmentation", "image-classification", "cnn", "computer-vision"],
    nextTerms: ["image-segmentation"],
    tags: ["yolo", "cajas", "localización"],
    sources: [{ title: "You Only Look Once: Unified, Real-Time Object Detection", authors: "Redmon et al.", year: 2015, url: "https://arxiv.org/abs/1506.02640", kind: "paper" }],
  },
  {
    slug: "image-segmentation",
    name: "Segmentation",
    spanishName: "Segmentación de imágenes",
    aliases: ["Segmentación", "Segmentación de imágenes", "Image segmentation", "Semantic segmentation", "Segment Anything"],
    category: "computer-vision",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Clasificar cada píxel de una imagen para delimitar con precisión la forma exacta de cada objeto o región.",
    simpleExplanation:
      "En vez de un rectángulo aproximado, la segmentación «colorea» exactamente los píxeles que pertenecen a cada cosa: el contorno preciso de una persona, la carretera, el cielo. Es lo que permite, por ejemplo, recortar el fondo de una foto.",
    technicalExplanation:
      "Variantes: **semántica** (una clase por píxel), **de instancias** (distingue objetos individuales de la misma clase) y **panóptica** (combina ambas). Arquitecturas clásicas: U-Net (muy usada en medicina), Mask R-CNN. Segment Anything (Kirillov et al., 2023) introdujo un modelo que segmenta objetos a partir de indicaciones como un clic o una caja.",
    whyItMatters: "Aporta la precisión necesaria en medicina, conducción autónoma y edición de imágenes.",
    useCases: ["Imágenes médicas", "Conducción autónoma", "Edición de fotos", "Agricultura de precisión"],
    prerequisites: ["object-detection"],
    relatedTerms: ["object-detection", "image-classification", "computer-vision"],
    nextTerms: ["vision-transformer"],
    tags: ["píxeles", "máscaras", "u-net", "sam"],
    sources: [{ title: "Segment Anything", authors: "Kirillov et al.", year: 2023, url: "https://arxiv.org/abs/2304.02643", kind: "paper" }],
  },
  {
    slug: "vision-transformer",
    name: "Vision Transformer",
    acronym: "ViT",
    aliases: ["ViT", "Transformer de visión"],
    category: "computer-vision",
    secondaryCategories: ["transformers"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Una adaptación del Transformer a imágenes que divide la imagen en parches y los trata como si fueran tokens.",
    simpleExplanation:
      "Un Transformer está diseñado para secuencias de palabras. El truco del ViT es cortar la imagen en cuadritos (por ejemplo, de 16×16 píxeles) y tratar cada cuadrito como si fuera una palabra. A partir de ahí, funciona como cualquier Transformer.",
    technicalExplanation:
      "Dosovitskiy et al. (2020) mostraron que un Transformer estándar aplicado a secuencias de parches proyectados linealmente, con [[positional-encoding|codificación posicional]] y un token de clasificación, puede igualar o superar a las CNNs cuando se preentrena con suficientes datos. Al tener menos sesgos inductivos que una CNN, necesita más datos, pero escala mejor. Los ViT son el codificador visual típico de los [[multimodal-model|modelos multimodales]].",
    whyItMatters: "Unificó visión y lenguaje bajo la misma arquitectura, facilitando la IA multimodal.",
    useCases: ["Clasificación de imágenes", "Codificadores de modelos multimodales", "Segmentación"],
    prerequisites: ["transformer", "computer-vision"],
    relatedTerms: ["transformer", "cnn", "multimodal-model", "computer-vision"],
    nextTerms: ["multimodal-model"],
    tags: ["vit", "parches", "patches"],
    sources: [{ title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale", authors: "Dosovitskiy et al.", year: 2020, url: "https://arxiv.org/abs/2010.11929", kind: "paper" }],
  },
  {
    slug: "diffusion-model",
    name: "Diffusion Model",
    spanishName: "Modelo de difusión",
    aliases: ["Modelo de difusión", "Modelos de difusión", "DDPM", "Difusión"],
    category: "generative-ai",
    secondaryCategories: ["computer-vision"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Un modelo generativo que aprende a crear imágenes (u otros datos) partiendo de ruido aleatorio y eliminándolo paso a paso.",
    simpleExplanation:
      "Durante el entrenamiento, se toman imágenes reales y se les añade ruido poco a poco hasta que son pura estática. El modelo aprende el proceso inverso: dada una imagen con ruido, quitar un poco de ruido.\n\nPara generar, se empieza con estática pura y se aplica ese «limpiador» muchas veces. Guiado por tu descripción en texto, el ruido se va convirtiendo en una imagen nueva.",
    analogy:
      "Es como un escultor que ve una forma dentro de un bloque de mármol y la revela quitando material poco a poco. Aquí, el «mármol» es ruido y la descripción de texto indica qué forma revelar.",
    diagram: {
      kind: "flow",
      title: "Generar una imagen con difusión",
      steps: [
        { label: "Prompt", detail: "«Un faro al atardecer, acuarela»" },
        { label: "Ruido aleatorio", detail: "Se parte de estática pura" },
        { label: "Eliminar ruido × N pasos", detail: "En cada paso el modelo predice y quita un poco de ruido, guiado por el texto" },
        { label: "Imagen final", detail: "Una imagen nueva que coincide con la descripción" },
      ],
    },
    technicalExplanation:
      "El proceso *forward* añade ruido gaussiano según un calendario hasta destruir la señal; una red (tradicionalmente una U-Net, cada vez más Transformers de difusión) aprende a predecir el ruido añadido en cada nivel (Ho et al., 2020, DDPM, a partir de ideas de Sohl-Dickstein et al., 2015). La generación invierte el proceso iterativamente. El condicionamiento por texto usa embeddings de un codificador de texto y *classifier-free guidance* para seguir el prompt. Muestreadores más eficientes reducen el número de pasos. La variante [[latent-diffusion|latente]] opera en un espacio comprimido.",
    whyItMatters: "Son la tecnología detrás de la mayoría de los generadores de imágenes y muchos de video actuales.",
    useCases: ["Generación de imágenes", "Edición de imágenes", "Video", "Audio", "Diseño de moléculas"],
    prerequisites: ["generative-ai", "neural-network"],
    relatedTerms: ["latent-diffusion", "image-generation", "gan", "generative-ai"],
    nextTerms: ["latent-diffusion", "image-generation"],
    tags: ["difusión", "ruido", "stable diffusion", "imágenes"],
    sources: [
      { title: "Denoising Diffusion Probabilistic Models", authors: "Ho, Jain & Abbeel", year: 2020, url: "https://arxiv.org/abs/2006.11239", kind: "paper" },
      { title: "Deep Unsupervised Learning using Nonequilibrium Thermodynamics", authors: "Sohl-Dickstein et al.", year: 2015, url: "https://arxiv.org/abs/1503.03585", kind: "paper" },
    ],
  },
  {
    slug: "latent-diffusion",
    name: "Latent Diffusion",
    spanishName: "Difusión latente",
    aliases: ["Difusión latente", "Latent diffusion model", "LDM", "Stable Diffusion"],
    category: "generative-ai",
    secondaryCategories: ["computer-vision"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Un modelo de difusión que trabaja en un espacio comprimido de la imagen en lugar de en sus píxeles, lo que lo hace mucho más eficiente.",
    simpleExplanation:
      "Quitar ruido píxel por píxel en una imagen grande es carísimo. La difusión latente primero comprime la imagen a una representación mucho más pequeña, hace todo el trabajo de difusión ahí y al final la «descomprime» a una imagen completa.",
    technicalExplanation:
      "Rombach et al. (2021) usaron un autoencoder para mapear imágenes a un [[latent-space|espacio latente]] de menor resolución (por ejemplo, 8× menor por lado), entrenaron la difusión en ese espacio y condicionaron con texto mediante cross-attention. Esta arquitectura es la base de Stable Diffusion y redujo drásticamente el costo de entrenar y generar.",
    whyItMatters: "Hizo posible generar imágenes de alta calidad en hardware de consumo.",
    useCases: ["Generación de imágenes", "Inpainting", "Superresolución"],
    prerequisites: ["diffusion-model", "latent-space"],
    relatedTerms: ["diffusion-model", "latent-space", "image-generation"],
    nextTerms: ["image-generation"],
    tags: ["stable diffusion", "latente", "autoencoder"],
    sources: [{ title: "High-Resolution Image Synthesis with Latent Diffusion Models", authors: "Rombach et al.", year: 2021, url: "https://arxiv.org/abs/2112.10752", kind: "paper" }],
  },
  {
    slug: "image-generation",
    name: "Image Generation",
    spanishName: "Generación de imágenes",
    aliases: ["Generación de imágenes", "Text-to-image", "Texto a imagen", "Generar imágenes"],
    category: "generative-ai",
    secondaryCategories: ["computer-vision"],
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Crear imágenes nuevas con IA, normalmente a partir de una descripción en texto.",
    simpleExplanation:
      "Escribes «un gato astronauta en estilo acuarela» y el modelo crea una imagen que nunca existió. Detrás hay modelos que aprendieron, a partir de millones de pares de imagen y texto, cómo se relacionan las palabras con formas, colores y estilos.",
    technicalExplanation:
      "Las técnicas dominantes son los [[diffusion-model|modelos de difusión]] (incluida la [[latent-diffusion|difusión latente]]) y, cada vez más, modelos autoregresivos o [[multimodal-model|multimodales]] que generan imágenes como tokens. Históricamente, las [[gan|GANs]] fueron el estado del arte. Capacidades comunes: edición guiada por texto, inpainting, control por bocetos o poses y consistencia de personajes. Temas abiertos: derechos de autor de los datos de entrenamiento, deepfakes y marcas de agua para identificar contenido generado.",
    whyItMatters: "Transformó el diseño, la publicidad y la creación de contenido, y plantea preguntas importantes de autenticidad.",
    useCases: ["Diseño y prototipado visual", "Publicidad", "Ilustración", "Edición de fotos"],
    prerequisites: ["generative-ai"],
    relatedTerms: ["diffusion-model", "latent-diffusion", "gan", "multimodal-model"],
    nextTerms: ["diffusion-model"],
    tags: ["texto a imagen", "arte", "ilustración"],
  },
  {
    slug: "gan",
    name: "Generative Adversarial Network",
    spanishName: "Red generativa adversaria",
    acronym: "GAN",
    aliases: ["GAN", "GANs", "Red generativa adversaria", "Redes generativas antagónicas"],
    category: "generative-ai",
    secondaryCategories: ["deep-learning"],
    difficulty: "advanced",
    type: "architecture",
    shortDefinition: "Un modelo generativo formado por dos redes que compiten: una genera datos falsos y otra intenta distinguirlos de los reales.",
    simpleExplanation:
      "Es como un falsificador de billetes y un detective. El falsificador (generador) intenta crear billetes que parezcan reales; el detective (discriminador) intenta detectarlos. Ambos mejoran compitiendo, hasta que las falsificaciones son muy convincentes.",
    technicalExplanation:
      "Propuestas por Goodfellow et al. (2014). El generador G transforma ruido en muestras; el discriminador D estima la probabilidad de que una muestra sea real. Se entrenan con un juego minimax. Son rápidas al generar (un solo paso), pero su entrenamiento es inestable y pueden sufrir *mode collapse* (generar poca variedad). StyleGAN logró rostros fotorrealistas; hoy los modelos de difusión dominan la generación de imágenes.",
    whyItMatters: "Fueron el primer gran salto en generación realista de imágenes y siguen usándose donde la velocidad importa.",
    useCases: ["Rostros sintéticos", "Superresolución", "Transferencia de estilo"],
    prerequisites: ["neural-network", "generative-ai"],
    relatedTerms: ["diffusion-model", "image-generation", "generative-ai"],
    nextTerms: ["diffusion-model"],
    tags: ["gan", "adversarial", "stylegan"],
    sources: [{ title: "Generative Adversarial Networks", authors: "Goodfellow et al.", year: 2014, url: "https://arxiv.org/abs/1406.2661", kind: "paper" }],
  },
];

export const nlpTerms: TermInput[] = [
  {
    slug: "nlp",
    name: "Natural Language Processing",
    spanishName: "Procesamiento de lenguaje natural",
    acronym: "NLP",
    aliases: ["NLP", "PLN", "Procesamiento de lenguaje natural", "Procesamiento del lenguaje natural"],
    category: "nlp",
    difficulty: "intermediate",
    type: "concept",
    shortDefinition: "El campo de la IA dedicado a que las computadoras entiendan, analicen y generen lenguaje humano.",
    simpleExplanation:
      "El lenguaje humano es ambiguo, lleno de contexto, ironía y dobles sentidos. El NLP busca que las máquinas puedan trabajar con él: traducir, resumir, responder preguntas, detectar emociones o extraer datos de documentos.\n\nLos [[llm|LLMs]] son hoy la herramienta más poderosa del NLP.",
    technicalExplanation:
      "Históricamente combinó lingüística y estadística: n-gramas, modelos ocultos de Markov y features diseñadas a mano. Luego llegaron los [[embeddings]] de palabras (Word2Vec), las redes recurrentes y el [[transformer]]. Tareas clásicas: [[tokenization|tokenización]], etiquetado gramatical, [[named-entity-recognition|reconocimiento de entidades]], [[sentiment-analysis|análisis de sentimiento]], [[machine-translation|traducción]], resumen y respuesta a preguntas. Muchas de estas tareas hoy se resuelven con un solo LLM mediante prompting.",
    whyItMatters: "El lenguaje es la interfaz más natural entre personas y máquinas.",
    useCases: ["Traducción", "Chatbots", "Análisis de opiniones", "Extracción de información", "Búsqueda"],
    prerequisites: ["machine-learning"],
    relatedTerms: ["llm", "tokenization", "sentiment-analysis", "machine-translation", "named-entity-recognition"],
    nextTerms: ["tokenization", "llm"],
    tags: ["lenguaje", "texto", "pln"],
  },
  {
    slug: "sentiment-analysis",
    name: "Sentiment Analysis",
    spanishName: "Análisis de sentimiento",
    aliases: ["Análisis de sentimiento", "Análisis de sentimientos", "Opinion mining"],
    category: "nlp",
    difficulty: "beginner",
    type: "technique",
    shortDefinition: "Identificar automáticamente si un texto expresa una opinión positiva, negativa o neutral.",
    simpleExplanation:
      "Una empresa recibe 10,000 reseñas al día. El análisis de sentimiento las clasifica automáticamente: «me encantó» → positiva; «llegó roto» → negativa. Así se detectan problemas rápido sin leer todo a mano.",
    technicalExplanation:
      "Es un problema de clasificación de texto. Se resolvía con diccionarios de palabras y modelos clásicos; luego con [[encoder|encoders]] ajustados. Hoy los LLMs lo resuelven [[zero-shot-learning|zero-shot]]. Variantes más finas: sentimiento por aspecto («la batería es mala, pero la pantalla excelente») y detección de emociones. La ironía y el contexto cultural siguen siendo difíciles.",
    whyItMatters: "Es una de las aplicaciones de NLP más usadas en negocio.",
    useCases: ["Análisis de reseñas", "Monitoreo de redes sociales", "Encuestas de satisfacción"],
    prerequisites: ["nlp", "supervised-learning"],
    relatedTerms: ["nlp", "named-entity-recognition", "zero-shot-learning"],
    nextTerms: ["named-entity-recognition"],
    tags: ["opiniones", "emociones", "reseñas"],
  },
  {
    slug: "named-entity-recognition",
    name: "Named Entity Recognition",
    spanishName: "Reconocimiento de entidades nombradas",
    acronym: "NER",
    aliases: ["NER", "Reconocimiento de entidades", "Extracción de entidades"],
    category: "nlp",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Detectar y clasificar en un texto nombres de personas, organizaciones, lugares, fechas, cantidades y otras entidades.",
    simpleExplanation:
      "En «Ana López firmó con Bimbo en Monterrey el 3 de marzo», un sistema NER marca: Ana López (persona), Bimbo (organización), Monterrey (lugar), 3 de marzo (fecha). Es un paso clave para convertir texto libre en datos estructurados.",
    technicalExplanation:
      "Se modela como etiquetado de secuencias (esquemas BIO) con CRFs, redes recurrentes o encoders tipo BERT. Con LLMs se resuelve mediante [[structured-output|salida estructurada]]. Retos: entidades ambiguas, dominios especializados (medicina, derecho) y textos informales.",
    whyItMatters: "Permite extraer información útil de grandes volúmenes de documentos.",
    useCases: ["Procesamiento de contratos", "Anonimización de datos", "Indexación de noticias"],
    prerequisites: ["nlp"],
    relatedTerms: ["nlp", "structured-output", "encoder"],
    nextTerms: ["structured-output"],
    tags: ["entidades", "extracción", "ner"],
  },
  {
    slug: "machine-translation",
    name: "Machine Translation",
    spanishName: "Traducción automática",
    aliases: ["Traducción automática", "MT", "Neural machine translation", "NMT"],
    category: "nlp",
    difficulty: "intermediate",
    type: "technique",
    shortDefinition: "Traducir texto o voz de un idioma a otro de forma automática.",
    simpleExplanation:
      "Uno de los sueños más antiguos de la IA. Pasó de reglas gramaticales escritas a mano, a modelos estadísticos, a redes neuronales. Curiosamente, el [[transformer]] se inventó precisamente para mejorar la traducción.",
    technicalExplanation:
      "La traducción neuronal (NMT) usa arquitecturas [[encoder-decoder]] con [[attention]]. Se evalúa con métricas automáticas como BLEU o COMET y con evaluación humana. Los LLMs multilingües traducen bien sin entrenamiento específico, aunque la calidad cae en idiomas con pocos datos. Retos: terminología especializada, contexto de documento completo, registro y variantes regionales (por ejemplo, español de México vs. de España).",
    whyItMatters: "Rompe barreras de idioma para miles de millones de personas.",
    useCases: ["Traducción de documentos", "Subtítulos", "Soporte multilingüe", "Localización de software"],
    prerequisites: ["nlp", "encoder-decoder"],
    relatedTerms: ["encoder-decoder", "attention", "transformer", "nlp"],
    nextTerms: ["transformer"],
    tags: ["traducción", "idiomas", "multilingüe"],
  },
];

export const rlTerms: TermInput[] = [
  {
    slug: "policy",
    name: "Policy",
    spanishName: "Política",
    aliases: ["Política", "Política del agente"],
    category: "reinforcement-learning",
    difficulty: "advanced",
    type: "concept",
    shortDefinition: "En aprendizaje por refuerzo, la estrategia que usa un agente para decidir qué acción tomar en cada situación.",
    simpleExplanation:
      "La política es el «manual de decisiones» del agente: ante esta situación, haz esto. Aprender por refuerzo consiste en mejorar ese manual a partir de las recompensas. En [[rlhf]], la política es el propio LLM.",
    technicalExplanation:
      "Formalmente, π(a|s) es una distribución de probabilidad sobre acciones dado un estado (política estocástica) o una función s → a (determinista). Los métodos de *policy gradient* (REINFORCE, PPO) optimizan directamente sus parámetros para maximizar la recompensa esperada. En LLMs, el «estado» es el texto hasta el momento y la «acción» es el siguiente token.",
    whyItMatters: "Es el objeto que realmente se aprende en RL.",
    useCases: ["Robótica", "Juegos", "RLHF"],
    prerequisites: ["reinforcement-learning"],
    relatedTerms: ["reinforcement-learning", "reward-function", "q-learning", "rlhf"],
    nextTerms: ["reward-function", "exploration-exploitation"],
    tags: ["política", "estrategia", "ppo"],
  },
  {
    slug: "reward-function",
    name: "Reward Function",
    spanishName: "Función de recompensa",
    aliases: ["Recompensa", "Reward", "Función de recompensa", "Reward hacking", "Señal de recompensa"],
    category: "reinforcement-learning",
    secondaryCategories: ["safety"],
    difficulty: "advanced",
    type: "concept",
    shortDefinition: "La regla que asigna un valor numérico a lo que hace un agente, indicándole qué tan bien lo está haciendo.",
    simpleExplanation:
      "Es la forma de decirle al agente qué queremos. En un videojuego puede ser la puntuación. El problema es que el agente optimiza **exactamente** la recompensa, no lo que teníamos en mente: si premias «terminar rápido» sin más, podría encontrar un atajo absurdo.",
    technicalExplanation:
      "r(s, a) define el objetivo del problema de RL. Diseñarla bien es difícil: recompensas escasas dificultan el aprendizaje y recompensas mal especificadas producen **reward hacking** (explotar huecos en la definición). Esto conecta con la ley de Goodhart y con [[alignment|alineación]]. Cuando es difícil definirla, se aprende de preferencias humanas con un [[reward-model|modelo de recompensa]].",
    whyItMatters: "Define el comportamiento que surgirá; una recompensa mal diseñada produce agentes que «cumplen» de formas no deseadas.",
    useCases: ["Diseño de agentes", "Robótica", "Alineación de modelos"],
    prerequisites: ["reinforcement-learning"],
    relatedTerms: ["reward-model", "policy", "alignment", "reinforcement-learning"],
    nextTerms: ["reward-model", "alignment"],
    tags: ["recompensa", "reward hacking", "goodhart"],
  },
  {
    slug: "exploration-exploitation",
    name: "Exploration vs. Exploitation",
    spanishName: "Exploración vs. explotación",
    aliases: ["Exploración y explotación", "Exploration-exploitation tradeoff", "Epsilon-greedy", "Multi-armed bandit"],
    category: "reinforcement-learning",
    difficulty: "advanced",
    type: "concept",
    shortDefinition: "El dilema entre aprovechar lo que ya se sabe que funciona y probar opciones nuevas que podrían ser mejores.",
    simpleExplanation:
      "¿Vas a tu restaurante favorito (explotar lo conocido) o pruebas uno nuevo que podría ser mejor o peor (explorar)? Si nunca exploras, te pierdes opciones mejores; si siempre exploras, nunca disfrutas de lo que ya sabes que es bueno. Los agentes de RL enfrentan este dilema constantemente.",
    technicalExplanation:
      "Estrategias: ε-greedy (elegir al azar con probabilidad ε), muestreo de Thompson, cotas de confianza superiores (UCB) y bonificaciones por curiosidad. El problema de los *multi-armed bandits* es su formulación más simple y se usa en pruebas A/B adaptativas y recomendaciones.",
    whyItMatters: "Aparece en cualquier sistema que aprende de la interacción: recomendaciones, anuncios, robótica.",
    useCases: ["Sistemas de recomendación", "Pruebas A/B adaptativas", "Robótica"],
    prerequisites: ["reinforcement-learning"],
    relatedTerms: ["policy", "reinforcement-learning", "q-learning"],
    nextTerms: ["q-learning"],
    tags: ["explorar", "explotar", "bandits"],
  },
  {
    slug: "q-learning",
    name: "Q-Learning",
    aliases: ["Q learning", "DQN", "Deep Q-Network", "Función de valor"],
    category: "reinforcement-learning",
    difficulty: "advanced",
    type: "technique",
    shortDefinition: "Un algoritmo de aprendizaje por refuerzo que aprende cuánto vale cada acción en cada situación para después elegir la mejor.",
    simpleExplanation:
      "El agente mantiene una tabla mental: «si estoy aquí y hago esto, ¿cuánta recompensa obtendré a la larga?». Con cada experiencia actualiza su estimación. Cuando las estimaciones son buenas, basta elegir la acción de mayor valor.",
    technicalExplanation:
      "Aprende la función Q(s, a) mediante la actualización de Bellman: Q(s,a) ← Q(s,a) + α[r + γ·maxₐ′ Q(s′,a′) − Q(s,a)]. Es un método *off-policy*. Deep Q-Network (Mnih et al., 2013) reemplazó la tabla por una red neuronal y aprendió a jugar juegos de Atari a partir de píxeles, usando *experience replay* y una red objetivo para estabilizar.",
    math: {
      formula: "Q(s,a) ← Q(s,a) + α · [ r + γ · maxₐ′ Q(s′,a′) − Q(s,a) ]",
      symbols: [
        { symbol: "Q(s,a)", meaning: "Valor estimado de hacer la acción a en el estado s" },
        { symbol: "α", meaning: "Tasa de aprendizaje" },
        { symbol: "r", meaning: "Recompensa inmediata" },
        { symbol: "γ", meaning: "Factor de descuento: cuánto importan las recompensas futuras" },
        { symbol: "maxₐ′ Q(s′,a′)", meaning: "Mejor valor esperado desde el siguiente estado" },
      ],
    },
    whyItMatters: "Es uno de los algoritmos fundacionales del RL y el origen del deep RL moderno.",
    useCases: ["Videojuegos", "Control", "Enseñanza de RL"],
    prerequisites: ["reinforcement-learning", "policy"],
    relatedTerms: ["reinforcement-learning", "policy", "exploration-exploitation"],
    nextTerms: ["rlhf"],
    tags: ["dqn", "bellman", "valor"],
    sources: [{ title: "Playing Atari with Deep Reinforcement Learning", authors: "Mnih et al.", year: 2013, url: "https://arxiv.org/abs/1312.5602", kind: "paper" }],
  },
];
